### ISSUE TITLE
Calculation of effective skin temperature in Noah LSM when urban fraction is less than 1

### ISSUE THREAD

**Issue by dmey** [wrf-model/WRF#1028]
In https://github.com/wrf-model/WRF/blob/master/phys/module_sf_noahdrv.F, I do not quite understand the calculation of the effective skin temperature (later used by the `SFLX` subroutine in https://github.com/wrf-model/WRF/blob/master/phys/module_sf_noahlsm.F). 

Is this meant to be calculated as a weighted average? If so, the current formula used below does not appear to be correct:

https://github.com/wrf-model/WRF/blob/bf4dfb1b6479c1352035324452cec5aee5972db9/phys/module_sf_noahdrv.F#L920

Physically, this seem to also be incorrect as the temperature becomes negative when the urban fraction is large and TS is larger than TSK.

If this is the case, and `T1` is meant to be a weighted average, I would suggest something like:

```
T1 = (FRC_URB2D(I,J) * TS_URB2D(I,J)) + (1 - FRC_URB2D(I,J)) * TSK(I,J)
```

Or better also using emissivity when calculating the weighted average as per SB law.

**Comment by davegill** [comment]
@dmey 
Good use for an issue.

@weiwangncar @dudhia @barlage 
Wei, Jimy, Mike,
Would you guys take a look at this issue please.

**Comment by dudhia** [comment]
Explain this issue with numbers. I don't see it.

**Comment by dmey** [comment]
``` py
def f(FRC_URB2D, TSK, TS_URB2D):
    return (TSK- FRC_URB2D * TS_URB2D ) / (1 - FRC_URB2D)
```
```
> f(FRC_URB2D, TSK, TS_URB2D)
# Returns
> -244.99999999999864
```

However still unclear as to what this is meant to do.

**Comment by dudhia** [comment]
FRC_URB should be between 1 and 0. If it is not, that is a problem.
Else both TSK and TS_URB2D should be realistic.
Jimy

**Comment by davegill** [comment]
It looks like the original equation is
TSK = T1(1-FRC_URB2D) + FRC_URB2D*TS_URB2D
Which is just the weighted mean.

However, we know TSK, FRC_URB2D, and TS_URB2D. To back out T1, then we end up with 
T1 = (TSK - FRC_URB2D*TS_URB2D ) / (1-FRC_URB2D)

Maybe we could bound T1 to be between TSK and TS_URB2D?

**Comment by dudhia** [comment]
There should be a special case if FRC_URB2D is too close to 1.
For cats 31, 32 and 33, the max is 0.95, so this can only happen
with special input. We have a FRC_URB2D dataset in geogrid
and someone should check that for values of 1.

**Comment by dmey** [comment]
@davegill I am more concerned with the physical meaning of `TSK`, `T1` and `TS_URB2D`? If the represent the same quantity should you not apply a weighted average? As per comment, the condition is only there to "check is only there to redefine the natural surface in cities as the "NATURAL" category in the VEGPARM.TBL" so it would make sense to satisfy such condition if ( FRC_URB2D(I,J) < 0.99 ). I may be misreading this but I am not sure that @dudhia comments re  0-1 bounds is about the same issue about how the averaging is done (assuming that we are referring to the same thing...)

**Comment by dudhia** [comment]
If FRC_URB2D is 1, the value of T1 would be arbitrary because it won't
contribute to TSK. If we need T1 we can set it to the urban value.

**Comment by dmey** [comment]
> If FRC_URB2D is 1, the value of T1 would be arbitrary because it won't
contribute to TSK. If we need T1 we can set it to the urban value.

@dudhia this is already be the case -- see below:

``` fortran
		 IF ( FRC_URB2D(I,J) < 0.99 ) THEN
                   if(sf_urban_physics.eq.1)then
                     T1= ( TSK(I,J) -FRC_URB2D(I,J) * TS_URB2D (I,J) )/ (1-FRC_URB2D(I,J))
                   elseif((sf_urban_physics.eq.2).OR.(sf_urban_physics.eq.3))then
                     T1=tsk_rural_bep(i,j)
                   endif
	         ELSE
		 T1 = TSK(I,J)

```

my issue is with `FRC_URB2D < 1 (or as it has been implemented < 0.99)` and `f_urban_physics.eq.1`, in which case I would think that the averaging should be done as:

``` fortran
T1 = (FRC_URB2D(I,J) * TS_URB2D(I,J)) + (1 - FRC_URB2D(I,J)) * TSK(I,J)
```

**Comment by dudhia** [comment]
TSK should be the weighted average, not T1.

**Comment by dmey** [comment]
This is not an issue as `T1` here represents the un-weighted average recovered from the weighted average returned by the sf_urban_physics=1 as @dudhia pointed out. I will close this now.

**Comment by 1560010** [comment]
hello，Have you figured out the flow and formula of land surface temperature calculation in WRF?
I still have this problems.
