### ISSUE TITLE
Tutorial link is broken

### ISSUE THREAD

**Issue by devdattakulkarni** [wrf-model/WRF#1045]
I am trying to install WRF and wanted to checkout the tutorial at:
https://www2.mmm.ucar.edu/wrf/OnLineTutorial/index.htm

But looks like the link is broken. I am getting 404 Not Found error.

**Comment by davegill** [comment]
@devdattakulkarni @kkeene44 
Dev,
Thanks!
For a quick fix, make the last extension "php" instead of "htm".

I am closing this as it really belongs on the WRF Forum.

**Comment by devdattakulkarni** [comment]
@davegill Thanks!
.php extension works.
