### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by devdattakulkarni** [wrf-model/WRF#1046]
I am trying to compile WRF for a Linux Ubuntu 16.04 host and am running into compilation errors. Here is a one of the first errors in the log. There are several similar errors throughout the log.

I think I have installed all the required libraries and have set appropriate environment variables.

Any suggestions on what might be the issue?

/lib/cpp -P -nostdinc -I/home/vagrant/WRF/inc -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM  -DDM_PARALLEL -DNETCDF -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0  -I. -traditional-cpp   module_dm.G  > module_dm.bb
module_dm.G:4137:0: fatal error: nest_interpdown_unpack.inc: No such file or directory
 #include "nest_interpdown_unpack.inc"
 ^
compilation terminated.
../configure.wrf:345: recipe for target 'module_dm.o' failed
make[2]: [module_dm.o] Error 1 (ignored)

**Comment by davegill** [comment]
Please post this to the WRF Forum: forum.mmm.ucar.edu

**Comment by devdattakulkarni** [comment]
I was able to compile WRF successfully by following the exact steps from the 

https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compilation_tutorial.php
