### ISSUE TITLE
Adding wind at 22 meter to the model

### ISSUE THREAD

**Issue by anahita5355** [wrf-model/WRF#1075]
Hi,

I tired to add wind at 22 meter to the model both WRF-3.9 and WRF-4.0.1, But I faced some problems. Here is I put in the forum (https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=43&t=8789):

 For my work I need to have wind at 22 meter in the model, for this reason I modified some codes in the model but when I run the model with more than one processor, there are some stripes in U22/V22 with -inf to inf values. I do not have this problem when I run the model with single processor. So there is a problem with running the model with multiple processors or input/output. I have attached all modified codes. The lines that I edited or added have "AF" in them.

I think the problem should be in Registry.

Thanks,
Ana

[io_grib1.F.txt](https://github.com/wrf-model/WRF/files/4165991/io_grib1.F.txt)
[io_grib2.F.txt](https://github.com/wrf-model/WRF/files/4165992/io_grib2.F.txt)
[module_bl_ysu.F.txt](https://github.com/wrf-model/WRF/files/4165993/module_bl_ysu.F.txt)
[module_first_rk_step_part1.F.txt](https://github.com/wrf-model/WRF/files/4165994/module_first_rk_step_part1.F.txt)
[module_initialize_real.F.txt](https://github.com/wrf-model/WRF/files/4165996/module_initialize_real.F.txt)
[module_pbl_driver.F.txt](https://github.com/wrf-model/WRF/files/4166000/module_pbl_driver.F.txt)
[module_sf_sfclay.F.txt](https://github.com/wrf-model/WRF/files/4166001/module_sf_sfclay.F.txt)
[module_sf_sfclayrev.F.txt](https://github.com/wrf-model/WRF/files/4166002/module_sf_sfclayrev.F.txt)
[module_surface_driver.F.txt](https://github.com/wrf-model/WRF/files/4166003/module_surface_driver.F.txt)
[Registry.CONVERT.txt](https://github.com/wrf-model/WRF/files/4166004/Registry.CONVERT.txt)
[Registry.EM_COMMON.txt](https://github.com/wrf-model/WRF/files/4166005/Registry.EM_COMMON.txt)
[Registry.EM_COMMON.var.txt](https://github.com/wrf-model/WRF/files/4166006/Registry.EM_COMMON.var.txt)

**Comment by davegill** [comment]
@anahita5355 
Ana,
This question is more appropriate for the forum.

**Comment by anahita5355** [comment]
I posted it to forum, but nobody answered me.

**Comment by dudhia** [comment]
I don't see any obvious reason for this problem, but you did not need to
change the pbl_driver or ysu pbl
scheme because that uses only the 10 m wind for some calculations over
water. Also the grib changes should
not be necessary if you use standard netcdf output.
Jimy

**Comment by anahita5355** [comment]
Hi Jimmy, 
Thanks for your answer,May I ask what calculation use 10 m wind? 
I ran the model for 72 hours for some time steps I do not have those missing values stripes.
Thanks,
Ana

**Comment by anahita5355** [comment]
Attached is showing the missing values stripes.
![Screen Shot 2020-02-07 at 9 01 12 AM](https://user-images.githubusercontent.com/60746920/74035585-8725c200-4988-11ea-8616-565bcc761284.png)

**Comment by kkeene44** [comment]
@anahita5355 @dudhia 
In addition to what is mentioned above, @davegill also responded to the striping issue on the forum back on Feb 6th: https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=43&t=8789&p=15786#p15786
