### ISSUE TITLE
Delete .gitignore in released file

### ISSUE THREAD

**Issue by zxdawn** [wrf-model/WRF#1105]
I'm trying to add some personal functions to WRF-Chem.

So, I downloaded released [WRFV4.1.4](https://github.com/wrf-model/WRF/releases/tag/v4.1.4) and uploaded to my empty private repository.

Then, I cloned the repository and uploaded to the HPC.
But, I got this error when compiling WRF-Chem with KPP:
```
This is KPP-2.1.

KPP is parsing the equation file.
KPP was told to generate WRF conform code
KPP is computing Jacobian sparsity structure.
KPP is starting the code generation.
KPP is initializing the code generation.

 KPP is using the WRF conform integrator routine:
 /yin_raid/xin/tmp_lfr/WRF-4.1.4/chem/KPP/kpp/kpp-2.1/int/WRF_conform/rosenbrock

Fatal error : /yin_raid/xin/tmp_lfr/WRF-4.1.4/chem/KPP/kpp/kpp-2.1/int/WRF_conform/rosenbrock.f90: Can't read file
Program aborted
make: *** [cb05_sorg_aq_Integrator.f90] Error 3
grep: ../../../module_kpp_cb05_sorg_aq_Integr.F: No such file or directory
Makefile:50: warning: overriding commands for target `.F.o'
../../../../configure.wrf:379: warning: ignoring old commands for target `.F.o'
Makefile:58: warning: overriding commands for target `.c.o'
../../../../configure.wrf:408: warning: ignoring old commands for target `.c.o'
```

BTW, if I downloaded the official release directly on the HPC, it works well.

Actually, this issue is caused by the `*.f90` in the `.gitignore` ...
I think it's better to delete `.gitignore` in the released file.

**Comment by davegill** [comment]
Xin,
Please make this a PR since we do not test KPP.

**Comment by zxdawn** [comment]
@davegill I think the better solution is adding `!` in .gitignore to keep some .f90 files for kpp.

But, I find some other `.f90` files and I'm not sure whether they're also needed to be kept.

Could you check the attached txt file? Then, I can create a better PR :)
[f90.txt](https://github.com/wrf-model/WRF/files/4259131/f90.txt)

**Comment by davegill** [comment]
@zxdawn 
Xin,
Do a clean clone of the repo
Any .f90 in that repo should not be "ignored".

With a quick look, I think that the files in the list that you have should all remain important to the user to know about diffs.

**Comment by zxdawn** [comment]
@davegill Got it. Just remove `.gitignore`? How about `.git` and `.github`?

**Comment by davegill** [comment]
@zxdawn 
Xin,
The WRF build generates many *.f90 files that we DO want to ignore. For a first cut at a PR, maybe something that indicates the f90 locations to NOT ignore (negation starts with a "!"). I have not tested this following example!

OLD
```
*.f90
```

NEW
```
!chem/KPP/kpp/kpp-2.1/util/*.f90
```

If that works out, we can add in other directories of interest following your example (such as the more complicated case of var).

**Comment by zxdawn** [comment]
@davegill Thanks. I will try to keep the kpp first. If the compilation has no error on the HPC, I will create a PR.

**Comment by davegill** [comment]
@zxdawn 
Xin,
Let me know if you have troubles. We need to fix this. We MUCH appreciate you assistance.
