### ISSUE TITLE
Obs nudging tile issue

### ISSUE THREAD

**Issue by brianreen** [wrf-model/WRF#1115]
When observations are on the edge of a tile there is an error in the determination of the potential temperature difference between the model and the observation for observation nudging.

In subroutine errob in phys/module_fddaobs_rtfdda.F when it calculates the potential temperature difference between the model and the observation (stored in ERRF(3,N)), it interpolates the model value of tb.  The interpolation relies on adjacent points and thus when the ob is on the edge of a tile the interpolation will need points outside of the tile.  However, the points outside of the tile are not set correctly (in the case tested they were set to 0.0).  This results in the difference between the model and the observation being incorrect and thus the model nudges towards the wrong value.

In errob, the model potential temperature is accessed via variable tb, which is listed as:
REAL,   INTENT(IN) :: tb( ims:ime, kms:kme, jms:jme )
In the case tested where the problem occurred the observation was at j=82 and the various j end values are:
jme=93
jde=205
jte=82
Thus, it would appear that the j values needed for the interpolation should be present in tb since j=83 < jme=93.  However all j=83 values of tb used by the interpolation are set to 0.0.

The variable tb in subroutine errob is passed into errob from fddaobs_driver (phys/module_fddaobs_driver.F) from tb.  It is passed into fddaobs_driver by subroutine first_rk_step_part2 (dyn_em/module_first_rk_step_part2.F) from grid%th_phy_m_t0. [In earlier versions (e.g., V3.9.1.1) instead of grid%th_phy_m_t0, grid%t_2 was passed in (I think the change is related to the hybrid vertical coordinate), but I have not tested to see if the problem occurs when grid%t_2 is instead passed.]

The problem is resolved for the case tested by adding th_phy_m_t0 to the following line in Registry/Registry.EM_COMMON:
halo      HALO_OBS_NUDGE dyn_em 24:ph_2,p,uratx,vratx,tratx,kpbl
so that it is instead:
halo      HALO_OBS_NUDGE dyn_em 24:ph_2,p,uratx,vratx,tratx,kpbl,th_phy_m_t0

However, I lack sufficient knowledge of WRF halos to know if this is the proper fix and so am not currently submitting this as a pull request.

The other variables used by subroutine errob to calculate the model vs. obs differences do not have the issue of being set to zero outside the tile, even though they are not included in the halo statement and are dimensioned the same, e.g.:
REAL,   INTENT(IN) :: qvb( ims:ime, kms:kme, jms:jme )

Should all variables dimensioned similarly be included in the halo statement if one is going to access values outside of the tile?  If this is the case perhaps the line in the Registry should be:
halo      HALO_OBS_NUDGE dyn_em 24:ph_2,p,uratx,vratx,tratx,kpbl,u_2,v_2,th_phy_m_t0,moist,pb,p

**Comment by davegill** [comment]
@brianreen 
Brian,

The th_phy_m_t0 field is the THeta variable for PHYsics Minus T0 (so, in v3.9.1.1 and prior, this is identically the t_2 field). This field th_phy_m_t0 was introduced when the moist theta option became part of the initial conditions (v4.0).

I would agree that it is a reasonable test to temporarily use the actual argument grid%t_2 to see if those tb values are all still zero at j=83.

IF tb != 0 at j=83
include the th_phy_m_t0 on the HALO as you suggest

IF still tb == 0 at j=83
we need to dig into the code a bit more

**Comment by brianreen** [comment]
@davegill 
Dave,
With t_2 passed in instead of th_phy_m_t0:
tb != 0 at j=83
Therefore, I will include th_phy_m_t0 on the HALO.  

However, would it be safer to also include the other variables obs nudging uses on off-tile gridpoints in the HALO statement?  Are the off-tile values for the other variables non-zero because of other HALO statements, and thus it would be safer to explicitly include them in the obs nudging HALO statement?  That way if the execution of the other HALO statements were configuration dependent, having the variables in the obs nudging HALO statement would ensure that regardless of configuration obs nudging would have access to the off-tile variables it needs.  I do not fully understand how the HALO's work and so I am not sure how to best approach this.

**Comment by davegill** [comment]
@brianreen 
Brian,
Without spending too much time on this (actually, _no_ time, so far), it is likely that the other variables are already communicated before getting into first Runge-Kutta step. The FDDA is handled early on (similar to physics). All of the variables are communicated ahead of time. The new variable that is the dry potential temperature was never added into the mix of communicated fields as it was used for column-oriented computations (so no need for comms).

This is clearly a part of the code where the th_phy_m_t0 needs to be communicated due to horizontal interpolation.

You have identified the location to add in the communication, and demonstrated the effectiveness of add in that HALO communcation. The grid%t_2 test indicates that the issue was simply using a field that had never been communicated.

You are good to go for a PR, and only need to add in the single new field th_phy_m_t0 to the HALO_OBS_NUDGE statement.

**Comment by brianreen** [comment]
Solved in PR #1118.
