### ISSUE TITLE
WRF not finding netcdf.inc

### ISSUE THREAD

**Issue by afernandezody** [wrf-model/WRF#1116]
Hello,
I have installed both netcdf-c & netcdf-fortran, which wrote netcdf.inc to /usr/local/include. However, the WRF configuration keeps producing the error 
```
Error : Not found /home/ubuntu/netcdf-c/include/netcdf.inc
        Please check this installation of NetCDF and re-run this configure script
./configure: 637: exit: Illegal number: -1
```
Thanks.

**Comment by sldcyh** [comment]
Seems WRF is not correctly finding your netcdf fortran interface (netcdf.inc). Please check the environment variable NETCDF by using echo $NETCDF.

**Comment by afernandezody** [comment]
Hi @**sldcyh**,
It's /home/ubuntu/netcdf-c. The thing is that I installed netcdf-c and netcdf-fortran in 2 separate subdirectories so what I don't understand is how these two apps click with the WRF installation. Thanks.

**Comment by sldcyh** [comment]
> Hi @**sldcyh**,
> It's `/home/ubuntu/netcdf-c`. The thing is that I installed netcdf-c and netcdf-fortran in 2 separate subdirectories so what I don't understand is how these two apps click with the WRF configuration. Thanks.

Hi,
What I did is install netcdf-c and netcdf-fortran in the same DIR. You can install them in '/home/ubuntu/netcdf' for your case. You should be able to find netcdf.inc in '/home/ubuntu/netcdf/include' after this. 

Or, maybe try to set the NETCDF environment variable pointing to your netcdf fortran folder, so WRF installation can find the netcdf.inc file.

Hope this can help!

**Comment by afernandezody** [comment]
Yes, I also installed them in the same directory. Thanks.
