### ISSUE TITLE
WRF compilation not finding librsl_lite.a

### ISSUE THREAD

**Issue by afernandezody** [wrf-model/WRF#1124]
Hello,
The WRF compilation (em_real) is producing the error:
`gfortran: error: /home/ubuntu/WRF/external/RSL_LITE/librsl_lite.a: No such file or directory
`
when using the GNU compilers (dm). Not sure if this is of any help, but the static libraries generated thus far are:

> /home/ubuntu/WRF/external/esmf_time_f90/libesmf_time.a
> /home/ubuntu/WRF/external/io_grib_share/libio_grib_share.a
> /home/ubuntu/WRF/external/fftpack/fftpack5/libfftpack.a
> /home/ubuntu/WRF/external/io_int/libwrfio_int.a
> /home/ubuntu/WRF/external/io_netcdf/libwrfio_nf.a
> /home/ubuntu/WRF/external/io_grib1/libio_grib1.a
> /home/ubuntu/WRF/main/libwrflib.a
> 

Thanks.

**Comment by davegill** [comment]
@afernandezody 
This is probably more of a question for the WRF forum: forum.mmm.ucar.edu.

1. There is no rsl library. Was there a compiler error? 
2. What version / branch of the WRF code is this?
3. What compiler and version?
4. Is this perhaps related to MPI or a serial build?
5. Is this a new occurrence?

These are questions that would be addressed in a back-and-forth posting on the forum. Please start with this additional information on the forum.

**Comment by afernandezody** [comment]
Hi @**davegill**, 
Thanks. I'll do so.
