### ISSUE TITLE
WRF-CHEM, running error

### ISSUE THREAD

**Issue by arman-abdipour** [wrf-model/WRF#1143]
Hi,
The following error occur when running wrf-chem that --> chem_opt=number(0,1,....).
if remove chem_opt in namelist.input, The problem will be solved...
 {
module_io_quilt_old.F        2931 T
  ------ ERROR while reading namelist physics ------
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:   11345
ERRORS while reading one or more namelists from namelist.input.
-------------------------------------------
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
}
Could you help me with this?
What is the solution to this error/problem ?
version:
wrf-chem v3.9

**Comment by stacywalters** [comment]
Could you please send the namelist.input file and the rsl.error.0000 that
contains
the above error statements as email attachments?

Stacy

**Comment by davegill** [comment]
@arman-abdipour 
Please re-post this to forum.mmm.ucar.edu. This is a user-services concern.

Include the namelist.input and the tar'ed up rsl* files as attachments.

**Comment by davegill** [comment]
@arman-abdipour 
The first thing is to make sure that this has not been fixed in the release-v4.2 branch.
