### ISSUE TITLE
Bug with clWRF diagnostics

### ISSUE THREAD

**Issue by ccarouge** [wrf-model/WRF#1193]
The times of the max/min have a bug. Sometimes, at some points, the times of the min/max are lower than XTIME for the first date of the period covered by the diagnostic.

I think the issue is the times aren't reinitialised with the values. So if the max or min happens at the time step the values are reinitialised then the times aren't given the proper value. The times keep the value they had for the previous period.

I know this is a community-based code so I don't know if it's the best place to report this.

**Comment by davegill** [comment]
@ccarouge 
Claire,
Yes, this is a community code, and thanks for helping out.
Could you provide a bit of print out that helps us understand the error you are seeing? Also, maybe the part of the namelist that is doing the diagnostics.
Would you be interested in tracking this error down? We want to get as many developers as possible involved in our code management and maintenance.

**Comment by ccarouge** [comment]
For more details. The person with the issue had set the diagnostics in namelist.input with:
```
 output_diagnostics                  = 1,
 auxhist3_outname                    = "wrfxtrm_d<domain>_<date>"
 io_form_auxhist3                    = 2
 auxhist3_interval                   = 1440
 frames_per_auxhist3                 = 30
```

So it calculates the extremes over each 24 hours window (1440 minutes). So one would expect the time of the min/max to be bound by XTIME at the start and end of the 24 hours. The simulation started at 18:00 and he looked at the TT2MAX for 2017-04-16_18:00:00. Looking at the corresponding values of XTIME in wrfout, we find XTIME is between 30240 and 31680 minutes.
Looking at TT2MAX with ncview and changing the range between the automatic min and 30240, we clearly see some points have values much lower than 30240. Which shouldn't happen.

My assumption is there is an issue in the code that reinitialise the diagnostics for each period (here every 24 hours). This reinitialisation (lines 155 - 190 in module_diag_cl.F) doesn't include the time variables. So if the min/max happen on the time step the reinitialisation occurs, the time variables aren't modified. 

The problem is coming from someone else and I don't have the time currently to test my hypothesis. I'm putting it here to help anyone who might have the issue or to jolt my memory once I have more time.

**Comment by davegill** [comment]
@ccarouge 
Claire,
Thank you for the detailed information.

**Comment by christopherthomas** [comment]
I am the person who Claire mentioned that noticed this issue. I think it will probably be a pretty simple fix. I can take a look at it if that is within WRF protocols, but it may be a couple of weeks before I can do this. Is there an upcoming incremental release deadline that I should be aware of?

**Comment by davegill** [comment]
@christopherthomas 
Christopher,
We produce an incremental release every couple of months, so do not drive your schedule based on that continual process - there is ALWAYS a minor release branch available to update. When you are ready to take a look at this issue, I would like to assist you in the process.

**Comment by dudhia** [comment]
Is this related to restarts at all? It wasn't clear from these messages.

**Comment by christopherthomas** [comment]
It occurs in a run with no restarts.

**Comment by dudhia** [comment]
Thanks.

**Comment by christopherthomas** [comment]
@davegill 
Dave, I have made a fix for this problem (very simple fix) and tested it to my satisfaction on the WRF setup for which I first noted the problem. The fix changes the TT2MAX and TT2MIN values only for those points/days for which they were bad, leaving all others unchanged. It produces TT2MAX and TT2MIN values in agreement with those produced by outputting T2 for all times steps and calculating TT2MAX and TT2MIN directly (using R). The test were made using V4.1.2 but the file in question (module_diag_cl.F) has not changed in V4.2.  I have attached a patch. What else should I do? 
[module_diag_cl.F_patch.txt](https://github.com/wrf-model/WRF/files/4761756/module_diag_cl.F_patch.txt)

**Comment by davegill** [comment]
@christopherthomas 
Take a look at this wiki page:
https://github.com/wrf-model/WRF/wiki/Workflow-for-WRF-Code-Modification

This is a bug fix, so follow the parts for that section (instead of "develop").

We want you to issue a pull request to the WRF repository. It is good for us, and we want it to be something that you are then comfortable in doing  as often as necessary. We will assist you along the way with comments.

Use branch release-v4.2.1 (the next one that is coming out).

**Comment by dudhia** [comment]
I guess similar changes are needed to initialize all the other times too.
