### ISSUE TITLE
Usage of macros is incompatible with clang cpp -traditional-cpp

### ISSUE THREAD

**Issue by irowebbn** [wrf-model/WRF#1206]
**Problem Description**
When compiling on MacOS using both the gcc and clang compiler configurations, building fails when the system version of `cpp` is used. The reason has to do a difference in the way that the MacOS system version of cpp (for me, Apple clang version 11.0.3 clang-1103.0.32.62) treats spacing in macros when using the `-traditional-cpp` flag. The difference could be considered a bug in llvm, but the [bug report documenting the difference](https://bugs.llvm.org/show_bug.cgi?id=18011) has been untouched since 2013 and the developers have explicitly expressed their intentions not to provide more than bare-bones support for `-traditional-cpp`.

The specific problem is that the clang distribution of cpp does not recognize and replace usages of macros with parameters if the macro is used with a space between the macro name and the opening parenthesis. Technically, there cannot be a space there in the macro definition, but 

As an example, in `phys/module_mp_fast_sbm.F`, a macro is defined like this:
```Fortran
#define DM_BCAST_MACRO_R16(A) CALL wrf_dm_bcast_bytes(A, size(A)*R16SIZE)
```
and used like this:
```Fortran
DM_BCAST_MACRO_R16 ( FAF1 )
```

In most instances, there is no space between the macro name and the opening parenthesis, but in this particular file there are a few instances that cause compilation to fail, because the macros are never replaced with valid Fortran code and therefore cannot be compiled to object files.

**Current Workaround**:
Changing the $PATH or creating a symbolic link to use the actual gcc preprocessor rather than the clang version called by default when using `cpp`. The real gcc version exhibits correct behavior with the flag.

**Proposed Solution**:
Remove "non-standard" spacing from macros. I searched through all the Fortran files, and the only one that uses this spacing that trips up the clang distribution of cpp is `phys/module_mp_fast_sbm.F`. Removing the space between the macro name and parenthesis is sufficient to fix the issue.

I have made local commits to fix this problem, but I haven't contributed to this project before and don't know what the correct process is. If everyone concurs on this solution, I can work on putting in a PR for this. It should only be one commit with one file diff.

**Comment by davegill** [comment]
@irowebbn
Isaac,
We would _very much_ like to receive a pull request from you!

Take a look at our wiki page:
https://github.com/wrf-model/WRF/wiki/Workflow-for-WRF-Code-Modification

You are going to make a change to the release-v4.2.1 branch (a bug fix branch). In the wiki there are a places where the instructions are exclusively for the develop branch or exclusively for the release branch.

We will walk you through some more steps once we see your PR. Expect there to be a bit of iterative back-and-forth.
