### ISSUE TITLE
WRF V 4.2 Compiling Error

### ISSUE THREAD

**Issue by GAaronAlexander** [wrf-model/WRF#1220]
Hello!

I am working to compile WRF on a GNU system. I have successfully compiled Netcdf, zlib, libpng, Mpich, and Jasper for a basic WRF compiling (Netcdf4 not enabled). All libraries have passed internal 'make check' tests and suggested WRF Fortran +C+Netcdf tests outlined on the WRF online tutorial. 

I have attached both my configure and compile log files. There seems to be a fatal error occurring

 from 'module_bc.mod' being unable to be found. I cannot make heads or tales of this error and would appreciate any assistance! 

Thanks! 
[configure_wrf.txt](https://github.com/wrf-model/WRF/files/4814491/configure_wrf.txt)
[log_compile.txt](https://github.com/wrf-model/WRF/files/4814492/log_compile.txt)

**Comment by weiwangncar** [comment]
@GAaronAlexander This should go to the Forum (https://forum.mmm.ucar.edu/). Thanks.
