### ISSUE TITLE
issue in building WRF

### ISSUE THREAD

**Issue by sloohe10** [wrf-model/WRF#1224]
Hello everyone,

I new to WRF, configure, and configure it.

I followed the steps of compiling WRF from this page:
https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compilation_tutorial.php

when I reached "Building WRF" section, and typed this command: ./configure

I get this error : 

************************** W A R N I N G ************************************
 
The moving nest option is not available due to missing rpc/types.h file.
Copy landread.c.dist to landread.c in share directory to bypass compile error.
 
*****************************************************************************
*****************************************************************************
This build of WRF will use classic (non-compressed) NETCDF format
*****************************************************************************

I have also tried, setenv NETCDF_classic 1, and it did not work.

thank you all

[WRF configuration issue.txt](https://github.com/wrf-model/WRF/files/4822493/WRF.configuration.issue.txt)

**Comment by davegill** [comment]
@sloohe10 
Please post this questions to the WRF Forum: 
https://forum.mmm.ucar.edu/

If this is a desktop computer or laptop, consider using a docker container:
https://github.com/davegill/wrf-coop/blob/master/README_tutorial.md

**Comment by sloohe10** [comment]
ok thank you
