### ISSUE TITLE
time series + solar diagnostics = seg fault

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#1227]
Franciano Puhales

I'm doing some tests with the WRF time series output and I had an issue when the solar diagnostic option is turned on.

The error was very generalist:
--------------------------------------------------------------------------
mpirun noticed that process rank 2 with PID 0 on node nestor exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

To try to understand it I checked the Registry files (the "WRF unicorns factory"). I realized that 2 ts profile variables lack when "solar_diagnostics = 1" (process_time_series==2)

package   tseries               process_time_series==1                 -             state:ts_hour,ts_u,ts_v,ts_q,ts_t,ts_psfc,ts_glw,ts_gsw,ts_hfx,ts_lh,ts_tsk,ts_tslb,ts_clw,ts_rainc,ts_rainnc,ts_u_profile,ts_v_profile,ts_gph_profile,ts_th_profile,ts_p_profile,ts_w_profile

package   tseries_add_solar     process_time_series==2                 -  state:ts_hour,ts_u,ts_v,ts_q,ts_t,ts_psfc,ts_glw,ts_gsw,ts_hfx,ts_lh,ts_tsk,ts_tslb,ts_clw,ts_rainc,ts_rainnc,ts_u_profile,ts_v_profile,ts_gph_profile,ts_th_profile,ts_cldfrac2d,ts_wvp,ts_lwp,ts_iwp,ts_swp,ts_lwp_tot,ts_iwp_tot,ts_swp_tot,ts_re_qc,ts_re_qi,ts_re_qs,ts_re_qc_tot,ts_re_qi_tot,ts_re_qs_tot,ts_tau_qc,ts_tau_qi,ts_tau_qs,ts_tau_qc_tot,ts_tau_qi_tot,ts_tau_qs_tot,ts_cbaseht,ts_ctopht,ts_cbaseht_tot,ts_ctopht_tot,ts_clrnidx

ts_p_profile and ts_w_profile are not present when process_time_series==2

I included these 2 variables and recompiled the code. I was able to run with solar_diagnostics = 1 without any error.

I don't know if it is sufficient to fix this issue, but it seems to work now.

Please, let me know what you think about it.

**Comment by davegill** [comment]
@weiwangncar @smileMchen @dudhia
Wei and MIng,
Are either of you familiar with the time series code? Do we really only need the pressure and vertical velocity profiles to be included?

Jimy,
Who is a solar person that we could have take a look at this?

**Comment by fpuhales** [comment]
Just to add some extra information about the issue before I included these 2 variables on package tseries_add_solar:

I was using ts_buf_size = 200. I've tried other values. Although the time step when the Segmentation fault error occurred change, it still was happening. 
The first time I notice this issue was when I used more than one station. 
If solar_diagnostics = 0, I was able to run without any problem.

**Comment by smileMchen** [comment]
@davegill 
Dave,
We need to include those two profiles in Registry ( package tseries_add_solar process_time_series==2 ). Franciano is right.

**Comment by dudhia** [comment]
Send it to Pedro

**Comment by dudhia** [comment]
The fix makes sense, but Pedro could check it.

**Comment by davegill** [comment]
@pedro-jm 
Pedro,
We would like you to review this PR. When using solar and selecting the time series diagnostics, there is a segfault. We have added a couple of extra fields to the package, and that seems to work.

**Comment by pedro-jm** [comment]
@davegill 
OK I will take a look to the PR #1228
Pedro
