### ISSUE TITLE
CRTM coefficients linked to /glade

### ISSUE THREAD

**Issue by lukeconibear** [wrf-model/WRF#1238]
The CRTM coefficients within [`WRF/var/run/crtm_coeffs`](https://github.com/wrf-model/WRF/blob/master/var/run/crtm_coeffs) are linked to `/glade/work/wrfhelp/WRFDA_files/crtm_coeffs_2.3.0`, which local users do not have access to.

There is a local copy of the CRTM coefficients within [`WRF/var/external/crtm_2.3.0`](https://github.com/wrf-model/WRF/tree/master/var/external/crtm_2.3.0).

Should this link not be to this local version, as below?

```bash
rm -f WRF/var/run/crtm_coeffs
ln -s -d WRF/var/external/crtm_2.3.0 WRF/var/run/crtm_coeffs
```

**Comment by liujake** [comment]
Please see https://www2.mmm.ucar.edu/wrf/users/wrfda/updates-4.1.html

**Comment by lukeconibear** [comment]
Okay, thanks
