### ISSUE TITLE
Run wrf.exe error when using surface analysis nudging

### ISSUE THREAD

**Issue by pengzimu** [wrf-model/WRF#1240]
Hi,
I met with a problem when I ran WRF with surface analysis nudging. 
I successfully created met_em* files by WPS. And then I successfully got metoa_em* files and wrfsfdda files by running obsgrid.exe. After that, real.exe is also run successfully. However, when I ran wrf.exe, the problem occurred and it seemed that wrf.exe stopped while initializing nest domain 3.
Here is a part of message in rsl.error files.

```
d02 2015-08-19_12:00:00  alloc_space_field: domain            3 ,                7252128  bytes allocated
d02 2015-08-19_12:00:00  alloc_space_field: domain            3 ,               40721948  bytes allocated
d02 2015-08-19_12:00:00 *** Initializing nest domain # 3 from an input file. ***
d02 2015-08-19_12:00:00 med_initialdata_input: calling input_input
d02 2015-08-19_12:00:00  Input data is acceptable to use:
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
d02 2015-08-19_12:00:00  Yes, this special data is acceptable to use: SFCFDDA FILE: SURFACE ANALYSES FOR NUDGING
d02 2015-08-19_12:00:00  Input data is acceptable to use:
d02 2015-08-19_12:00:00 Input data processed for aux input   9 for domain   2
d02 2015-08-19_12:00:00  Input data is acceptable to use:
d02 2015-08-19_12:00:00 Input data processed for aux input  10 for domain   2
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS     71 IE     85 JS     48 JE     62
WRF NUMBER OF TILES =   1
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
In grid FDDA
-------------------------------------------
Abort(1) on node 23 (rank 23 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 23
```

I found this problem using the command, `grep -i 'fatal' rsl.*` . The results were shown as below:
```
rsl.error.0023:-------------- FATAL CALLED ---------------
rsl.error.0023:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.error.0028:-------------- FATAL CALLED ---------------
rsl.error.0028:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.error.0029:-------------- FATAL CALLED ---------------
rsl.error.0029:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.error.0034:-------------- FATAL CALLED ---------------
rsl.error.0034:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.error.0035:-------------- FATAL CALLED ---------------
rsl.error.0035:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.out.0023:-------------- FATAL CALLED ---------------
rsl.out.0023:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.out.0028:-------------- FATAL CALLED ---------------
rsl.out.0028:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.out.0029:-------------- FATAL CALLED ---------------
rsl.out.0029:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.out.0034:-------------- FATAL CALLED ---------------
rsl.out.0034:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
rsl.out.0035:-------------- FATAL CALLED ---------------
rsl.out.0035:FATAL CALLED FROM FILE:  <stdin>  LINE:    1076
```

And I tried turning off the "grid_sfdda", namely, only turning on the "grid_fdda". Then the wrf.exe could run successfully.

So I doubt whether this problem is due to a bug in WRFv4.2 which could not run with surface analysis nudging or that I did something wrong in running WRF.

Version infomation:
WRF v4.2
WPS v4.2
OBSGRID v3.7
netcdf-c-4.7.3
netcdf-fortran-4.5.2
ioapi-3.2
jasper-2.0.14
libpng-1.6.37
zlib-1.2.11
Intel 19.1

The attachment below contains namelist, rsl.error and rsl.out.
[namelistAndErrorLog.zip](https://github.com/wrf-model/WRF/files/4880299/namelistAndErrorLog.zip)

p.s. I tried to post this problem in the forum but failed. It showed this message "Forbidden. Message seems to be spam. ". I didn't know what's going wrong.
<img width="947" alt="cannotpost" src="https://user-images.githubusercontent.com/67904073/86619989-227d9a80-bfee-11ea-829a-b3d78ed9795d.png">

**Comment by davegill** [comment]
@pengzimu @kkeene44 
The WRF demons are out to get you!

You are right that the correct place for handling this problem is the WRF forum, so I am going to close this issue.

Kelly,
Just wanting to draw your attention to this forum question.

**Comment by davegill** [comment]
@pengzimu 
When you do post this on the forum, tar up ALL of the rsl.out* and rsl.error.* files. Include those with the namelist.input (which you included here).

**Comment by pengzimu** [comment]
Thanks for Dave's help!
The solution is to set "rinblw" in the namelist.input like this:
```
rinblw                       = 250., 250., 250.,
```
rinblw should be set for each domain, which seems to be new since v3.9.
