### ISSUE TITLE
Speed up writing the TUV.diags file

### ISSUE THREAD

**Issue by zxdawn** [wrf-model/WRF#1242]
The part of [writing `TUV.diags` file](https://github.com/wrf-model/WRF/blob/0d88b5800186d892a882e118425d2e684ded756f/chem/rxn.F#L5464-L5603) for `phot_opt = 4` option is quite slow.

Is it possible to write it in parallel using `nio_tasks_per_group`/`nio_groups` and keep the order?

**Comment by stacywalters** [comment]
The diags can be removed; it was for development purposes only.

Stacy

**Comment by zxdawn** [comment]
@stacywalters So, shall we enable the diags only for debug level > 100?

**Comment by stacywalters** [comment]
That is a reasonable approach.

Stacy

**Comment by davegill** [comment]
@zxdawn @stacywalters 
Xin,
Would you like to put together a PR for this issue? If you target the release-v4.2.1 branch (which seems appropriate), we are shooting for a release around 23 July. So, a PR would need to appear this week or next.

**Comment by zxdawn** [comment]
@davegill Ok, Dave. I will make a PR for this later today.
