### ISSUE TITLE
phys/module_fr_fire_phys.F does not compile with Intel Fortran v13

### ISSUE THREAD

**Issue by milancurcic** [wrf-model/WRF#1262]
**Describe the bug**
An internal subroutine `read_namelist_fire` in phys/module_fr_fire_phys.F is closed with an `end` statement, which violates F2003 standard:

>  C1248 (R1234) SUBROUTINE shall appear in the end-subroutine-stmt of an internal or module subroutine.

This rule has been removed in F2008, however it causes an older version of Intel Fortran compiler (v13) to report:

```
module_fr_fire_phys.f90(755): error #6378: SUBROUTINE must be present on the end-subroutine-stmt of an internal or module subroutine
end
^
compilation aborted for module_fr_fire_phys.f90 (code 1)
```

**To Reproduce**
1. Use compiler and version: ifort (IFORT) 13.1.0 20130121
2. Use namelist options: N/A
3. Output is: See bug description

**Expected behavior**
The behavior is expected for compilers that conform to F2003. However, the solution to change the end statement (phys/module_fr_fire_phys.F, L755) from:

```fortran
end
```

to:

```fortran
end subroutine read_namelist_fire
```

is straightforward and standard conforming with all modern Fortran editions. It will allow recent WRF versions to build with older compilers.

**Screenshots**
n/a

**Attachments**
n/a

**Additional context**
n/a

**Comment by davegill** [comment]
@milancurcic 
 Milan,
We have addressed this issue:
https://github.com/wrf-model/WRF/pull/1223

The WRF release-v4.2.1 will come out tomorrow, which will have that fix.

**Comment by milancurcic** [comment]
Perfect, it didn't come up in my search.

**Comment by davegill** [comment]
@milancurcic 
Milan,
We very much appreciate your active participation on our github site.
