### ISSUE TITLE
IO in registry: explanation for cases with feedback

### ISSUE THREAD

**Issue by hamidrezaomidvar** [wrf-model/WRF#1282]
Hi,

I am looking at some of the options in the wrf registry (i.e. registry.clm), and noticing some options that I cannot find the documentation such as 

`rd=(interp_mask_field:lu_index,iswater)u=(copy_fcnm)`

What confuses me are `interp_mask_field:lu_index,iswate` and `copy_fcnm`. 

What are the implication of these two functions? Is there any documentation that explain using these in the registry? (I have tracked that `d` and `u` options are related to the cases with feedback = 1). Would you please help me to understand this?
Thanks

**Comment by davegill** [comment]
@hamidrezaomidvar 
Hamidreza,
These are good questions. Please post this in the WRF forum: forum.mmm.ucar.edu. That will allow others to see the post and answer.

Short answer:
d: horizontally interpolate to the child domain (usually only with initialization)
u: horizontally feed averaged values to the parent (usually at the end of each group of child steps)
A user can choose which function to perform the horizontal interpolation or the feedback. There are specific arguments that are always in these routines, but a user may add extra fields.
