### ISSUE TITLE
Remove antiquated !DEC$ compiler directives

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#1293]
**Describe the bug**
The !DEC$ directives were for the DEC compiler that was available under VMS and alpha. The last machines we had of those types were in the previous millennia. These directives are breaking modern tools that help us look at static source code compliance.

**To Reproduce**
Here are the existing !DEC$ directives that can be removed:
```
etotheipi:/Users/gill/Desktop/WRF_scala-test>find . -name \*.F -exec grep '\!DEC\$' {} \; -print
!DEC$ IVDEP
./phys/module_ra_rrtm.F
!DEC$ ATTRIBUTES FORCEINLINE
./phys/module_fr_fire_core.F
!DEC$ vector always
!DEC$ vector always
!DEC$ vector always
!DEC$ vector always  
!DEC$ vector always
./dyn_em/module_advect_em.F
!DEC$ ASSUME_ALIGNED dat:64
!DEC$ UNROLL(4)
!DEC$ IVDEP
!DEC$ ASSUME_ALIGNED dat:64
!DEC$ UNROLL(4)
!DEC$ IVDEP
./share/module_bc.F
```

**Expected behavior**
These directives do not cause any troubles whatsoever with compilation or runtime, they are just old legacy pieces that are no longer necessary. Since they are causing our static code analyzer troubles, they can be safely removed.

**Comment by Plantain** [comment]
DEC is still used by the Intel compiler. It's synonymous with the more
contemporary DIR
https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-developer-guide-and-reference/top/language-reference/directive-enhanced-compilation/syntax-rules-for-compiler-directives.html

**Comment by Plantain** [comment]
Looking at git blame, all of those DEC's were actually added by John Michalakes explicitly for the Intel compilers (a5b7321e4cda3704d223c1a0cce4975ddef60ae5 / 87b37986ff19f51d27da1b0ff593d369a38d8aa9)

**Comment by davegill** [comment]
@Plantain 
OK, we'll keep them in there!
Thanks for looking at this.
