### ISSUE TITLE
Symmetric and open BC: corner points missing 

### ISSUE THREAD

**Issue by matzegoebel** [wrf-model/WRF#1311]
**Describe the bug**
In idealized simulations, the routine `set_physical_bc3d` sets the boundary zone points for periodic, symmetric, and open boundary conditions:
https://github.com/wrf-model/WRF/blob/f311cd5e136631ebf3ebaa02b4b7be3816ed171f/share/module_bc.F#L747-L1096
At first, the routine does not set the corner points (e.g., (ids-1,jds-1)): For the y-boundaries it iterates i only from `MAX(ids,its-1)` to  `MIN(ite+1,ide+istag)` and analogously for the x-boundaries (note that for open BC it actually also tries to set the corner points (see line 896), but not effectively, because the RHS values in lines 903-905 are still 0 there, as the y-BC has not been applied yet).

For doubly-periodic BC, the corner points are set correctly afterwards, starting at line 1100. In any other case, however, it seems that the corner points are not assigned and appear as zeros. 
At least that's what I see, when debugging the code with gdb.

These corner points are later used, e.g. in the diffusion module:
https://github.com/wrf-model/WRF/blob/f311cd5e136631ebf3ebaa02b4b7be3816ed171f/dyn_em/module_diffusion_em.F#L5511-L5517
Thus, because `rho(i_start-1,k,j_start-1)=0`, `xkxavg(i_start, k, j_start)` is much smaller than at the other locations.
Inaccuracies must obviously arise.

**Suggested solution**
The corner points should be set also for non-doubly-periodic boundary conditions. This should be easy to achieve by applying lines 747-1096 in module_bc.F twice, the second time only for the corner points. But someone needs to look at this in more detail.

**Comment by dudhia** [comment]
Does this affect the interior result or only the corners?

**Comment by matzegoebel** [comment]
I guess it could affect a lot of things, but I only checked that one example that I posted.
There it affects the SGS UV-flux (titau_12_21) at the corners of the xy-staggered grid and thus also the u and v-tendencies on the corners of the x and y-staggered grid, respectively, so e.g. at (ids,jds)

**Comment by dudhia** [comment]
Double periodic would be the most used, e.g. in LES cases, and I think you
said that one is OK.
The b_wave idealized case uses a periodic channel, so I am wondering if
this proposed change
affects that case or not.

**Comment by matzegoebel** [comment]
yes the b_wave case is a good example. That one should be affected, because it mixes symmetric with periodic BC. But maybe I also overlooked something in the code. I haven't checked it extremely thorougly.

**Comment by dudhia** [comment]
I would encourage a test to see if it makes a difference first.
