### ISSUE TITLE
RRTMK bugs reported

### ISSUE THREAD

**Issue by dudhia** [wrf-model/WRF#1312]
I am attaching the docx file (see if it works) from Soonyoung Roh (NIMS, Korea)
I have looked at this and their issues seem valid. Sent to Songyou Hong for developers to look at.

[Bug_report_On_WRF.docx](https://github.com/wrf-model/WRF/files/5489311/Bug_report_On_WRF.docx)

**Comment by davegill** [comment]
@dudhia 
Jimy,
With just a cursory view, these seem bug fixes seem to be correct.

**Comment by dudhia** [comment]
Yes, Hong thinks so too.

**Comment by weiwangncar** [comment]
Are you going to make a PR?

**Comment by weiwangncar** [comment]
Also, does it affect model results otherwise?

**Comment by weiwangncar** [comment]
I guess the last two do...

**Comment by dudhia** [comment]
The first one might not because it outputs gsw which is the one that
other physics uses, but that swdnb array is going to be wrong for
diagnostics.
The others would but they did not show the impacts of those.
I might do the PR. Hong is contacting the developers. Perhaps they
will provide a fixed code.

**Comment by dudhia** [comment]
Dave,
Hong approves these changes. I will do a PR.
I notice that there is a setting in compile flags where RRTMK is not built.
Is there anything
I need to do to make sure it is? I am compiling the changed code now and
will see if it does these.
Jimy

**Comment by dudhia** [comment]
Dave,
The flag appears in my compilation so I don't expect RRTMK routines to be
compiled. I am using gnu and clang on my laptop. How would you suggest
testing the RRTMK compilation?
Jimy

**Comment by weiwangncar** [comment]
@dudhia Once you have configure.wrf file, search for BUILD_RRTMK, and set the value to 0. However your laptop version of gfortran may not be able to compile this scheme. It looks like you need 9 and above.

**Comment by dudhia** [comment]
The default was 0. It does seem to have built this correctly when I set the
build flag to 1.
Before it had short *.o files, now they are long. I am not sure why
the default build stubs this option out.
Jimy
