### ISSUE TITLE
Coupled WRF/WRF Hydro build fails with Intel HSW/BDW configuration

### ISSUE THREAD

**Issue by tinyendian** [wrf-model/WRF#1325]
Building coupled WRF/WRF Hydro models fails when choosing configuration `INTEL (ifort/icc): HSW/BDW`. This appears to be caused by an incomplete `#ARCH` specification in line 1832 of file `arch/configure.defaults`, which does not specify `ifort` as Fortran compiler. Script `arch/Config.pl` hands over this compiler description to WRF Hydro script `hydro/wrf_hydro_config`, which unsuccessfully scans the compiler specification for compiler names such as `gfortran` or `ifort`. WRF Hydro configuration fails quietly, and the WRF build will stop with missing file `hydro/Makefile.comm` when trying to build WRF Hydro.

The problem could be fixed by replacing line 1832 in `arch/configure.defaults` with something like
`
#ARCH    Linux x86_64 ppc64le i486 i586 i686, ifort compiler with icc #serial smpar dmpar dm+sm
`
I did not create a pull request as I wasn't sure which conventions are used for such descriptions.

**To Reproduce**
1. `git clone https://github.com/NCAR/wrf_hydro_nwm_public.git`
2. In WRF top directory: `rm -r hydro; cp -r ../wrf_hydro_nwm_public/trunk/NDHMS hydro`
3. Run `configure` script, choosing one of the `INTEL (ifort/icc): HSW/BDW` configurations, e.g., `dmpar`
4. Build WRF

The build will fall over with an error when it reaches the WRF Hydro sources, with `make` complaining about missing file `hydro/Makefile.comm`, which should have been created during the `configure` stage as explained above.

**Comment by jw500** [comment]
This commit has broken selection of Intel HSW/BDW build option. When HSW/BDW is selected, the initial Intel configuration option is selected instead. This appears to be caused by the comma in the comment line.
