### ISSUE TITLE
NOAHRES is not in restart files.

### ISSUE THREAD

**Issue by Enzoupi** [wrf-model/WRF#1390]
Possible inconsistency in output variables regarding the NOAH surface budget. Indeed, NOAHRES is only included in `history` when other members of the budget are included in both `history` and `restart` (except for flx1,2,3[,4]).

As a consequence, NOAHRES is 0 at every simulation restart. This makes it quite hard to track the surface energy balance. As it is only a supplementary 2D variable, adding it to the `restart` should only change unsignificantly in terms of storage.

I thought about sending the following PR (see below) but I thought I would better create and issue first to have the maintainers opinion on the matter.

_PS : For my own purposes, I will also add the flx1, flx2 and flx3 to both `history` and `restart` to be able to close the heat budget. However I am not sure if it is worth it to include it by default to the whole community._

**Possible PR content**
Add NOAHRES to restart files.

TYPE: bug fix

KEYWORDS: output ; noah ; surface ; heat fluxes

SOURCE: Enzo Le Bouëdec (Université Grenoble Alpes)

DESCRIPTION OF CHANGES:
Problem:
Possible inconsistency in output variables regarding the NOAH surface budget. Indeed, NOAHRES is only included in `history` when other members of the budget are included in both `history` and `restart`.

As a consequence, NOAHRES is 0 at every simulation restart. This makes it quite hard to track the surface energy balance. As it is only a supplementary 2D variable, adding it to the `restart` should only change unsignificantly in terms of storage.

Solution:
Add NOAHRES to restart files from the registry.

LIST OF MODIFIED FILES:
Registry/Registry.EM_COMMON

**Comment by Enzoupi** [comment]
Up ? If you believe it is erroneous or not important I can close the issue.

**Comment by weiwangncar** [comment]
@Enzoupi The reason that this field, NOAHRES, isn't in the restart file is because it is a diagnostic field, hence not required for model restart.

**Comment by Enzoupi** [comment]
Yes, I understand the philosophy. It is just that, in my case, I get NOAHRES to be zero every time I restart my simulation which is not super convenient as a default behavior to evaluate the energy balance.

Thanks for the answer @weiwangncar , closing the discussion not to overload with open issues :)
