### ISSUE TITLE
Nesting/non-uniform physics selection issue with state variable interp/feedback/forcing

### ISSUE THREAD

**Issue by sael9740** [wrf-model/WRF#1448]
**Describe the bug**
This is an issue that came up when I was working on the nesting implementation in AceCAST (independent GPU-WRF project). At @davegill's request I am just copying the contents of my email here:

> Hi Dave,
> 
> We just uncovered an issue in my nesting implementation that occurs with the following namelist options:
> 
> max_dom = 2
> feedback = 1
> …
> cu_physics = 11, 0
> 
> I noticed the following entries in the registry:
> 
> state    real  w_up             ikj     misc        1         -      rdu      "W_UP"                  "EFFECTIVE SUBGRID VELOCITY FROM KF"  "m s-1”
> package   mskfscheme     cu_physics==11              3       -             state:w0avg,w_up
> 
> I believe the issue is that my implementation of the RSL_LITE nesting code does not properly handle state variables like w_up if they are not allocated for both the parent and the child grids. My question is what is the intended behavior for a variable such as w_up when feedback = 1 but the nest doesn’t actually have that variable allocated? Does it just not update w_up on the parent grid? Or does it do something else?
> 
> Samm

Note - AceCAST is based off of WRF version 3.8.1

**Comment by dudhia** [comment]
Sounds like (without checking) a packaged variable issue with changing
physics on grids.
Can unpackage as a test by removing it from cu package list.

**Comment by sael9740** [comment]
Looks like that actually worked. So do I understand correctly that any state variable that is not specified in any package entry will always be allocated?

**Comment by weiwangncar** [comment]
@sael9740 That is correct. Did remove both variables from the package? I'm guessing the one that causes the problem is w_up?

**Comment by sael9740** [comment]
I only removed `w_up`. `w0avg` did not have any `usdf` specifications so it doesn't cause any issues with the nesting implementations.

**Comment by weiwangncar** [comment]
@sael9740 Thanks. As this array (w_up) is no longer used in MSKF, we will fix it by removing it from the code.
