### ISSUE TITLE
WENO, monotonic, and PD advection only done for rk_step=3 instead of rk_step=rk_ord

### ISSUE THREAD

**Issue by matzegoebel** [wrf-model/WRF#1461]
Positive-definite, monotonic, and WENO advection are only carried out in RK step 3, in the other RK steps the normal advection routines are called. See for example:
https://github.com/wrf-model/WRF/blob/fb60d61cc44e2a2e8b8311f0b79185724010d510/dyn_em/module_em.F#L420-L424
If the user selects `rk_ord=2`, then these routines are not called at all. Is that intentional, because they are not supported for `rk_ord=2`, or should we rather change all those if statements to `rk_step == rk_ord`? In the former case, we should add an error/warning for that combination.

**Comment by dudhia** [comment]
@Matthias Göbel ***@***.***> have you tried forcing it to
use rk_ord=2 to see if it works? This is not a much used option
and offline discussion with Bill Skamarock is that we could also
remove that option. Do you see a need for it?

**Comment by matzegoebel** [comment]
I see now that this issue has recently been fixed with commit 4412521401e6f57b3f29daaa47c04b03eb4f15ce.
I have never used rk_ord=2 and the whole documentation seems to focus on rk_ord=3. But I don't know if some people find that option useful...
