### ISSUE TITLE
missing metadata in auxiliary history files

### ISSUE THREAD

**Issue by tlspero** [wrf-model/WRF#1476]
The suite of global attributes is incomplete in the auxiliary history files. I have a proposed fix that would be inserted into share/output_wrf.F. I made the change in the version in WRFv4.2.2 (which did not change from WRFv4.2.1, for example), and it works.

Please let me know if you'd like the updated code.

**Comment by davegill** [comment]
@tlspero
Tanya,
Yes please provide a pull request. Use release-4.3.1 as the base branch that you are pushing to.

**Comment by davegill** [comment]
@tlspero 
Tanya,
If you would like to provide the source code, this might be handy for the rest of the community. Let me know if you would like some assistance with a pull request.

**Comment by tlspero** [comment]
@davegill --

Thank you for the reminder. Which branch should I submit to?

--Tanya

**Comment by davegill** [comment]
@tlspero 
Tanya,
Use the develop branch.
Thank you very much!

**Comment by tlspero** [comment]
I just need to check the mods against the current release (which I have not yet downloaded). I'll try to submit a PR later today.

**Comment by tlspero** [comment]
@davegill --

I could not get the code to attach to the PR, and hopefully I didn't botch it. Please reach out to me via email so I can send you a copy of the routine.

--Tanya

**Comment by davegill** [comment]
@tlspero 
Tanya
gill@ucar.edu
