### ISSUE TITLE
Error in the Irrigation module

### ISSUE THREAD

**Issue by rsegura24** [wrf-model/WRF#1482]
Hello,

I have noticed that the new irrigation module incorporated in the last WRF version 4.2 does not work as it is expected. The irrigation schedule is not properly defined. There is irrigation at all hours, not between the specified times ( irr_start_hour                      and  irr_start_hour + irr_num_hours) defined in the namelist.input. This is observed in the module phys/module_sf_irrigation.F in the IF conditional of the three subroutines (drip_irrigation, channel_irrigation and sprinkler_irrigation):

   xt24=mod(xtime,1440.)
   tloc=floor(gmt+xt24/60.)
   if(tloc.lt.0) tloc=tloc+24
   IF (((tloc.GE.irr_start_hour .AND. tloc.LT.24) .OR. ( tloc.GE.0 .AND. tloc.LT.end_hour) ) &
               .AND. ((julian_in.GE.irr_start_julianday  .AND.  julian_in.LT.367) .OR.       &
             (  julian_in.GE.0 .AND.   julian_in.LT.irr_end_julianday)) .AND. timing.EQ.0.  ) THEN
     IF(irr_ph.EQ.0) THEN
...

It should be:

   xt24=mod(xtime,1440.)
   tloc=floor(gmt+xt24/60.)
   if(tloc.lt.0) tloc=tloc+24
   IF (((tloc.GE.irr_start_hour .AND. tloc.LT.24) .AND. ( tloc.GE.0 .AND. tloc.LT.end_hour) ) &
               .AND. ((julian_in.GE.irr_start_julianday  .AND.  julian_in.LT.367) .AND.       &
             (  julian_in.GE.0 .AND.   julian_in.LT.irr_end_julianday)) .AND. timing.EQ.0.  ) THEN
     IF(irr_ph.EQ.0) THEN
...

Otherwise it will irrigate always. 

Greetings,

Ricard

**Comment by davegill** [comment]
@pedro-jm @cenlinhe @prasanthvkrishna @dudhia @weiwangncar 

Folks,
Would you take a look at this issue concerning irrigation.

**Comment by weiwangncar** [comment]
@arjanna Can you take a look at this? Thanks.

**Comment by davegill** [comment]
@weiwangncar 
Wei,
I knew that SOMEONE would know to whom we should direct this!

**Comment by cenlinhe** [comment]
Wei, thanks! You are right, this is not the same new irrigation we added to v4.3. :)

**Comment by arjanna** [comment]
Yes! sorry, here I am. It was a correction I did because otherwise, it was not working for a period across the julian_in=0.
I am fixing it.
