### ISSUE TITLE
WRF V4.2 can not run wrf.exe after modifying the SMOIS in wrfinput

### ISSUE THREAD

**Issue by genhou** [wrf-model/WRF#1500]
**Describe the bug**
WRF V4.2 crashes when I run wrf.exe after modifying the variable "SMOIS" in wrfinput_d03 in a 3-nested simulation in the rainy season in TP. 
The modification in “SMOIS” is very simple. I replace the  SMOIS with a weak spatial variability with SMOIS with a strong one. but all the changes are within a reasonable range. I once ran the same simulations using WRF V3.6 with the same modification in SMOIS successfully. I have no idea what makes failure.

The  namelist.input, rsl.error* and rsl.out are enclosed with this 
**To Reproduce**

**Expected behavior**
I hope someone(s) who are good at WRF could give me some solutions

**Screenshots**

**Attachments**
If applicable, attach supporting files: namelist.input, rsl.* files, etc.
[Namelist_rslerror_modified.zip](https://github.com/wrf-model/WRF/files/6396544/Namelist_rslerror_modified.zip)

**Additional context**
Add any other context about the problem here, such as:
   - This used to work with a previous version.
   - The documentation is different from the exhibited behavior.

**Comment by genhou** [comment]
[modifications.mat.zip](https://github.com/wrf-model/WRF/files/6396567/modifications.mat.zip)
The modification to the SMOIS is shown in the zip file. The  SMOIS0 is the unchanged one and the SMOIS1 is the modified one.

**Comment by dudhia** [comment]
This should be compiled with configure -d to give a better error message.

**Comment by dudhia** [comment]
Yes, clean -a and configure -d then run again.

**Comment by dudhia** [comment]
Send the result to the Forum. The Issues page is not for this type of
problem.
https://forum.mmm.ucar.edu/phpBB3/

**Comment by weiwangncar** [comment]
This problem should be posted on Forum.
