### ISSUE TITLE
WRFv4.1 ACM2 PBL scheme occasional NaN error

### ISSUE THREAD

**Issue by Novarizark** [wrf-model/WRF#1504]
**Describe the bug**
Occasional NaN error on random grids using ACM2 PBL scheme in all WRFv4.1 series after several hours to several days integration, both in hybrid and non-hybrid coordinates. WRFv3.9.1 integrates smoothly with same configurations.

**To Reproduce**
1. Compiler: Intel 20 and PGI 20
2. Use namelist options: bl_pbl_physics                      = 7,     7,    7,  7
3. Output is 
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     431
  RIBX never exceeds RIC, RIB(i,kte) =             NaN  THETAV(i,1) =    308.6539      MOL=  -2.797972      TCONV =             NaN  WST =             NaN  KMIX =            3  UST =   2.4491318E-02  TST =  -1.5744805E-02  U,V =  -0.3968337     -0.8117328      I,J=          23         136
-------------------------------------------

While I, J is quite random. We are sure it is not the terrain issue as all of our experiments (10 series and each series runs for 3 month) work fine in WRFv3.9.1

**Additional context**
- This used to work with a previous version.

**Comment by weiwangncar** [comment]
@Novarizark Please post this on the Forum: https://forum.mmm.ucar.edu/phpBB3/. Thanks. Also see PR#1433 which may have a fix for this problem. That fix will be released in 4.3 soon.

**Comment by Novarizark** [comment]
Thanks!
