### ISSUE TITLE
WRF-Chem4.0 or later Error running wrf.exe

### ISSUE THREAD

**Issue by Qinchuang2019** [wrf-model/WRF#1506]
Hello
There is a problem when I am running WRF-CHEM4.0 (https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=91&t=10319) later, Some of the solutions on the forums have been used but to no avail, anthropogenic source is generated by anthro_emiss.
Intel 19, NETCDF4.7.3 ,hdf5-1.10.5

setenv CC icc
setenv CXX icpc
setenv FC ifort
setenv F77 ifort
setenv F90 ifort
setenv CPPFLAGS "-qopenmp -DNDEBUG -DpgiFortran"
setenv CFLAGS "-qopenmp -g -O"
setenv FFLAGS "-qopenmp -O2 -mp -recursive"

**Comment by davegill** [comment]
@Qinchuang2019 
Please send this to the WRF Forum. This is the location for user support. 
forum.mmm.ucar.edu

On the forum site, include the following files:
1. configuration log (configure.wrf)
2. compilation log (output of ./compile em_real >& foo)
3. the run-time output files (all of the rsl.* file)

Include a description. "There is a problem when I am running WRF-CHEM4.0" is not sufficient to be helpful.
