### ISSUE TITLE
Error trying to read metadata WRF-Chem4.1

### ISSUE THREAD

**Issue by Qinchuang2019** [wrf-model/WRF#1509]
mediation_integrate: med_read_wrf_chem_emissions: Read emissions for time 2019-11-29_00:00:00
 mediation_integrate: med_read_wrf_chem_emissions: Open file wrfchemi_d01_2019-11-29_00:00:00
 NetCDF error: NetCDF: Attribute not found
 NetCDF error in ext_ncd_get_dom_ti.code CHAR, line          83  Element TITLE
 Error trying to read metadata
 Input data is acceptable to use: wrfchemi_d01_2019-11-29_00:00:00
mminlu = 'MODIFIED_IGBP_MODIS_NOAH'
 NetCDF error: NetCDF: Attribute not found
 NetCDF error in ext_ncd_get_dom_ti.code CHAR, line          83  Element TITLE

[file.zip](https://github.com/wrf-model/WRF/files/6445745/file.zip)

**Comment by weiwangncar** [comment]
@Qinchuang2019 Please use Forum to post this problem. Thanks.
