### ISSUE TITLE
MYNN in parent, LES in a nest: sometimes the sim does not run.

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#1514]
**Describe the bug**
This is an old issue we are having. When we try to use MYNN in one domain and LES in a nest sometimes the sim does not run. And the output provides no clue about what the problem could be. You pointed us a few years ago to the solution, copy the MYNN package definition in the registry and change to a nopbl package if the pbl is set to 0 in the namelist (LES). 

The problem of this fix is that it is particular for MYNN. So it never made it into the official WRF, and it is consuming the time of many users trying to run MYNN with LES.

My idea for a generic fix was to put the fix above for MYNN (the most used PBL) and then in check a mundo put an check to stop any sim with a PBL with a package + LES and print the solution. This will stop consuming user's time and points to the fix.

I briefly talked to Jimy about it and he indicated that you may know a generic fix.

How do you think we should move forward with this to avoid this issue?

Thanks in advance,
Pedro.

**To Reproduce**
1. Use compiler and version '....'
2. Use namelist options '....'
3. Output is '....'

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, attach supporting files: namelist.input, rsl.* files, etc.

**Additional context**
Add any other context about the problem here, such as:
   - This used to work with a previous version.
   - The documentation is different from the exhibited behavior.

**Comment by mefrediani** [comment]
Dave, there's a directory with the run files here: /glade/scratch/frediani/WRF-Fire/runs/cameron_peak_2020/no-fire/WRF/2dom
(Please note that the wrfinput and wrfbdy files are symlinks to subfolders)
Let me know if you have any questions. 

Thanks
Maria

**Comment by dudhia** [comment]
Just to update on what this fix is.
When we use a PBL scheme on any domain, any advected scalars in its package list need to be applied to all domains. This is so that LES nests don't allocate less memory. What is not clear yet is if all state variables in the package list also have to be allocated. For Franciano, the quick fix that seemed to work was to add the qke_adv scalar to the microphysics package.
