### ISSUE TITLE
There was an error unpacking the package of wrf-4.3.tar.gz，the wrf-4.3.zip is OK.

### ISSUE THREAD

**Issue by liuppei** [wrf-model/WRF#1515]
**Describe the bug**

**To Reproduce**
1. Use compiler and version '....'
2. Use namelist options '....'
3. Output is '....'

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, attach supporting files: namelist.input, rsl.* files, etc.

**Additional context**
Add any other context about the problem here, such as:
   - This used to work with a previous version.
   - The documentation is different from the exhibited behavior.

**Comment by mgduda** [comment]
The `.tar.gz` file is working fine for me. @liuppei can you try again? In any case, it's probably preferable to clone the repository rather than to download `.zip` or `.tar.gz` files.

**Comment by andrewsoong** [comment]
> @liuppei @andrewsoong
> 
> 1. I tried using the web interface, just clicking "Source code (tar.gz)":
> 
> <img alt="Screen Shot 2021-05-11 at 7 49 09 AM" width="695" src="https://user-images.githubusercontent.com/12666234/117826771-a9625b80-b22d-11eb-8d02-98dcecf6a226.png">
> 
> Then I got the source code unpacked:
> 
> ```
> $ gunzip WRF-4.3.tar.gz 
> 
> $ tar -xf WRF-4.3.tar
> 
> $ cd WRF-4.3
> 
> $ ls
> LICENSE.txt	README.md	chem		configure	dyn_nmm		hydro		phys		test		wrftladj
> Makefile	Registry	clean		doc		external	inc		run		tools
> README		arch		compile		dyn_em		frame		main		share		var
> ```
> 
> 1. I also manually pulled the file
> 
> ```
> $ wget https://github.com/wrf-model/WRF/archive/refs/tags/v4.3.tar.gz
> --2021-05-11 07:49:32--  https://github.com/wrf-model/WRF/archive/refs/tags/v4.3.tar.gz
> Resolving github.com (github.com)... 140.82.113.3
> Connecting to github.com (github.com)|140.82.113.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://codeload.github.com/wrf-model/WRF/tar.gz/refs/tags/v4.3 [following]
> --2021-05-11 07:49:32--  https://codeload.github.com/wrf-model/WRF/tar.gz/refs/tags/v4.3
> Resolving codeload.github.com (codeload.github.com)... 140.82.113.9
> Connecting to codeload.github.com (codeload.github.com)|140.82.113.9|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [application/x-gzip]
> Saving to: ‘v4.3.tar.gz’
> 
> v4.3.tar.gz                                  [                                                <=>                                     ] 140.22M  7.42MB/s    in 30s    
> 
> 2021-05-11 07:50:03 (4.71 MB/s) - ‘v4.3.tar.gz’ saved [147028447]
> 
> $ gunzip v4.3.tar.gz
> 
> $ tar -xf v4.3.tar
> 
> $ cd WRF-4.3
> 
> $ ls
> LICENSE.txt     README.md       chem            configure       dyn_nmm         hydro           phys            test            wrftladj
> Makefile        Registry        clean           doc             external        inc             run             tools
> README          arch            compile         dyn_em          frame           main            share           var 
> ```
> 
> 1. I repeated the download via the web and the wget command on a Linux machine (the 1. and 2. above were using a Mac). The Linux machine (a little raspberry pi) was able to pull the source code correctly.
> 
> Would you fill in the above issue message to give us more information? We are unable to replicate the error.

Sorry for late response. I can unpack it correctly, because the tar.gz file was downloaded partly.
Another qustion is how to get official supported wrf-hydro v5.2.0? The wrfhydro's github obtains only pre-release wrf-hydro v5.2.0. Thanks!

**Comment by liuppei** [comment]
> @liuppei @andrewsoong
> 
> 1. I tried using the web interface, just clicking "Source code (tar.gz)":
> 
> <img alt="Screen Shot 2021-05-11 at 7 49 09 AM" width="695" src="https://user-images.githubusercontent.com/12666234/117826771-a9625b80-b22d-11eb-8d02-98dcecf6a226.png">
> 
> Then I got the source code unpacked:
> 
> ```
> $ gunzip WRF-4.3.tar.gz 
> 
> $ tar -xf WRF-4.3.tar
> 
> $ cd WRF-4.3
> 
> $ ls
> LICENSE.txt	README.md	chem		configure	dyn_nmm		hydro		phys		test		wrftladj
> Makefile	Registry	clean		doc		external	inc		run		tools
> README		arch		compile		dyn_em		frame		main		share		var
> ```
> 
> 1. I also manually pulled the file
> 
> ```
> $ wget https://github.com/wrf-model/WRF/archive/refs/tags/v4.3.tar.gz
> --2021-05-11 07:49:32--  https://github.com/wrf-model/WRF/archive/refs/tags/v4.3.tar.gz
> Resolving github.com (github.com)... 140.82.113.3
> Connecting to github.com (github.com)|140.82.113.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://codeload.github.com/wrf-model/WRF/tar.gz/refs/tags/v4.3 [following]
> --2021-05-11 07:49:32--  https://codeload.github.com/wrf-model/WRF/tar.gz/refs/tags/v4.3
> Resolving codeload.github.com (codeload.github.com)... 140.82.113.9
> Connecting to codeload.github.com (codeload.github.com)|140.82.113.9|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [application/x-gzip]
> Saving to: ‘v4.3.tar.gz’
> 
> v4.3.tar.gz                                  [                                                <=>                                     ] 140.22M  7.42MB/s    in 30s    
> 
> 2021-05-11 07:50:03 (4.71 MB/s) - ‘v4.3.tar.gz’ saved [147028447]
> 
> $ gunzip v4.3.tar.gz
> 
> $ tar -xf v4.3.tar
> 
> $ cd WRF-4.3
> 
> $ ls
> LICENSE.txt     README.md       chem            configure       dyn_nmm         hydro           phys            test            wrftladj
> Makefile        Registry        clean           doc             external        inc             run             tools
> README          arch            compile         dyn_em          frame           main            share           var 
> ```
> 
> 1. I repeated the download via the web and the wget command on a Linux machine (the 1. and 2. above were using a Mac). The Linux machine (a little raspberry pi) was able to pull the source code correctly.
> 
> Would you fill in the above issue message to give us more information? We are unable to replicate the error.

I have re-downloaded .tar.gz, It is OK.Maybe it's my Internet problem,embarrassed.

**Comment by davegill** [comment]
@andrewsoong @liuppei 
I am going to close this issue. It looks like both of these problems with v4.3 were perhaps network related.

**Comment by davegill** [comment]
@andrewsoong @rcabal
> Another question is how to get official supported wrf-hydro v5.2.0? The wrfhydro's github obtains only pre-release wrf-hydro v5.2.0. Thanks!

Ryan,
There is about to be a question about WRF Hydro access.

Andrew,
Take a look at https://ral.ucar.edu/projects/wrf_hydro/overview
There is an email for support: wrfhydro@ucar.edu
Go ahead and use the email resource instead of this platform for support questions.
