### ISSUE TITLE
Dependance error for da_radiance in WRFDA

### ISSUE THREAD

**Issue by honnorat** [wrf-model/WRF#1527]
When compiling WRFDA with `export J="-j 1"` environment variable set to make sure that all files are compiled in order, `da_radiance.o` compilation fails because `mod_clddet_geoir.mod` has not been compiled yet.

```
if [ -n "" ] ; then echo COMPILING da_radiance.f90 WITHOUT OMP ; fi ; \
    mpif90  -c -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -fdefault-real-8 -I../external/crtm_2.3.0/libsrc   -I/opt/wrf/gcc8/usr/include -I/opt/wrf/gcc8/usr/include da_radiance.f ; \
fi
da_radiance.f:81:7:

    use mod_clddet_geoir, only: qc_SDob,qc_RTCT,qc_rtmt,qc_cwvt,qc_tit, &
       1
Fatal Error: Can't open module file ‘mod_clddet_geoir.mod’ for reading at (1): Aucun fichier ou dossier de ce type
compilation terminated.
make[1]: [da_radiance.o] Erreur 1 (ignorée)
```

**To Reproduce**
1. `$ gcc --version`
`gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)`
2. `$ git clone -b release-v4.3.1 https://github.com/wrf-model/WRF.git WRFDA`
3. `$ export J="-j 1"`
4. `$ cd WRFDA;  ./configure wrfda ; ./compile all_wrfvar`

**Expected behavior**
Module `mod_clddet_geoir.mod` should be compiled before `da_radiance.o`.

**Comment by liujake** [comment]
Thanks for fixing this. Your fix is merged.
