### ISSUE TITLE
IO time in WRF v4.1 much longer than that in WRF v4.0 and WRF v4.2

### ISSUE THREAD

**Issue by J-shel** [wrf-model/WRF#1537]
Hi,

I run the same case using WRF v4.1, WRF v4.0 and WRF v4.2, and I just found that the run time was much longer when using WRF v4.1 than using WRF v4.0 and WRF v4.2. According to the details in the log files, it seems the compute time were close among WRF v4.1, WRF v4.0 and WRF v4.2, and the IO time in WRF v4.1 was much longer than that in WRFv4.0 and WRFv4.2. The IO format I used is Pnetcdf.

Could anyone tell me why? Thank you!

**Comment by davegill** [comment]
please post this on the WRF forum https://forum.mmm.ucar.edu/phpBB3/
The answer is likely that we moved to netcdf4 output by default, but the cost was a bit much.
