### ISSUE TITLE
 WRF 4.3: I/O syntax error, unit 19, file VEGPARM.TBL

### ISSUE THREAD

**Issue by liesss** [wrf-model/WRF#1546]
I sucessfully ran wrf.exe version 4.1.2 with Noah LSM ( sf_surface_physics = 2,) and NLCD input data. However, although in version 4.3 (also in preliminary version 4.3.1 from 7/30/2021) all WPS routines and real.exe work, for wrf.exe I get the error

INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
Skipping over LUTYPE = MODIFIED_IGBP_MODIS_NOAH
LANDUSE TYPE = NLCD40 FOUND 40 CATEGORIES
forrtl: severe (59): list-directed I/O syntax error, unit 19, file </absolute_path_to_wrf_run_dir>/VEGPARM.TBL

I'm using ifort (IFORT) 19.0.1.144 20181018 on CentOS Linux release 7.9.2009 kernel 3.10.0-1160.31.1.el7.x86_64

I'm reposting here to bump. The other post is at https://forum.wrfforum.com/viewtopic.php?f=43&t=13701 . Thanks in advance for any help!

**Comment by dudhia** [comment]
#1536 was added to 4.3.1 in August. Check if this resolves the issue.

**Comment by liesss** [comment]
Yes, this resolves the issue, thank you.
