### ISSUE TITLE
An error occurred while running wrf.exe ‘free(): invalid pointer’

### ISSUE THREAD

**Issue by dyw770** [wrf-model/WRF#1558]
Hi, dear developer, I try to compile WRF and WPS according to the official documents and run a case provided by the official. I successfully compiled WRF and WPS, but a strange error occurred when I ran wrf.exe at the last step of the case. I had this problem on both computers. I don't know how to solve this mistake. I hope I can get your help.
![image](https://user-images.githubusercontent.com/26217571/133793641-d81fb40c-e3ad-43dc-8268-33bdcf567cc5.png)

**Comment by weiwangncar** [comment]
@dyw770 Please report the problem on the Forum: https://forum.mmm.ucar.edu/. Thanks.
