### ISSUE TITLE
How to calculate grid%mu with a corrected surface pressure?

### ISSUE THREAD

**Issue by good-goodboy** [wrf-model/WRF#1582]
I'm working on online WRF assimilation. I'm currently assimilating surface pressure and I had calculated the correction of surface pressure.

Do you know how to use the correction of surface pressure to modify the perturbation dry air mass in column ( grid%mu)?

Thanks a lot！

**Comment by davegill** [comment]
This is more of a general question that other users would benefit from knowing. This github issues page for WRF is more related to possible bugs or shortcomings in the WRF code.

Would you please repost this EXACT question (just cut and paste) to the WRF Forum. Please add in what version of WRF you are using, and specifically if you are using the hybrid vertical coordinate. That impacts the definition of mu.

Go to https://forum.mmm.ucar.edu

Your first time signing in, there is a delay to keep spammers out.

Once you are logged in with your user ID and password, under `WRF SUPPORT` there is a section called `WRF Model`. This topic that you have seems appropriate for that area. 

Also, your title above is detailed and accurate - use that for your WRF Forum post question title.

Yo move things along more quickly, feel free in the text of the post to mention "Dave Gill asked to have this question directly assigned to him."

I am closing this issue.
