### ISSUE TITLE
Thresholds of nprocx and nprocy

### ISSUE THREAD

**Issue by bomarty** [wrf-model/WRF#1627]
Hello everyone,
When I run wrf.exe (Version 4.3.2) using parallel computing based on MPI,  I get the following error:

   For domain            1 , the domain size is too small for this many processors, or the decomposition aspect ratio is poor.
   Minimum decomposed computational patch size, either x-dir or y-dir, is 10 grid cells.
  e_we =   142, nproc_x =    8, with cell width in x-direction =   17
  e_sn =   133, nproc_y =   16, with cell width in y-direction =    8
  --- ERROR: Reduce the MPI rank count, or redistribute the tasks.
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    2572
NOTE:       1 namelist settings are wrong. Please check and reset these options
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

So I reduce the number of processes from 128 to 64 which did solve the problem. However, it seems there is no problem when I use the same grid setting using WRF version 3.8 and I didn't find any explaination in users' guide.
My problem is whether the nproc_x and nproc_y have thresholds? 
Thank you.

**Comment by davegill** [comment]
We now enforce a minimum grid size. Each horizontal dimension of the decomposed domain must be greater than or equal to 10. Yes, there is a threshold, and yes that value is 10.

To disable this, edit the file share/module_check_a_mundo.F, look for the string in the error printout ("Minimum decomposed computational patch size"). Just below is an incrementing flag (oops = oops + 1) that should be commented out.

**Comment by bomarty** [comment]
Thank you so much!  I have found the relevant codes. 
I'm wondering do we enforce a minimum grid size for preventing wasting computing resources only or there are other reasons?

**Comment by honnorat** [comment]
When the decomposed domains are too small, you'll devote most of your computing resources to MPI tasks exchanging messages, to the detriment of actual computing.
