### ISSUE TITLE
Potential issue with rl_up correction in WRFv4.3.2 BEP/BEM code

### ISSUE THREAD

**Issue by cgiannaros** [wrf-model/WRF#1643]
Dear all,

I perform some ultra-high resolution simulations during a heat-wave period with WRF coupled to BEP/BEM urban canopy model using the NOAH_MP land surface model. Attached you can find the namelist.input I use. Initially, I used version 4.3, but recently I applied also version 4.3.2, as it contains the following fix: 

"An error in longwave radiation calculation in the BEP-BEM urban module is fixed. This error affects the calculation of TSK, which now is correctly calculated."

Indeed, the use of initial version led to very high TSK values (~ 330 K in night and ~ 347 in day), which were not correspond well to satellite LST observations. The application of the updated/corrected version, lead to better simulation of TSK, but to worse results concerning near surface atmospheric variables and especially for 2m air temperature. 

In the provided figures, the first one corresponds to version 4.3 simulations, while the second corresponds to version 4.3.2 simulation for the first six days (25/07 00:00 to 30/07 00:00). A significant drop of the simulated 2m air temperature by 2-3 degrees Celsius is evident during the night with the updated/corrected version. During the day the results are the same. Similar outcomes can be derived by comparing the third and fourth figure for 10-m wind speed.

Maybe the longwave radiation calculation in BEP/BEM corrects the TSK calculation, but affects negatively the computation of 2m air temperature and other near surface variables? 

Any ideas on how to investigate and resolve this issue would be very much appreciated.

Best regards, 

Christos

![August_T_all_FINAL_ALL_ERA5_v2](https://user-images.githubusercontent.com/42891907/149761056-4b17febe-4d24-4145-bc7c-a8062f87fef6.png)
![August_T_all_FINAL_ALL_ERA5_v3](https://user-images.githubusercontent.com/42891907/149761060-e67e2518-24b9-46ff-bd6f-4fc2ae0d067e.png)
![August_WS_all_FINAL_ALL_ERA5_v2](https://user-images.githubusercontent.com/42891907/149761213-83dcaf55-014d-4a84-9738-bdbc81178be3.png)
![August_WS_all_FINAL_ALL_ERA5_v3](https://user-images.githubusercontent.com/42891907/149761219-3785a6de-9bd3-4610-9444-57579b3ba7b6.png)

**Comment by weiwangncar** [comment]
@cenlinhe @andreazonato Any comments?

**Comment by cenlinhe** [comment]
@andreazonato may have more thoughts on this, but the first 6 day curve looks like a normal spin-up type of results to me where you see the worse result for v4.3.2. But after 6 days, everything seems fine. Did you spin up the model before your start date (July 25th)?

**Comment by cgiannaros** [comment]
@cenlinhe Sorry, I forgot to mention that my runs cover 3 days with a 12h spin-up period. So, the first run started on 24/07 12:00 UTC and it ended on 28/07 00:000 UTC. The next run started on 27/12 12:00 UTC and it ended on 31/07 00:00 UTC, etc. Please, ignore the curves from 31/07 00:00 and then. These runs are completely identical. The differences between the two versions (v4.3 and v4.3.2) are found only in the first 6 days (25/07 00:00 to 31/07 00:00).

**Comment by cgiannaros** [comment]
Dear all,

Please find below some updated figures for a better visualization of the differences between the runs with versions v4.3 and v4.3.2 concerning 2m air temperature and humidity, and 10m wind speed and direction. 

![August_T_ERA5_diffs](https://user-images.githubusercontent.com/42891907/149885362-7a96764b-3b86-491d-be0e-33caa053cdba.png)
![August_RH_ERA5_diffs](https://user-images.githubusercontent.com/42891907/149885445-f89013b8-8637-49cb-8fbc-234271ee5931.png)
![August_WS_ERA5_diffs](https://user-images.githubusercontent.com/42891907/149885458-c4b6b8b9-bb28-40b4-9b0d-2755f57da3b2.png)
![August_WDIR_ERA5_diffs](https://user-images.githubusercontent.com/42891907/149885469-ce096f28-8de1-447d-8eed-a427edc87232.png)

**Comment by andreazonato** [comment]
@cgiannaros , thank you for reporting this issue.

Actually, model 4.3 was wrong, and I fixed the problem by returning to the calculation present in the previous versions.
T2 depends directly on TSK since T2 is a weighted average between TSK and Temperature in the first level. 

So there is no error in this, and I would not rely too much in the comparison with observations, which can be counterproductive.

Thank you again. 
Andrea
