### ISSUE TITLE
Fail to compile in a Cray Environment

### ISSUE THREAD

**Issue by davidedelvento** [wrf-model/WRF#1658]
**Describe the bug**
WRF v4.3 Fail to compile on a Cray environment

**To Reproduce**
1. Cray Fortran : Version 12.0.3
2. Compile Option 46
3. Output is
```
ftn-855 crayftn: ERROR MODULE_MP_NSSL_2MOM, File = module_mp_nssl_2mom.f90, Line = 154, Column = 8
  The compiler has detected errors in module "MODULE_MP_NSSL_2MOM".  No module information file will be created for this module.

          open(15,file='namelist.output',status='old',action='readwrite', access='append',form='formatted')
                                                                                 ^                          
ftn-24 crayftn: ERROR NSSL_2MOM_INIT, File = module_mp_nssl_2mom.f90, Line = 1173, Column = 82
  The character constant "APPEND  ", for the I/O control information list item ACCESS, is not allowed.
```

which eventually prevents the binary from being created

**Additional context**
My understanding is that the statement `open(15,file='namelist.output',status='old',action='readwrite', access='append',form='formatted')` is not standard conformant and deprecated. The intended behavior can be achieved by
`open(15,file='namelist.output',status='old',action='readwrite', position='append',form='formatted')` which instead compiles fine.

**Comment by dudhia** [comment]
It may have been corrected. I see position in the current develop branch.

**Comment by dudhia** [comment]
#1577 fixed it a couple of months ago

**Comment by davegill** [comment]
@davidedelvento 
Davide
Thanks - the Cray folks sent us this also. The next release is out SOON!

**Comment by davidedelvento** [comment]
Perfect, thanks!

**Comment by davegill** [comment]
@davidedelvento 
PR #1577 "Small physics syntax errors" SHA1 7c6fd575b7a8fe5715b

Here are the first few lines:
```
    Small physics syntax errors (#1577)

    TYPE: bug fix

    KEYWORDS: HPE, CCE, syntax

    SOURCE: Tricia Balle (HPE)
   
    DESCRIPTION OF CHANGES:
    Problem:
    There were three types of syntax errors that were uncovered by the HPE CCE compiler.
    1. Open statement used `action="append"`.
    2. Multiple unary operators next to each other `*+`
    3. Multiple unary operators next to each other `*-1`.
   
    Solution:
    1. The correct usage is `position="append"`.
    2. The developer agrees with the new modification to `GS3*+SASR1` was the original intent.
    3. Typically, `*(-1)` is intended, and this is the case.
```

**Comment by davidedelvento** [comment]
Great. For you and others who may land on this issue, and in case you haven't tested this yourself yet, I confirm that the HEAD of current main branch, namely aa9f3b61ae9b0fc08d11fbeccd201b90404369e1 compiles correctly in the Derecho environment.
