### ISSUE TITLE
Problem building WRF v4.4 with dm+sm and Cray compiler

### ISSUE THREAD

**Issue by davidedelvento** [wrf-model/WRF#1659]
**Describe the bug**
Can't compile WRF v4.4 (from github commit 6e1c57a22d856102277ec16ed369d0cc719a1cb5) in dm+sm

**To Reproduce**
1. Cray Fortran : Version 12.0.3
2. configure and select Compile option 47
3. Tested on Derecho's container environment
4. `compile em_real`

**Expected behavior**
Binaries produced

**Screenshots**
The first error is the following:

```
MODULE MODULE_SF_NOAHMPLSM
       ^
ftn-855 crayftn: ERROR MODULE_SF_NOAHMPLSM, File = module_sf_noahmplsm.f90, Line = 21, Column = 8
  The compiler has detected errors in module "MODULE_SF_NOAHMPLSM".  No module information file will be created for this module.

    TOP_MOIST     = TOP_MOIST + (SMC(IZ)*-1.0*ZSOIL(IZ))
                                         ^
ftn-1725 crayftn: ERROR COMPUTE_VIC_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 7988, Column = 42
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

    TOP_MAX_MOIST = TOP_MAX_MOIST + (parameters%SMCMAX(IZ)*-1.0*ZSOIL(IZ))
                                                           ^
ftn-1725 crayftn: ERROR COMPUTE_VIC_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 7989, Column = 60
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

          SM     = SM + (SMC(IZ) - parameters%SMCREF(IZ) )*-1.0*ZSOIL(IZ)
                                                           ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8069, Column = 60
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

          WM     = WM + (parameters%SMCREF(IZ)*-1.0*ZSOIL(IZ))
                                               ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8070, Column = 48
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

          WM     = WM + (SMC(IZ)*-1.0*ZSOIL(IZ))
                                 ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8072, Column = 34
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

       WM_MAX = WM_MAX + (parameters%SMCREF(IZ)*-1.0*ZSOIL(IZ))
                                                ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8074, Column = 49
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

       SM_MAX = SM_MAX + (parameters%SMCMAX(IZ) - parameters%SMCREF(IZ))*-1.0*ZSOIL(IZ)
                                                                         ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8075, Column = 74
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

    TOP_MOIST     = TOP_MOIST + (SMC(IZ)*-1.0*ZSOIL(IZ))
                                         ^
ftn-1725 crayftn: ERROR DYNAMIC_VIC, File = module_sf_noahmplsm.f90, Line = 8172, Column = 42
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".
```

**Additional context**
Given how trivial the error looks, and given a number of other warnings that happen (a couple quoted below), I suspect the `configure` script making something wrong for option 47 rather than a problem in WRF itself. Moreover, the version `dm` (option 46) compiled fine (however that was the HEAD of the trunk as reported in the other ticket, whereas this is v4.4)

```
Fortran compiler for the model source code:
which FC
which: invalid option -- 'h'
which: invalid option -- 'n'
which: invalid option -- 'o'
which: invalid option -- 'o'
which: invalid option -- 'm'
which: invalid option -- 'p'
```

```
ftn-714 crayftn: WARNING in command line
  The "noomp" command has been overridden by the "omp" command.
```

**Comment by weiwangncar** [comment]
@cenlinhe Please see this post, and it points to multiple places in module_sf_noahmplsm.F that may require change.

**Comment by cenlinhe** [comment]
I will put a parenthesis () to the "-1.0" in noahmplsm, but this may also be an issue with the Cray compiler (?), since this issue is not there for all the current Cheyenne compilers.

**Comment by weiwangncar** [comment]
@cenlinhe We don't win by fighting the compilers...

**Comment by cenlinhe** [comment]
OK, agreed. I will make the changes soon. Maybe after the v4.4 branch cut-off?

**Comment by davidedelvento** [comment]
I will bring the issue to Cray, but as @weiwangncar said....

@cenlinhe It will be nice if the change gets into v4.4 so users of Derecho will not be stuck with this problem.

If you would like to test the issue yourself, and you have an account on Cheyenne see https://arc.ucar.edu/knowledge_base/80511266

**Comment by weiwangncar** [comment]
@cenlinhe Just sent you the info.

**Comment by cenlinhe** [comment]
@davidedelvento  @weiwangncar  Got it. Thanks

**Comment by davegill** [comment]
@davidedelvento @cenlinhe @weiwangncar 
Cenlin,
What branch for NoahMP, and I will make a PR? 
```
module_sf_noahmplsm.F:    TOP_MOIST     = TOP_MOIST + (SMC(IZ)*-1.0*ZSOIL(IZ)) ! m 
module_sf_noahmplsm.F:    TOP_MAX_MOIST = TOP_MAX_MOIST + (parameters%SMCMAX(IZ)*-1.0*ZSOIL(IZ)) ! m   
module_sf_noahmplsm.F:          SM     = SM + (SMC(IZ) - parameters%SMCREF(IZ) )*-1.0*ZSOIL(IZ) !m
module_sf_noahmplsm.F:          WM     = WM + (parameters%SMCREF(IZ)*-1.0*ZSOIL(IZ))            !m  
module_sf_noahmplsm.F:          WM     = WM + (SMC(IZ)*-1.0*ZSOIL(IZ))
module_sf_noahmplsm.F:       WM_MAX = WM_MAX + (parameters%SMCREF(IZ)*-1.0*ZSOIL(IZ))
module_sf_noahmplsm.F:       SM_MAX = SM_MAX + (parameters%SMCMAX(IZ) - parameters%SMCREF(IZ))*-1.0*ZSOIL(IZ)
module_sf_noahmplsm.F:    TOP_MOIST     = TOP_MOIST + (SMC(IZ)*-1.0*ZSOIL(IZ))                                   ! actual moisture in top layers, [m] 
module_sf_noahmplsm.F:    TOP_MAX_MOIST = TOP_MAX_MOIST + (parameters%SMCMAX(IZ)*-1.0*ZSOIL(IZ))                 ! maximum moisture in top layers, [m]  
module_sf_noahmplsm.F:      SMCAVL = (SH2O(1)-parameters%SMCWLT(1))*-1.0*ZSOIL(1)              ! current soil water (m) 
module_sf_noahmplsm.F:      SMCLIM = (parameters%SMCREF(1)-parameters%SMCWLT(1))*-1.0*ZSOIL(1) ! available water (m) 
```

**Comment by cenlinhe** [comment]
@davegill I have not updated the code to fix this issue yet. Do you want to do it or you want to wait for me to do it and I will let you know which NoahMP branch should be connected by WRF once I update the NoahMP github repo?

**Comment by davegill** [comment]
@cenlinhe 
Yes, let me propose a change to the NoahMP repo. Which branch should I use?

**Comment by cenlinhe** [comment]
@davegill Please use the develop branch. Thanks!

**Comment by davegill** [comment]
@cenlinhe @weiwangncar @davidedelvento 
https://github.com/NCAR/noahmp/pull/30

**Comment by davegill** [comment]
@weiwangncar @cenlinhe 
Now we have an excellent learning opportunity! We need to update the SHA1 that we pull from NoahMP. After Cenlin updates the code, we will need to add a mod to the release-v4.4 branch to change the NoahMP version.

@davidedelvento 
Thanks mucho!

**Comment by cenlinhe** [comment]
@davegill I have merged the updates from NoahMP "develop" branch to the NoahMP "release-v4.4-WRF" branch. You can update the SHA from WRF side if you want.

**Comment by davidedelvento** [comment]
The issue I initially reported is fixed, thank you.

However the Cray compiler still complains about this configuration and refuses to compile it. Here is a quick summary of the reported problems (hope I captured everything....)

```
ftn-1725 crayftn: ERROR COMPUTE_VIC_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 7988, Column = 42 
ftn-1725 crayftn: ERROR COMPUTE_VIC_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 7989, Column = 60 
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8069, Column = 60 
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8070, Column = 48 
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8072, Column = 34 
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8074, Column = 49 
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8075, Column = 74 
ftn-1725 crayftn: ERROR DYNAMIC_VIC, File = module_sf_noahmplsm.f90, Line = 8172, Column = 42 
ftn-1725 crayftn: ERROR DYNAMIC_VIC, File = module_sf_noahmplsm.f90, Line = 8173, Column = 60 
ftn-1725 crayftn: ERROR SMITH_PARLANGE_INFIL, File = module_sf_noahmplsm.f90, Line = 8471, Column = 89 
ftn-1725 crayftn: ERROR SMITH_PARLANGE_INFIL, File = module_sf_noahmplsm.f90, Line = 8488, Column = 84 
ftn-1725 crayftn: ERROR GREEN_AMPT_INFIL, File = module_sf_noahmplsm.f90, Line = 8549, Column = 88 
ftn-1725 crayftn: ERROR GREEN_AMPT_INFIL, File = module_sf_noahmplsm.f90, Line = 8561, Column = 83 
ftn-1725 crayftn: ERROR TRIGGER_IRRIGATION, File = module_sf_noahmplsm.f90, Line = 9262, Column = 47 
ftn-1725 crayftn: ERROR TRIGGER_IRRIGATION, File = module_sf_noahmplsm.f90, Line = 9263, Column = 60 
ftn-855 crayftn: ERROR MODULE_FIREBRAND_SPOTTING, File = module_firebrand_spotting.f90, Line = 10, Column = 8 
ftn-319 crayftn: ERROR GET_FUEL_CAT, File = module_firebrand_spotting.f90, Line = 567, Column = 28 
ftn-855 crayftn: ERROR MODULE_SF_NOAHMPDRV, File = module_sf_noahmpdrv.f90, Line = 1, Column = 8 
ftn-894 crayftn: ERROR NOAHMPLSM, File = module_sf_noahmpdrv.f90, Line = 68, Column = 9 
ftn-894 crayftn: ERROR TRANSFER_MP_PARAMETERS, File = module_sf_noahmpdrv.f90, Line = 1393, Column = 7 
ftn-894 crayftn: ERROR PEDOTRANSFER_SR2006, File = module_sf_noahmpdrv.f90, Line = 1667, Column = 7 
ftn-855 crayftn: ERROR MODULE_SURFACE_DRIVER, File = module_surface_driver.f90, Line = 3, Column = 8 
ftn-894 crayftn: ERROR SURFACE_DRIVER, File = module_surface_driver.f90, Line = 323, Column = 8 
ftn-855 crayftn: ERROR MODULE_PHYSICS_INIT, File = module_physics_init.f90, Line = 11, Column = 8 
ftn-894 crayftn: ERROR BL_INIT, File = module_physics_init.f90, Line = 2431, Column = 8 
ftn-855 crayftn: ERROR MODULE_FIREBRAND_SPOTTING, File = ../phys/module_firebrand_spotting.f90, Line = 10, Column = 8 
ftn-319 crayftn: ERROR GET_FUEL_CAT, File = ../phys/module_firebrand_spotting.f90, Line = 567, Column = 28 
ftn-855 crayftn: ERROR MODULE_SURFACE_DRIVER, File = ../phys/module_surface_driver.f90, Line = 3, Column = 8 
ftn-894 crayftn: ERROR SURFACE_DRIVER, File = ../phys/module_surface_driver.f90, Line = 323, Column = 8 
ftn-855 crayftn: ERROR MODULE_FIRST_RK_STEP_PART1, File = module_first_rk_step_part1.f90, Line = 4, Column = 8 
ftn-894 crayftn: ERROR FIRST_RK_STEP_PART1, File = module_first_rk_step_part1.f90, Line = 42, Column = 9 
ftn-894 crayftn: ERROR SOLVE_EM, File = solve_em.f90, Line = 87, Column = 8 
ftn-855 crayftn: ERROR MODULE_PHYSICS_INIT, File = ../phys/module_physics_init.f90, Line = 11, Column = 8 
ftn-894 crayftn: ERROR BL_INIT, File = ../phys/module_physics_init.f90, Line = 2431, Column = 8 
ftn-894 crayftn: ERROR START_DOMAIN_EM, File = start_em.f90, Line = 36, Column = 8 
ftn-894 crayftn: ERROR START_DOMAIN_EM, File = start_em.f90, Line = 37, Column = 8 
ftn-894 crayftn: ERROR START_DOMAIN_EM, File = start_em.f90, Line = 40, Column = 8 
```

Let me know how do you prefer to proceed: I can create separate github issue for each problem individually, we can use this one, or we can work outside of github directly on the Derecho environment? Let me know what works best for you.

If you want to see the whole compilation log, you may find it in GLADE at  `/glade/scratch/ddvento/ch/WRF-Derecho/WRF-github-v4.4-hybrid-merge/compile.log`

**Comment by weiwangncar** [comment]
@cenlinhe In case you are not notified...

**Comment by cenlinhe** [comment]
Just took a look at it and not sure why such error occurred in NoahMP code. Also, it seems that it also occurred for other modules above.

**Comment by davegill** [comment]
@davidedelvento 
Any idea what is happening at those lines and locations? Are they tabs or windows ^M characters?

**Comment by davidedelvento** [comment]
I may be wrong, but from my cursory look, it seems the same problem as before, which (probably) cascaded into further source codes down the road due to the WRF building system not bailing out at first failure.

**Comment by davegill** [comment]
@davidedelvento @weiwangncar @dudhia @cenlinhe 
Folks,
This is OLDER code. We have two mods that went in to fix the `* -1.0` issue. In Davide's directory, the NoahMP repo is at PR number 29, and it should be at about 34.

Davide,
Would you wipe this one and then
```
git clone https://github.com/wrf-model/WRF WRF-derecho2
cd WRF-derecho2
git checkout release-v4.4
./configure -d
./compile em_real -j 4 >& foo ; tail -20 foo
```

**Comment by davidedelvento** [comment]
@davegill thanks for taking a look. I thought I had already done that, but in any case I am redoing it right now, barring minor differences due to me using the Cray environment and using 6 threads rather than 4 to speed it up a bit more (the Cray environment is quite slow). And naming the file `davide_compile.log`  rather than `foo`.

If you want to take a peek while it is running, it's in a new directory with the same name as before `/glade/scratch/ddvento/ch/WRF-Derecho/WRF-github-v4.4-hybrid-merge/` (I moved the old one to `/glade/scratch/ddvento/ch/WRF-Derecho/trash/WRF-github-v4.4-hybrid-merge/`)

**Comment by davidedelvento** [comment]
Mmmm, that failed too, in addition to the same stuff as before I also noticed a bunch of ESMF-related failures which did not happen before. Compare `/glade/scratch/ddvento/ch/WRF-Derecho/WRF-github-v4.4-hybrid-merge/davide_compile.log` with `/glade/scratch/ddvento/ch/WRF-Derecho/trash/WRF-github-v4.4-hybrid-merge/compile.log`

Perhaps it is better if I wait for your to settle on a more stable release candidate before attempting further tests?

**Comment by davidedelvento** [comment]
Folks, we had an internal conversion, which involved also a few representatives from the Fortran Standard Committee.

In a nutshell, Intel and GNU compile this code because by default they accept non-standard-compliant code, however that is poor practice, and we can not request Cray to loosen their acceptance. Even with Intel and GNU, we recommend that you (or really any code developer) enforce the standard compliance enforcement with the `-stand` and `-std` command line argument as we already describe at https://arc.ucar.edu/knowledge_base/72581452

With those, you should be able to reproduce the problem with any compiler in any machine, so that should make it easier for you to fix. Thanks for your patience and understanding, please let me know if there is anything that I can do to facilitate this process in preparation of Derecho.

**Comment by dudhia** [comment]
We definitely want to make sure we have this level of compliance. We should
add this
compilation option to our regular testing,
Jimy

**Comment by davidedelvento** [comment]
@weiwangncar @cenlinhe has there been any progress on this? Is there anything I can do to help?

**Comment by weiwangncar** [comment]
@davidedelvento Not yet. We haven't had time to look into this more. I just took a look at your two compile log files, and it looks like either our configure file has changed and/or the Cray environment has. Can you tell us if the configure.wrf has changed between the two compiles? If you have any suggestion for change, we are happy to hear. I may have some time to look into this more in two weeks.

**Comment by davidedelvento** [comment]
Thanks @weiwangncar for the quick response. What I did in my tests was always taking a "vanilla" configure coming out of a specific version of WRF (I believe it was the pre-release tag of the time I ran it) and selecting the relevant option from the menu. I did not touch it otherwise.

The Cray environment, I suspect, has changed. Let me ping @siddsghosh who knows more details about that, but what are you seeing differently?

With regard to the changes to apply which I recommend, they are in the source code, not configure file. The source code should be strictly complaint to the published Fortran Standards, which the Cray compiler enforces by default (and no option to relax). If the Cray environment is causing you troubles, I'm confident that also the GNU and the Intel compiler will produce the same failure, if requested to enforced standard compliance (which you can do with compiler switches as described in the documentation I linked above). Let me know if you need assistance exploring this option, which might be more convenient for you than utilizing the Cray environment

**Comment by siddsghosh** [comment]
The **crayenv** hasn't changed since we have seen this error.

**Comment by weiwangncar** [comment]
@davidedelvento @siddsghosh In Davide's first compile attempt, we did not see any errors related to ESMF libraries used in WRF, but they appeared in the second try. We didn't change anything regarding ESMF, hence something else must have caused these errors.

**Comment by davidedelvento** [comment]
Thanks @weiwangncar 
I can confirm that in the second try something was broken on our side. I've now made a fresh recompile with the latest v4.4 release (candidate?) branch and cray container. The hybrid (=dm+sm) version now compiles successfully (yay!)

I've also attempted running this hybrid version, but not having anything else suitable I adapted Dave Gill's pure MPI case, and that quits with MPI_Abort because of some namelist settings (if my understanding is correct). See /glade/scratch/ddvento/ch/WRF-Derecho/WRF/test/em_real-WRF_TINY_TEST_KIT for details.

If you can please help me running a small hybrid test case (or if you can run it yourself), that would be great, so we can confirm that it works, close this issue and be ready for Derecho!

Thanks

**Comment by weiwangncar** [comment]
@davidedelvento That is great to know that the pre-release code is now compiling in derecho environment! I will let you know when I get that small case to run on Cheyenne.
