### ISSUE TITLE
WRF stops with segmentation fault when I use MYNN2.5 / 3 PBL scheme

### ISSUE THREAD

**Issue by bjkindia** [wrf-model/WRF#1674]
I running WRF-4.3.3 with 2km grid resolution and 61vertical levels. 16 vertical levels below 1000m. ECMWF reanalysis as initial conditions

WRF stops after a few hours when I use MYNN2.5 or MYNN3 scheme and even I tried with different time steps like 2,4,6,8,10,12 nothing works. 
Does anyone have the same experience with this and any solutions?

below you can find namelist file 

 &time_control
 run_days                            = 0,
 run_hours                           = 0,
 run_minutes                         = 0,
 run_seconds                         = 0,
 start_year                          = 2021, 2019, 2000,
 start_month                         = 11,   10,   01,
 start_day                           = 11,   26,   24,
 start_hour                          = 18,   00,   12,
 end_year                            = 2021, 2019, 2000,
 end_month                           = 11,   10,   01,
 end_day                             = 12,   27,   25,
 end_hour                            = 10,   12,   12,
 interval_seconds                    = 3600
 input_from_file                     = .true.,.T.,.true.,
 history_interval                    = 60,  60,   60,
 frames_per_outfile                  = 1, 1000, 1000,
 restart                             = .false.,
 restart_interval                    = 7200,
 io_form_history                     = 2
 io_form_restart                     = 2
 io_form_input                       = 2
 io_form_boundary                    = 2
 debug_level                         = 0
 /

 &domains
 time_step                           = 12,
 use_adaptive_time_step		     = .T.
 step_to_output_time 		     = .T. 
 target_cfl                          = 0.8, 1.2,
 starting_time_step		     = 16, 16,
 max_time_step                       = 20, 30,
 min_time_step                       = 5, 5
 time_step_fract_num                 = 0,
 time_step_fract_den                 = 1,
 max_dom                             = 1,
 e_we                                = 400,    151,   94,
 e_sn                                = 370,    133,    91,
 e_vert                              = 61,    61,    33,
 eta_levels                          = 1.0000, 0.9994, 0.9982, 0.9970, 0.9959, 0.9947, 0.9935, 0.9923, 0.9911, 
                                       0.9882, 0.9853, 0.9823, 0.9794, 0.9765, 0.9707, 0.9649, 0.9592, 0.9535, 0.9478, 
                                       0.9421, 0.9309, 0.9246, 0.9197, 0.8926, 0.8631, 0.8291, 0.7910, 0.7492, 0.7046, 0.6581, 
                                       0.6103, 0.5613, 0.5123, 0.4656, 0.4228, 0.3835, 0.3474, 0.3144, 0.2840, 0.2562, 
                                       0.2307, 0.2073, 0.1858, 0.1661, 0.1480, 0.1314, 0.1162, 0.1022, 0.0894, 0.0777, 
                                       0.0669, 0.0570, 0.0480, 0.0397, 0.0320, 0.0250, 0.0186, 0.0127, 0.0073, 0.0024, 
                                       0.0000,
 p_top_requested                     = 5000,
 num_metgrid_levels                  = 33,
 num_metgrid_soil_levels             = 4,
 dx                                  = 2000, 2700,  3333.33,
 dy                                  = 2000, 2700,  3333.33,
 grid_id                             = 1,     2,     3,
 parent_id                           = 1,     1,     2,
 i_parent_start                      = 1,     33,    30,
 j_parent_start                      = 1,     33,    30,
 parent_grid_ratio                   = 1,     3,     3,
 parent_time_step_ratio              = 1,     3,     3,
 feedback                            = 1,
 smooth_option                       = 0,
 wif_input_opt			     = 1,
 num_wif_levels			     = 30
 /

 &physics
 mp_physics                          = 28,   28,    -1,
 cu_physics                          = 0,    0,     0,
 ra_lw_physics                       = 4,    4,    -1,
 ra_sw_physics                       = 4,    4,    -1,
 bl_pbl_physics                      = 5,    5,    -1,
 sf_sfclay_physics                   = 5,    5,    -1,
 sf_surface_physics                  = 4,    4,    -1,
 radt                                = 2,   3,    30,
 bldt                                = 0,    0,     0,
 cudt                                = 0,    0,     5,
 icloud                              = 1,    
 icloud_bl			     = 1,    
 aer_opt			     = 3,    
 grav_settling                       = 0,    
 use_aero_icbc                       = .T.,
! use_fog_calc			     = .F., 
 num_land_cat                        = 21,
 sf_urban_physics                    = 0,     0,     0,
 /

 &fdda
 /

 &dynamics
 hybrid_opt                          = 2,
 w_damping                           = 0,
 diff_opt                            = 1,      1,      1,
 km_opt                              = 4,      4,      4,
 diff_6th_opt                        = 0,      0,      0,
 diff_6th_factor                     = 0.12,   0.12,   0.12,
 base_temp                           = 290.
 damp_opt                            = 3,
 zdamp                               = 5000.,  5000.,  5000.,
 dampcoef                            = 0.2,    0.2,    0.2
 khdif                               = 0,      0,      0,
 kvdif                               = 0,      0,      0,
 non_hydrostatic                     = .true., .true., .true.,
 moist_adv_opt                       = 1,      1,      1,
 moist_adv_dfi_opt		     = 1, 
 scalar_adv_opt                      = 1,      1,      1,
 gwd_opt                             = 1,
 time_step_sound		     = 8,
 /

 &bdy_control
 spec_bdy_width                      = 5,
 spec_zone 			     = 1,
 relax_zone 			     = 4,
 specified                           = .T., .T.,
 nested                              = .F., .T.,
 /

 &grib2
 /

 &namelist_quilt
 nio_tasks_per_group = 0,
 nio_groups = 1,
 /

**Comment by dudhia** [comment]
This should go to the Forum. More likely to get response and follow-up
there.

**Comment by mgduda** [comment]
WRF/MPAS Support Forum: https://forum.mmm.ucar.edu/ .
