### ISSUE TITLE
How to create the lookup table with P3

### ISSUE THREAD

**Issue by urkitarke** [wrf-model/WRF#1708]
Hi.
I am trying to do a simulation with the P3 parameterization but the lookup table is not created.
The rsl.out stops at:
  Reading table 1 [5.3-2momI]

Can you help me?
Do I have the namelist.input wrong?
Attach the namelist.input.

Best regards
[namelist.input.txt](https://github.com/wrf-model/WRF/files/8380119/namelist.input.txt)

**Comment by weiwangncar** [comment]
Please post this to the Forum: https://forum.mmm.ucar.edu/.
