### ISSUE TITLE
Met_ em*. nc files produced by WPS has different num_ metgrid_ Levels and num_ sm_ Layers.

### ISSUE THREAD

**Issue by liiiiiiiiber** [wrf-model/WRF#1710]
Met_ em*. nc files produced by WPS has different num_ metgrid_ Levels and num_ sm_ Layers in June 2019 and 2005 , which leads to real Exe failed to generate wrfbdy. What can I do to ensure the metgrid.exe produce the met files with same dims.

**Comment by weiwangncar** [comment]
@liiiiiiiiber Please post this to the Forum: https://forum.mmm.ucar.edu/. Thanks.
