### ISSUE TITLE
Error when compiling WPS, metgrid.exe is missing

### ISSUE THREAD

**Issue by xpji** [wrf-model/WRF#1713]
hi @all

An error occurred when compiling WPS, metgrid.exe was missing，the errors show as  following 

![image](https://user-images.githubusercontent.com/60537770/162210239-ce9085d0-7f23-48c7-8217-aed020f2deb3.png)

Looking forward to your answer，thank you

**Comment by mgduda** [comment]
Please use the WRF support forum at https://forum.mmm.ucar.edu to ask these sorts of questions. We generally use GitHub Issues to track code bugs or to-do items, and not for providing assistance.
