### ISSUE TITLE
2-m diagnostics with RUC LSM

### ISSUE THREAD

**Issue by tanyasmirnova** [wrf-model/WRF#1719]
**Describe the bug**
In module_sf_sfcdiags_ruclsm.F90 flux =.false., while it should be set to .true. as a default method.

**To Reproduce**
1. Use compiler and version '....'
2. Use namelist options '....'
3. Output is '....'

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, attach supporting files: namelist.input, rsl.* files, etc.

**Additional context**
Add any other context about the problem here, such as:
   - This used to work with a previous version.
   - The documentation is different from the exhibited behavior.

**Comment by weiwangncar** [comment]
No issue posted.
