### ISSUE TITLE
Issue with open boundary conditions

### ISSUE THREAD

**Issue by huangynj** [wrf-model/WRF#1723]
Dear WRF team,

I would like report an issue which always exists when I run WRF model with open boundary conditions.
There are some strange values near the domain boundaries during the model run (see attached figure), and areas with strange values enlarge with time. I always encountered this issue when using open boundary conditions, but it is the first time for me to report it. Do you have ideas to solve this issue? I did not meet the issue using CM1. 

Thanks,
Yongjie

<img width="1049" alt="WRF_open_boundary_issue" src="https://user-images.githubusercontent.com/5990047/164812564-d8606904-d5ac-4f18-a78e-e1ec98e6c380.png">

**Comment by dudhia** [comment]
We have typically avoided this with multiple nest levels and a large outer
domain with periodic boundaries.
However you can't make the top and bottom periodic unless you use constant
f and a channel could be used instead.
Jimy

**Comment by huangynj** [comment]
> 

Thank you, Jimy, for the suggestion!
Yongjie

**Comment by huangynj** [comment]
Thank you, Jimy, for the suggestion!
Yongjie

**Comment by weiwangncar** [comment]
@huangynj Issue like this should be posted to the user forum.
