### ISSUE TITLE
Error in the compilation of WRF

### ISSUE THREAD

**Issue by Anirbanm0101** [wrf-model/WRF#1730]
I am trying to install WRF in my system and I am using the following steps:
I already have the libraries installed in my system with their path given in the .profile file. Now, when I am trying to compile WRF, I am getting the error below (screenshot attached). After uncompressing the source code, I executed the configure file with the choice given 32 as I am using gfortran compiler. After that, I used the following commands
```
./compile em_real >&log&
tail -f log
```
During this part, the compilation isn't done and I am getting the error. I searched on the internet for the error but wasn't able to find a proper solution. Any suggestion on how to solve this error would be helpful.

![image](https://user-images.githubusercontent.com/99262949/166065429-8e920af9-521e-4852-9767-a7234acbdc13.png)

**Comment by weiwangncar** [comment]
@Anirbanm0101 Please post this to the Forum. Make sure you either downloaded the right model tar file, or if you use git clone, make sure you read the Release notes.
