### ISSUE TITLE
How can new options be added to namelist.input 

### ISSUE THREAD

**Issue by lizeting** [wrf-model/WRF#1732]
Hi,
    I want to add new instruments to WRFDA and  add corresponding options.  I added options in registry.var ,  but the compilation failed,  may I ask which files need to be modified.  Thanks.

**Comment by weiwangncar** [comment]
@lizeting Thank you for your question. However this question does not belong here. Could you please post the question to the Forum: https://forum.mmm.ucar.edu/?
