### ISSUE TITLE
WRF with WSM5 as microphysics stops at first nested domain

### ISSUE THREAD

**Issue by pratiman-91** [wrf-model/WRF#1737]
**Describe the bug**
When using WSM5 (`mp_physics=4`) in a nested domain, WRF stops at the creation of the 1st nested domain without any error. To be exact `d02 2007-05-27_12:00:00  alloc_space_field: domain            3 ,               36606528  bytes allocated` is the last line. I have provided a rsl.error.0000 file with debug set to 1000.

The same simulation runs perfectly with Purdue Lin (`mp_physics=2`) scheme.

**To Reproduce**
1. Use compiler and version `Intel 19.1.1.217 20200306`
2. Use namelist options `
&physics
mp_physics               = 4,      4,      4,
ra_lw_physics            = 1,        1,        1,
ra_sw_physics            = 1,        1,        1,
radt                     = 20,       20,       20,
sf_sfclay_physics        = 2,        2,        2,
sf_surface_physics       = 2,        2,        2,
bl_pbl_physics           = 2,        2,        2,
bldt                     = 0,        0,        0,
cu_physics               = 1,        1,        0,
cudt                     = 0,        0,        0,
surface_input_source     = 1,
num_soil_layers          = 4,
sf_urban_physics         = 2,        2,        2,
`

**Expected behavior**
It should be able to create `wrfout_d02`

**Screenshots**
NA

**Attachments**
Supporting files: namelist.input, rsl.error.0000
[namelist.input.txt](https://github.com/wrf-model/WRF/files/8748839/namelist.input.txt)
[rsl.error.0000.txt](https://github.com/wrf-model/WRF/files/8748837/rsl.error.0000.txt)

**Additional context**
I have tested this with 4.4, 4.2.1, and 3.9.1.1

**Comment by weiwangncar** [comment]
@pratiman-91 I think this is best posted on the User's Forum: https://forum.mmm.ucar.edu/. Thanks.

**Comment by pratiman-91** [comment]
I found a solution to this. I needed to add CLDFRA as a variable in the wrfinput_d* files. I do not know why this variable was absent in the wrfinput files. Once added, now everything works fine.
