### ISSUE TITLE
Error reading CAMtr_volume_mixing_ratio for CCE compiler

### ISSUE THREAD

**Issue by pkb99** [wrf-model/WRF#1741]
Hi there

This relates to running version 4.4 as downloaded as a tar file.

At the start of the run, it tries to read the file CAMtr_volume_mixing_ratio and this fails for the CCE compiler. I see this file was added to v4.4/run in https://github.com/wrf-model/WRF/pull/1665 and was not existing in the run directory in previous versions of WRF.

The read of this file in phys/module_ra_clWRF_support.F  fails with the CCE compiler because by design the read goes until it hits- the end of the file (when istatus is not 0):

```
DO WHILE (istatus == 0)
                READ(UNIT=iunit, FMT='(I4, 1x, F8.3,1x, 4(F10.3,1x))', IOSTAT=istatus)    &
                     yrdata(idata), co2r(idata), n2or(idata), ch4r(idata), cfc11r(idata), &
                     cfc12r(idata)
                mondata(idata) = 6
                idata=idata+1
             END DO
             CLOSE(iunit)

 …… snipped ….

             IF (istatus /= -1) THEN
                WRITE(message,*) "   Not normal ending of CAMtr_volume_mixing_ratio file"
                call wrf_error_fatal( message)
             END IF
```

While “IF (istatus /= -1)”  is fine for the Intel compiler at least, the CCE compiler throws the error status code “-4001” when it reads past the end of a file, not “-1”.  Thus, the code takes a fatal error.

Not sure what the best fix is – probably just check istatus for -1 or -4001 (unless there are even more error codes for other compilers).

Thanks!
Tricia

**Comment by weiwangncar** [comment]
@pkb99 If you make the change to check -4001 instead of -1, does it allow the code to work for you?

**Comment by jatin-kala** [comment]
Hi there,
I have also reproduced this error with the Cray CCE compiler, and I can confirm that replacing -1 with -4001 fixes the issue, hope this helps.
Regards
Jatin

**Comment by pkb99** [comment]
Sorry yes, I thought I'd replied to this - thank you Jatin.  The check has to be for -4001 and -1 to handle both compilers.

**Comment by dudhia** [comment]
can someone make a pull request for this so that it gets in our 4.4.1
release?

**Comment by jatin-kala** [comment]
I have made the pull request now:
https://github.com/wrf-model/WRF/pull/1748

**Comment by pkb99** [comment]
Yes it does,  though the check has to be for -4001 and -1 to handle both compilers.

Tricia

On 11/06/2022, at 7:07 AM, weiwangncar ***@***.***> wrote:

﻿

@pkb99<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpkb99&data=05%7C01%7C%7C2059872acc564817b59a08da4b148137%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637904848681802488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xx1x8cpXkFSdXd69uk4B1C3%2BXunPa79rIfJ8szE4XrE%3D&reserved=0> If you make the change to check -4001 instead of -1, does it allow the code to work for you?
