### ISSUE TITLE
ghg_input=1 and LW-SW radiation schemes pairing

### ISSUE THREAD

**Issue by cgiannaros** [wrf-model/WRF#1746]
Dear all,

I am running some tests with the ghg_input=1 option (version 4.4). When I use the CAM LW radiation scheme in combination with the RRTM SW radiation scheme, I receive the following message during the real.exe execution: 

"ERROR: ghg_input available only for these radiation schemes: CAM, RRTM, RRTMG, RRTMG_fast. And the LW and SW schemes must be reasonably paired together: OK = CAM LW with CAM SW. OK = RRTM, RRTMG LW or SW, RRTMG_fast LW or SW may be mixed." (This is coming from the module_check_a_mundo.F). 

The above message seems to be a warning, as the real.exe execution is not being terminated; it proceeds normally with a "real_em: SUCCESS COMPLETE REAL_EM INIT" output in the end. Then, when I run wrf.exe I see the following information related to the ghg_option=1 option in the rsl.* files: 

" GHG annual values from CAM trace gas file
 Year =         2021, Julian day =          213
 CO2   =   4.176698091542527E-004 volume mixing ratio ..." 

So, can I assume that the model runs correctly with the ghg_option=1 option, despite the initial real.exe "error" (or warning) message? If this is not the case, maybe it would be better the above "error" to be fatal? 

By the way, is there is a way to add CAM-related diagnostic fluxes (e.g., LWDNB) to the model output when I use RRTM or RRTMG radiation schemes? I tried using the "iofields_filename" option in the namelist, but I get warnings ( "Unable to modify mask for lwdnb"). 

Best regards,

Christos

**Comment by weiwangncar** [comment]
@cgiannaros Please post it to the Forum: https://forum.mmm.ucar.edu/. Thanks.
