### ISSUE TITLE
WRF repo and code size

### ISSUE THREAD

**Issue by lmarelle** [wrf-model/WRF#1749]
Dear WRF development Team,

The WRF repository is currently around 500MB. If I am not mistaken, it seems to be largely due to input data files for specific microphysical schemes, such as run/ishmael-qi-qr.bin, run/ishmael-qi-qc.bin, run/p3_lookupTable_1.dat-5.3-3momI.gz, even though most users do not use these schemes.

In addition, when significant changes are made to these files, their previous states are saved in the git history. As a result the .git history is now ~250MB, and it seems like close to 200MB is due to storing the previous state of the p3 files.

Are there any plans to remove these kind of large files from the WRF repo and host them elsewhere, especially in case of future changes? Running WRF already requires downloading a lot of additional files, so model users are used to this. In addition, I think there are ways to remove large files from git history, is this something the dev team is considering? This large repo size is an issue on systems where several users have their own local version, and for temporarily rehosting private development versions on github's free version which has a max storage space of 1GB.

**Comment by dudhia** [comment]
So how much size does that save, since it only removes the history?
Thanks for pointing this option out.

**Comment by lmarelle** [comment]
Thank you very much for your answer, I did not know about shallow clones, I think it could help for most of our use cases. Concerning the other part of my question, what do you think of my suggestion of moving the input files for P3 and Jensen microphysics (and maybe other large files) out of the main repository and into a separate space, like what is already done for the WPS geog files? It seems like they are responsible of about half of even the shallow-clone size of the model, even though they are only useful for these specific setups.

**Comment by lmarelle** [comment]
Sorry, I closed the issue by mistake.

**Comment by dudhia** [comment]
We also have the option of downloading the tar file that should also save
that space.
But it is on our list of things to look at, separating our data from the
code.

**Comment by lmarelle** [comment]
Ok, great, thank you very much for your answers!
