### ISSUE TITLE
Compile Error in WRFV4.4 moving nest option

### ISSUE THREAD

**Issue by ben108472** [wrf-model/WRF#1750]
**Describe the bug**
When I compile WRFV4.4, same error is repeated.
module_comm_dm_4.G:30:0: fatal error: REGISTRY_COMM_DM_PERIOD_subs.inc: No such file or directory

**To Reproduce**
nohup ./compile em_real &>compile.log

**Attachments**
[compile.log](https://github.com/wrf-model/WRF/files/9177783/compile.log)

**Additional context**

**Comment by weiwangncar** [comment]
@ben108472 This should be posted on the Forum: https://forum.mmm.ucar.edu/. Thanks.
