### ISSUE TITLE
WRF4.4 does not compile with ifort and dmpar

### ISSUE THREAD

**Issue by lmarelle** [wrf-model/WRF#1751]
**Describing the bug**
When compiling with ifort+dmpar (15), the compilation of WRF4.4 fails with module_stoch.f90 

**Compile script output**
module_stoch.f90(117): error #7837: Two or more accessible entities, other than generic interfaces, may have the same name only if the name is not used to refer to an entity in the scoping unit.   [WRF_DM_MAXVAL]
                          wrf_dm_maxval, wrf_err_message, local_communicator_x, local_communicator_y, data_order_xzy
--------------------------^
compilation aborted for module_stoch.f90 (code 1)

**Explanation**
This issue occurs because USE module_dm is there twice in module_stoch.F when DM_PARALLEL is enabled
line 111:
    USE module_dm
line 115:
#ifdef DM_PARALLEL
    USE module_dm, ONLY : …

**Fix**
In SUBROUTINE INITIALIZE_STOCH, removing the first USE module_dm solves the issue

**Comment by weiwangncar** [comment]
@lmarelle What happens if you choose option 13, or serial option?

**Comment by lmarelle** [comment]
I am getting the same error with option 13:

module_stoch.f90(117): error #7837: Two or more accessible entities, other than generic interfaces, may have the same name only if the name is not used to refer to an entity in the scoping unit.   [WRF_DM_MAXVAL]
                          wrf_dm_maxval, wrf_err_message, local_communicator_x, local_communicator_y, data_order_xzy
--------------------------^
compilation aborted for module_stoch.f90 (code 1)

**Comment by weiwangncar** [comment]
@lmarelle Thanks for testing. Two questions: 1. If you remove the first 'USE module_dm' in module_stock.F, will it work for the serial compilation? 2. What is your version of the Intel compiler?

**Comment by lmarelle** [comment]
1. Yes this also works for serial compilation
2. ifort version is 12.1.3 20120212 I did not have issues with it with previous versions of WRF, back to at least 3.9.1

**Comment by lmarelle** [comment]
Should I create a pull request for this?

**Comment by weiwangncar** [comment]
@lmarelle Just hold on for a while. Is it possible for you to upgrade your compiler? Yours is almost 10 years old. I'm glad that you haven't encountered other problem thus far.

**Comment by weiwangncar** [comment]
@lmarelle I checked the code, and it looks the first reference to 'use module_dm' was added in v4.4, and it does appear not needed. I also tested it here using serial and dmpar option and it works. So if it is ok with you, please go ahead and make a PR to remove the first 'USE module_dm'. Thanks.

**Comment by dudhia** [comment]
This extra call was added when some WRF-Solar changes were made for the
last release. It may not be needed but we need to check why it was added.
