### ISSUE TITLE
No error message for poor MPI core distribution after activating 3D urban scheme

### ISSUE THREAD

**Issue by oscarbrousse** [wrf-model/WRF#1769]
**Describe the bug**
Recently, WRF developers implemented a check up in _share/module_check_a_mundo.F_ to see if the MPI tasks were poorly distributed. Despite the understandable need for such a check-up, the fatal error does not provide any error message when running the model with "too few" cores from the command line in order to test whether a namelist change or a new input data is working fine. This is problematic as one should be able whether to chose or not the recommendations for the MPI tasks' distribution; especially during debugging phases. In this case, this bug appeared only after activating the BEP(-BEM) model, which could have led to increased memory usage.

For an unexplained reason, commenting out the fatal error in the MPI check allowed the interactive run on the super computer facilities from University College London. The bug was the same on two machines.

We suggest adding a clearer error message on why this fatal error occurs and a switch in the namelist to ignore the MPI tasks distribution check-up.

**To Reproduce**
1. Use gfortran compiler (dmpar) and version '4.4.1'

2. Use the following modules and libraries: 
- gcc-libs/9.2.0
- compilers/gnu/9.2.0
- python/3.8.6
- git/2.32.0
- cmake/3.21.1
- openmpi-4.1.4-gcc-9.2.0-pj7s746
- parallel-netcdf-1.12.2-gcc-9.2.0-ryhg4az
- netcdf-c-4.8.1-gcc-9.2.0-hwudpbw
- netcdf-fortran-4.5.4-gcc-9.2.0-cvowtqi
- jasper-3.0.3-gcc-9.2.0-b27qxah
- libpng-1.6.37-gcc-9.2.0-zj4qygx
- zlib-1.2.12-gcc-9.2.0-6fom2cm
- perl-5.34.1-gcc-9.2.0-xsh6olg
- hdf5-1.12.2-gcc-9.2.0-sr6gjof
- m4-1.4.19-gcc-9.2.0-yp5ge32
- libtool-2.4.7-gcc-9.2.0-p7qrn4x

3. The namelist.input is the following:

> &time_control
>  run_days                            = 99,
>  run_hours                           = 2376,
>  run_minutes                         = 0,
>  run_seconds                         = 0,
>  start_year                          = 2018, 2018, 2018,
>  start_month                         = 05,   05,   05,
>  start_day                           = 25,   25,   25,
>  start_hour                          = 00,   00,   00,
>  end_year                            = 2018, 2018, 2018,
>  end_month                           = 05,   05,   05,
>  end_day                             = 26,   26,   26,
>  end_hour                            = 00,   00,   00,
>  interval_seconds                    = 21600
>  input_from_file                     = .true.,.true.,.true.,
>  history_interval                    = 180,  60,   60,
>  frames_per_outfile                  = 1, 1, 1,
>  restart                             = .false.,
>  restart_interval                    = 1440,
>  io_form_history                     = 2
>  io_form_restart                     = 2
>  io_form_input                       = 2
>  io_form_boundary                    = 2
>  debug_level                         = 0
>  iofields_filename                   = "output_fields_d1.txt","output_fields_d2.txt","output_fields_d3.txt",
>  ignore_iofields_warning             = .true.,
>  auxinput4_inname                    = "wrflowinp_d<domain>",
>  auxinput4_interval                  = 360, 360, 360,
>  io_form_auxinput4                   = 2
>  /
> 
>  &domains
>  time_step                           = 30,
>  time_step_fract_num                 = 0,
>  time_step_fract_den                 = 1,
>  max_dom                             = 3,
>  s_we                                = 1,     1,     1,
>  e_we                                = 200,   253,   211,
>  s_sn                                = 1,     1,     1,
>  e_sn                                = 200,   241,   181,
>  e_vert                              = 56,    56,    56,
>  p_top_requested                     = 5000,
> num_metgrid_levels                  = 38,
>  num_metgrid_soil_levels             = 4,
>  dx                                  = 12000, 3000, 1000,
>  dy                                  = 12000, 3000, 1000,
>  grid_id                             = 1,     2,     3,
>  parent_id                           = 0,     1,     2,
>  i_parent_start                      = 1,     75,    61,
>  j_parent_start                      = 1,     75,    90,
>  parent_grid_ratio                   = 1,     4,     3,
>  parent_time_step_ratio              = 1,     4,     3,
>  feedback                            = 1,
>  smooth_option                       = 0,
> eta_levels                          = 1.000000000,     0.998801231,     0.997603536,     0.996406972,     0.995211542,
>       0.994017184,     0.992823958,     0.991482794,     0.989975631,     0.988282144,
>       0.986379504,     0.984242380,     0.981842160,     0.979147196,     0.976122022,
>       0.972727060,     0.968918264,     0.964646637,     0.959857881,     0.954491794,
>       0.948481739,     0.941754222,     0.934228301,     0.925815403,     0.916418433,
>       0.905932009,     0.894241750,     0.881224811,     0.866749644,     0.850676894,
>       0.832860351,     0.813148856,     0.791388154,     0.767424703,     0.741109610,
>       0.712304950,     0.680890381,     0.646772981,     0.609897852,     0.570261896,
>       0.527929187,     0.483048379,     0.435872257,     0.386776686,     0.336279571,
>       0.285055518,     0.238921404,     0.198029578,     0.161911666,     0.130128920,
>       0.102271557,     0.077957153,     0.056830287,     0.038560748,     0.022843063,
>       0.000000000,
>  sfcp_to_sfcp                        = .true.
>  /
> 
>  &physics
>  mp_physics                          = 3,    3,    3,
>  cu_physics                          = 1,    0,    0,
>  ra_lw_physics                       = 1,    1,    1,
>  ra_sw_physics                       = 1,    1,    1,
>  bl_pbl_physics                      = 8,    8,    8,
>  sf_sfclay_physics                   = 1,    1,    1,
>  sf_surface_physics                  = 4,    4,    4,
>  radt                                = 30,   30,   30,
>  bldt                                = 0,    0,    0,
>  cudt                                = 5,    5,    5,
>  isfflx                              = 1,
>  ifsnow                              = 0,
>  icloud                              = 1,
>  surface_input_source                = 1,
>  num_soil_layers                     = 4,
>  num_land_cat                        = 41,
>  sst_update                          = 1,
>  sf_urban_physics                    = 3,    3,    3,
>  use_wudapt_lcz                      = 1,
>  tmn_update                          = 1,
>  maxiens                             = 1,
>  maxens                              = 3,
> maxens2                             = 3,
>  maxens3                             = 16,
>  ensdim                              = 144,
>  /
> 
>  &noah_mp
>  !!! We only use default LSM parameters
>  /
> 
>  &fdda
>  /
> 
>  &dynamics
>  w_damping                           = 0,
>  diff_opt                            = 1,
>  km_opt                              = 4,
>  diff_6th_opt                        = 1,      1,      1,
>  diff_6th_factor                     = 0.12,   0.12,   0.12,
>  base_temp                           = 290.
>  damp_opt                            = 0,
>  zdamp                               = 5000.,  5000.,  5000.,
>  dampcoef                            = 0.2,    0.2,    0.2,
>  khdif                               = 0,      0,      0,
>  kvdif                               = 0,      0,      0,
>  non_hydrostatic                     = .true., .true., .true.,
>  moist_adv_opt                       = 1,      1,      1,
>  scalar_adv_opt                      = 1,      1,      1,
>  /
> 
>  &bdy_control
>  spec_bdy_width                      = 5,
>  spec_zone                           = 1,
>  relax_zone                          = 4,
>  specified                           = .true., .false., .false.,
>  nested                              = .false., .true., .true.,
>  /
> 
>  &grib2
>  /
> 
>  &namelist_quilt
>  nio_tasks_per_group = 0,
>  nio_groups = 1,
>  /

**Expected behavior**
The model will run fine for the _real.exe_ step, but will stop just after the initialization phase when running _wrf.exe_. Changing the number of domains run won't change the bug.

**Attachments**
Here is where the model stops without providing any error message:

> d03 2018-05-25_00:00:00  Input data is acceptable to use: wrflowinp_d03
> d03 2018-05-25_00:00:00 Input data processed for aux input   4 for domain   3
>  Tile Strategy is not specified. Assuming 1D-Y
> WRF TILE   1 IS      1 IE     21 JS      1 JE      9
> WRF NUMBER OF TILES =   1

**Additional context**
This used to work with a previous version (v4.3)

**Comment by weiwangncar** [comment]
@oscarbrousse This should be posted to the Forum site: https://forum.mmm.ucar.edu/. When you post, please attach the entire rsl.error.0000 file. It looks like you compiled the code using dmpar, but somehow you are running it using OpenMP or smpar command.
