### ISSUE TITLE
Using dust only opt, no Dust_x variables in wrfinput_d0x files

### ISSUE THREAD

**Issue by StrayMetal** [wrf-model/WRF#1771]
**Describe the bug**
I am a very beginner of the WRF modle. I am using WRF-Chem (WRF version 4.4.1) with chem-opt=401 and dust-opt=1 to conduct the exercise 1(dust only simulation) on the WRF-CHEM homepage, but after I run the real.exe program, there is no Dust_x variables in the wrfinput files. Is there any way to solve this problem? I've tried WRF vesion 4.3.3, but I still failed.
Thanks very much for your reading.

**Comment by weiwangncar** [comment]
@StrayMetal This should be posted on the Forum: https://forum.mmm.ucar.edu/. Thanks.

**Comment by StrayMetal** [comment]
> 

Thanks for your reply.
