### ISSUE TITLE
obs nudging

### ISSUE THREAD

**Issue by rahanozturk** [wrf-model/WRF#1777]
Hello, I'm not fammiliar with compiler and f90 codes etc. so I really do not know how to check and read them.
I want to use surface observation nudging with wrf and read resources, set up my namelist, create OBSNUDGING101, and attach the files here in the forum: "https://forum.mmm.ucar.edu/threads/nudging.11954/".

I found a file on the internet with fonc, finest and ifon in codes but didn't understand what they are doing and how to fix it. My guess is that I had to install/compile additional files to use observation nudging. Maybe the OBSDOMAIN101 file is wrongly created?

Thank you,

**Comment by weiwangncar** [comment]
@rahanozturk I'm sorry but your issue doesn't belong to this post. Please post your question to https://forum.mmm.ucar.edu/. Thank you.
