### ISSUE TITLE
---> Problems building executables, look for errors in the build log <---

### ISSUE THREAD

**Issue by hamedhafizi** [wrf-model/WRF#1780]
The compilation process went without any problems until tail -f compile.log. At this point, the system wasn't able to make the 4 executable files, so it showed an error message that said, "Problems building executables." I've included a screenshot of this message below. I have also included the WRF file (compile.log) in the attachments. Let me know if someone has experienced the same issue and knows how to solve it.

[compile.log](https://github.com/wrf-model/WRF/files/9899445/compile.log)
![WRF error message ](https://user-images.githubusercontent.com/52052483/198967018-51050017-bac2-4fab-8c8a-eef4e96ee1bf.jpeg)

**Comment by weiwangncar** [comment]
@hamedhafizi This should be posted on the Users' Forum: https://forum.mmm.ucar.edu/. Thanks.
