### ISSUE TITLE
real.exe

### ISSUE THREAD

**Issue by mostafaeshimy007** [wrf-model/WRF#1784]
DYNAMICS OPTION: Eulerian Mass Coordinate
   alloc_space_field: domain            1 ,             108250112  bytes allocated
 Domain            1  W A R N I N G : Variable rainc already on history stream            0 .  File: vars_d01.txt at line            1
 Domain            1  W A R N I N G : Variable rainnc already on history stream            0 .  File: vars_d01.txt at line            1
 Domain            1  W A R N I N G : Variable t2 already on history stream            0 .  File: vars_d01.txt at line            1
 Domain            1  Setting history stream            0  for t2max
 Domain            1  Setting history stream            0  for t2min
 Domain            1  Setting history stream            0  for t2mean
d01 2000-01-01_00:00:00  Yes, this special data is acceptable to use: OUTPUT FROM METGRID V4.3
d01 2000-01-01_00:00:00  Input data is acceptable to use: met_em.d01.2000-01-01_00:00:00.nc
 metgrid input_wrf.F first_date_input = 2000-01-01_00:00:00
 metgrid input_wrf.F first_date_nml = 2000-01-01_00:00:00
d01 2000-01-01_00:00:00 Timing for input          1 s.
d01 2000-01-01_00:00:00          flag_soil_layers read from met_em file is  1
Max map factor in domain 1 =  1.27. Scale the dt in the model accordingly.
ERROR in psfc: flag_psfc =  1, flag_soilhgt =  1, flag_slp =  0, sfcp_to_sfcp = F
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    1416
not enough info for a p sfc computation

namelist .wps

&share
 wrf_core = 'ARW',
 max_dom = 2,
 start_date = '2000-01-01_00:00:00','2000-01-01_00:00:00',
 end_date   = '2000-12-31_18:00:00','2000-12-31_18:00:00',
 interval_seconds = 21600
/

&geogrid
 parent_id         =   1,   1,
 parent_grid_ratio =   1,   3,
 i_parent_start    =   1,  35,
 j_parent_start    =   1,  60,
 e_we              =  200, 301,
 e_sn              =  200, 301,
 geog_data_res = 'default','default',
 dx = 27000,
 dy = 27000,
 map_proj = 'mercator',
 ref_lat   =  23.40,
 ref_lon   = 31.19,
 truelat1  =  27.40,
 truelat2  =  27.40,
 stand_lon = 31.19,
 geog_data_path = '/home/marwa/WRF/Downloads/WPS_GEOG/'
/

&ungrib
 out_format = 'WPS',
 prefix = 'FILE',
/

&metgrid
 fg_name = 'FILE'
/
&share
 wrf_core = 'ARW',
 max_dom = 2,
 start_date = '2000-01-01_00:00:00','2000-01-01_00:00:00',
 end_date   = '2000-12-31_18:00:00','2000-12-31_18:00:00',
 interval_seconds = 21600
/

&geogrid
 parent_id         =   1,   1,
 parent_grid_ratio =   1,   3,
 i_parent_start    =   1,  35,
 j_parent_start    =   1,  60,
 e_we              =  200, 301,
 e_sn              =  200, 301,
 geog_data_res = 'default','default',
 dx = 27000,
 dy = 27000,
 map_proj = 'mercator',
 ref_lat   =  23.40,
 ref_lon   = 31.19,
 truelat1  =  27.40,
 truelat2  =  27.40,
 stand_lon = 31.19,
 geog_data_path = '/home/marwa/WRF/Downloads/WPS_GEOG/'
/

&ungrib
 out_format = 'WPS',
 prefix = 'FILE',
/

&metgrid
 fg_name = 'FILE'
/
&share
 wrf_core = 'ARW',
 max_dom = 2,
 start_date = '2000-01-01_00:00:00','2000-01-01_00:00:00',
 end_date   = '2000-12-31_18:00:00','2000-12-31_18:00:00',
 interval_seconds = 21600
/

&geogrid
 parent_id         =   1,   1,
 parent_grid_ratio =   1,   3,
 i_parent_start    =   1,  35,
 j_parent_start    =   1,  60,
 e_we              =  200, 301,
 e_sn              =  200, 301,
 geog_data_res = 'default','default',
 dx = 27000,
 dy = 27000,
 map_proj = 'mercator',
 ref_lat   =  23.40,
 ref_lon   = 31.19,
 truelat1  =  27.40,
 truelat2  =  27.40,
 stand_lon = 31.19,
 geog_data_path = '/home/marwa/WRF/Downloads/WPS_GEOG/'
/

&ungrib
 out_format = 'WPS',
 prefix = 'FILE',
/

&metgrid
 fg_name = 'FILE'
/

namelist.input

 &time_control
 run_days                            = 0,
 run_hours                           = 00,
 run_minutes                         = 0,
 run_seconds                         = 0,
 start_year                          = 2000,2000,2000,
 start_month                         = 01,01,10,
 start_day                           = 01,01,08,
 start_hour                          = 00,   00,   00,
 start_minute                        = 00,   00,   00,
 start_second                        = 00,   00,   00,
 end_year                            = 2000,2000,2022,
 end_month                           = 12,12,10,
 end_day                             = 31,31,17,
 end_hour                            = 18,   18,   18,
 end_minute                          = 00,   00,   00,
 end_second                          = 00,   00,   00,
 interval_seconds                    = 21600
 input_from_file                     = .true.,.true.,
 frames_per_outfile                  = 1000, 1000,
 history_interval                    = 360, 360, 60,
 restart                             = .false.,
 io_form_history                     = 2
 io_form_restart                     = 2
 io_form_input                       = 2
 io_form_boundary                    = 2
 output_diagnostics                  = 1
 io_form_auxhist3                    = 2
 iofields_filename                   = 'vars_d01.txt','vars_d02.txt',
 auxhist3_interval                   = 1440, 1440,
 auxhist3_outname                    = "diags.d<domain>.<date>"
 frames_per_auxhist3                 =  1000,    1000,     1, 
/
 &domains
 time_step                           = 180,
 time_step_fract_num                 = 0,
 time_step_fract_den                 = 1,
 max_dom                             = 2,
 e_we                                = 200,    301,
 e_sn                                = 200,    301,
 num_metgrid_levels                  = 27,
 num_metgrid_soil_levels             = 2,
 dx                                  = 27000,
 dy                                  = 27000,
 grid_id                             = 1,     2,
 parent_id                           = 1,     1,
 i_parent_start                      = 1,     35,
 j_parent_start                      = 1,     60,
 parent_grid_ratio                   = 1,     3,
 parent_time_step_ratio              = 1,     3,
 feedback                            = 1,
 smooth_option                       = 1
 /
 &physics
 mp_physics                          = 6,     6,
 ra_lw_physics                       = 3,     3,
 ra_sw_physics                       = 3,     3,
 radt                                = 30,    30,
 sf_sfclay_physics                   = 1,     1,
 sf_surface_physics                  = 2,     2,
 bl_pbl_physics                      = 0,     0,
 bldt                                = 0,     0,
 cu_physics                          = 1,     1,
 / 
 
 &fdda
 /

 &dynamics
 w_damping                           = 0,
 diff_opt                            = 1,      1,      1,
 km_opt                              = 4,      4,      4,
 diff_6th_opt                        = 0,      0,      0,
 diff_6th_factor                     = 0.12,   0.12,   0.12,
 base_temp                           = 290.
 damp_opt                            = 0,
 zdamp                               = 5000.,  5000.,  5000.,
 dampcoef                            = 0.2,    0.2,    0.2
 khdif                               = 0,      0,      0,
 kvdif                               = 0,      0,      0,
 non_hydrostatic                     = .true., .true., .true.,
 moist_adv_opt                       = 1,      1,      1,     
 scalar_adv_opt                      = 1,      1,      1,     
 /

 &bdy_control
 spec_bdy_width                      = 5,
 specified                           = .true.
 nested                              = .true.
 /

&diags
/
 &grib2
 /

 &namelist_quilt
 nio_tasks_per_group = 0,
 nio_groups = 1,
 /

**Comment by weiwangncar** [comment]
@mostafaeshimy007 Please post this question to the user's forum: https://forum.mmm.ucar.edu/. Thanks.
