### ISSUE TITLE
Runtime Error when combining WRF-LES with WRF-Urban (BEPBEM)

### ISSUE THREAD

**Issue by htan2013** [wrf-model/WRF#1785]
**Describe the bug**
Error when combining WRF-LES with WRF-Urban

**To Reproduce**
The compiler is Intel. The model version is 4.3. ICBC is from ERA5. 
I have designed 4 domains: 2.5km, 500m, 100m, and 20m (1:5 ratio), with 61 vertical levels. The first 3 domains do not use BEPBEM. I have used Ndown to process each domain (no issue on the first 3 domains). The namelist.input for 4 domains and the innermost domain is attached.

Dear all experts:
I wanted to combine WRF-LES with WRF-Urban. Some basic settings are described above. When I tried to run the innermost domain, the error occurred on the BEPBEM file:

![image](https://user-images.githubusercontent.com/77926698/202736536-483f9285-59b4-4562-b1ca-05571f1a5df0.png)

The line 1147 in module_sf_bep_bem.f90 is "time_bep=time_bep+dt". I am not sure what caused this error. I am aware that this resolution is quite insane but I just want to try my best for my project. I will appreciate any suggestions/advice.

**Attachments**
namelist.input.4Domains (For generating wrfbdy and wrfinputs)
namelist.input.InnermostDomain
module_sf_bep_bem.f90

[module_sf_bep_bem.f90.txt](https://github.com/wrf-model/WRF/files/10042473/module_sf_bep_bem.f90.txt)
[namelist.input.4domains.txt](https://github.com/wrf-model/WRF/files/10042474/namelist.input.4domains.txt)
[namelist.input.InnermostDomain.txt](https://github.com/wrf-model/WRF/files/10042475/namelist.input.InnermostDomain.txt)

**Comment by weiwangncar** [comment]
@htan2013 Please post your issue to the User's Forum: https://forum.mmm.ucar.edu/. Thanks.
