### ISSUE TITLE
Malloc.h Header not found in Macos

### ISSUE THREAD

**Issue by HathewayWill** [wrf-model/WRF#1796]
malloc.h
make may fail in compiling some types of Unix software if it cannot find malloc.h. Software designed for older Unix systems may expect to find this header file in /usr/include; however, malloc.h is not present in this directory. The set of malloc( ) function prototypes is actually found in stdlib.h. For portability, your programs should include stdlib.h instead of malloc.h. (This is the norm; systems that require you to use malloc.h are the rare exception these days.) GNU autoconf will detect systems that require malloc.h and define the HAVE_MALLOC_H macro. If you do not use GNU autoconf, you will need to detect this case on your own and set the macro accordingly. You can handle such cases with this code:

#include <stdlib.h>
#ifdef HAVE_MALLOC_H
#include <malloc.h>
#endif

malloc.h is no longer included in current models of macos Ventura.  Is there a way to change the linkers for it in the WRF CHEM compile code for KPP?

**Comment by HathewayWill** [comment]
So one fix that is temporary is to comment out #include <malloc.h> using /* */  in:

/WRFV4.4.2/chem/KPP/kpp/kpp-2.1/src/scan.y
/WRFV4.4.2/chem/KPP/kpp/kpp-2.1/src/scanutil.c

However, this requires users to go into the files and manually comment out this issue.
This is a temporary fix and I would recommend, after talking with @jordanschnell , a pre-configure flag with that creates an variable  to run an if statement check.

If I am able to come up with a solution I will post it here.

**Comment by MicroTed** [comment]
@HathewayWill  I have run into a similar issue on macos when compiling RSL_LITE/rsl_malloc.c with homebrew gcc (11, 12, 15) instead of clang. Here is a solution I came up that only includes malloc.h if clang is the compiler. If I recall, clang doesn't actually need malloc.h, anyway, but that might be different for older versions. (gcc doesn't like the apple malloc.h and throws an error)

```
 #ifndef MACOS
 # include <malloc.h>
 #else
+/* MacOS: if using gnu gcc, then stdlib is enough, otherwise can use malloc for clang */
+#ifdef __clang__
 # include <malloc/malloc.h>
 #endif
+#endif
```
