### ISSUE TITLE
The wind fields are the same with gwd_opt equals to 3 and 0

### ISSUE THREAD

**Issue by bomarty** [wrf-model/WRF#1815]
Hello everyone!
When I run wrf.exe (Version 4.3.2) with gwd_opt equals to 3 in namelist.input, all the relevant diagnostic variables are zero, and the wind fields of all three domains (25km, 5km, and 1km)are exactly the same with gwd_opt equals to 0.
![1675136721547](https://user-images.githubusercontent.com/75073681/215661748-8929cc0a-940c-4d71-a568-af91bea7f915.jpg)

According to the users' guide,  gwd_opt equals to 3 indicates all four drag parameterization schemes (large-scale gravity wave drag, small-scale gravity wave drag, blocking drag, topographic form drag) are used in wrf.exe, and gwd_opt equal to 0 indicates no drag parameterization schemes. The result seems quite strange since the parameterization schemes should have effected the wind field obviously, especially to the surface layers. Here follows the namelist.input.

&domains
 time_step                           = 100,
 time_step_fract_num                 = 0,
 time_step_fract_den                 = 1,
 max_dom                             = 3,
 e_we                                = 80,  221, 601,
 e_sn                                = 80,  231, 651,
 e_vert                              = 51,  51,  51
 p_top_requested                     = 3000,
 num_metgrid_levels                  = 34,
 num_metgrid_soil_levels             = 4,
 dx                                  = 25000, 5000,  1000
 dy                                  = 25000, 5000,  1000
 grid_id                             = 1,     2,     3,
 parent_id                           = 1,     1,     2,
 i_parent_start                      = 1,     20,    55,
 j_parent_start                      = 3,     25,    47,
 parent_grid_ratio                   = 1,     5,     5,
 parent_time_step_ratio              = 1,     5,     5,
 feedback                            = 1,
 smooth_option                       = 2
 /

 &physics
 mp_physics                          = 8,     8,     8,
 ra_lw_physics                       = 4,     4,     4,
 ra_sw_physics                       = 4,     4,     4,
 radt                                = 30,    30,    30,
 sf_sfclay_physics                   = 1,     1,    1,
 sf_surface_physics                  = 2,     2,     2,
 bl_pbl_physics                      = 1,     1,     1,
 topo_wind                           = 0,     0,     0,
 bldt                                = 0,     0,     0,
 cu_physics                          = 1,     0,     0,
 cudt                                = 5,     0,     0,
 isfflx                              = 1,
 ifsnow                              = 1,
 icloud                              = 1,
 surface_input_source                = 1,
 num_soil_layers                     = 4,
 num_land_cat                        = 21,
 sf_urban_physics                    = 0,     0,     0,
 /

 &dynamics
 hybrid_opt                          = 0, 
 w_damping                           = 1,
 diff_opt                            = 1,      1,      1,
 km_opt                              = 4,      4,      4,
 diff_6th_opt                        = 0,      0,      0,
 diff_6th_factor                     = 0.12,   0.12,   0.12,
 base_temp                           = 290.
 damp_opt                            = 0,
 zdamp                               = 5000.,  5000.,  5000.,
 dampcoef                            = 0.2,    0.2,    0.2
 khdif                               = 0,      0,      0,
 kvdif                               = 0,      0,      0,
 non_hydrostatic                     = .true., .true., .true.,
 moist_adv_opt                       = 1,      1,      1,     
 scalar_adv_opt                      = 1,      1,      1,     
 gwd_opt                             = 3,      3,      3,     
 gwd_diags                           = 1
 /

 &bdy_control
 spec_bdy_width                      = 7,
 spec_zone                           = 1,
 relax_zone                          = 6,
 specified                           = .true., .false.,.false.,
 nested                              = .false., .true., .true.,
 /

 &grib2
 /

 &namelist_quilt
 poll_servers = T,
 nio_tasks_per_group = 0,
 nio_groups = 1,
 /

My problem is how to turn on the gwd_opt and are there any other steps to use the drag parameterization schemes appropriately in wrf.exe?
Thanks.

**Comment by weiwangncar** [comment]
@bomarty Please post this to https://forum.mmm.ucar.edu/. Thanks.

**Comment by bomarty** [comment]
@weiwangncar I've posted the question on this website, and thank you for your suggestion.
