### ISSUE TITLE
AHI data assimilation doesn't emulate channels 1-6（actually channels 7-12）

### ISSUE THREAD

**Issue by sunhuihang** [wrf-model/WRF#1816]
Hi:
I can only assimilate 7-10 channels of data with WRFDAV4.4.Himawari-8 AHI has 16 channels and WRFDA allows the assimilation of 10 IR channels (channels 7-16)，But in the radiance_info/himawari-8-ahi.info it is written as channels 1-10. When entering assimilation, the background values for channels 1-6 are not simulated, resulting in data rejection for all channels 1-6, which I think is due to the difference in channel naming for the radiation transfer mode. I've tried crtm and rttov and the results are the same. 
Can anyone gives me some help please, thanks in advance.

Here is himawari-8-ahi.info, 01_qcstat_himawari-8-ahi and a part of 01_oma_himawari-8-ahi.0000
![image](https://user-images.githubusercontent.com/56792866/215934460-e1e38870-4961-4a9c-8b6c-c4a65ead4c51.png)
![image](https://user-images.githubusercontent.com/56792866/215934586-d25de704-a13d-4eec-99e2-d46112ab6e96.png)
![image](https://user-images.githubusercontent.com/56792866/215934701-03a6d511-4cf7-42a0-91a8-2f302d3e0d5a.png)

**Comment by mgduda** [comment]
Please post requests for help to the WRF/MPAS support forum at https://forum.mmm.ucar.edu/.
