### ISSUE TITLE
Bugfix: Correct string test in configure.

### ISSUE THREAD

**Issue by HathewayWill** [wrf-model/WRF#1817]
@weiwangncar @kkeene44 @douglowe @mgduda 

**Describe the bug**
https://github.com/wrf-model/WRF/pull/1735

his is the error message.

Testing for NetCDF, C and Fortran compiler

This installation of NetCDF is 64-bit
C compiler is 64-bit
Fortran compiler is 64-bit
It will build in 64-bit

NetCDF version: 4.8.1
Enabled NetCDF-4/HDF-5: yes
NetCDF built with PnetCDF: no
./configure: 919: [: unexpected operator

While the ./configure and ./compile will finish running without issue the problem occurs at WPS ./configure. WPS ./configure will say that WRF was not compiled correctly. After modifying line 919 in my ./configure file this issue was resolved.

I believe it has to do with the fact that
In a POSIX shell, the test operator for string equality is =:

$ sh -c '[ "a" = "a" ] && echo equal'
equal

whereas

$ sh -c '[ "a" == "a" ] && echo equal'
sh: 1: [: a: unexpected operator

== is a provided as a synonym for = in the bash shell. From the CONDITIONAL EXPRESSIONS section of man bash:

**To Reproduce**
Run ./configure

**Expected behavior**
Without bug fix

```
NetCDF version: 4.9.0
Enabled NetCDF-4/HDF-5: yes
NetCDF built with PnetCDF: yes
./configure: 919: [: unexpected operator
 
```

With Bug Fix:

```
NetCDF version: 4.9.0
Enabled NetCDF-4/HDF-5: yes
NetCDF built with PnetCDF: yes
 
```

**Attachments**
  sed -i '186s/==/=/g' $WRFCHEM_FOLDER/WRFV4.4.2/configure
  sed -i '318s/==/=/g' $WRFCHEM_FOLDER/WRFV4.4.2/configure
  sed -i '919s/==/=/g' $WRFCHEM_FOLDER/WRFV4.4.2/configure

**Additional context**
Pull requested on v4.4.1 but was never added into the code.  Error still with 4.4.2

**Comment by weiwangncar** [comment]
@HathewayWill Can you describe the computer system you use? I ask the question because we don't see it on the systems we use, and we haven't had other report of this problem.

**Comment by HathewayWill** [comment]
Ubuntu 20 & Ubuntu 22
64 bit

**Comment by HathewayWill** [comment]
https://github.com/wrf-model/WRF/pull/1735#issuecomment-1203059895

**Comment by HathewayWill** [comment]
> @HathewayWill Can you describe the computer system you use? I ask the question because we don't see it on the systems we use, and we haven't had other report of this problem.


 Ubuntu 20, Ubuntu 22
64bit

https://github.com/wrf-model/WRF/pull/1735#issuecomment-1203059895
