### ISSUE TITLE
Problems building executables, look for errors in the build log

### ISSUE THREAD

**Issue by erfiiiiiii** [wrf-model/WRF#1820]
Hello,I am trying to compile WRF_Fire file and I face the problem "Problems building executables, look for errors in the build log". I have examined the log.compile but could not figure out how to resolve them. I have uploaded  the log.compile in the link below, please if anyone who knows the solution inform me. 
the link:
https://file.io/6rw7pCgOgr7e

**Comment by erfiiiiiii** [comment]
I think the exact problem comes from here

/usr/bin/ld: cannot find -lhdf5hl_fortran: No such file or directory
/usr/bin/ld: cannot find -lhdf5_hl: No such file or directory
/usr/bin/ld: cannot find -lhdf5_fortran: No such file or directory
/usr/bin/ld: cannot find -lhdf5: No such file or directory
collect2: error: ld returned 1 exit status
Command exited with non-zero status 1
0.14user 0.13system 0:01.16elapsed 24%CPU (0avgtext+0avgdata 58860maxresident)k
14344inputs+0outputs (21major+23821minor)pagefaults 0swaps
make[1]: [Makefile:17: em_wrf] Error 1 (ignored)
make[1]: Leaving directory '/home/erfan/v4.4.2/WRF/main'
( cd run ; /bin/rm -f wrf.exe ; ln -s ../main/wrf.exe . )

**Comment by smileMchen** [comment]
Please post your issue to WRF&MPAS-A Form. The website is https://forum.mmm.ucar.edu.
