### ISSUE TITLE
[Question] README.windturbine

### ISSUE THREAD

**Issue by v-veiga** [wrf-model/WRF#1824]
Hello, I'm running the WRFv4.3 using the Wind Farm Parametrization. 

However, I don't know what is the "Standing Thrust Coefficient" (https://github.com/wrf-model/WRF/blob/master/doc/README.windturbine#L86) to edit my wind-turbine-1.tbl file.

Could you explain what this means theoretically or indicate some paper/link that clarifies this question, please?

**Comment by mgduda** [comment]
Please use the WRF/MPAS support forum at https://forum.mmm.ucar.edu/ when requesting assistance with the WRF model.
