### ISSUE TITLE
WRF not installing with new netCDF 4.9.2

### ISSUE THREAD

**Issue by HathewayWill** [wrf-model/WRF#1829]
**Describe the bug**
netcdf v.4.9.2 not compatible with WRF

**To Reproduce**
See below

**Expected behavior**
Expected v4.9.2 to work the same as v4.9.0.  Confirmed with Unidata that nothing changed that they know of for v4.9.2

**Screenshots**
see below

**Attachments**
N/A

**Additional context**
I am trying to install the Weather Research and Forecasting Model (WRF) using Netcdf 4.9.2

I use these commands to install netcdf

  ##############################Install NETCDF C Library############################
  cd $WRF_FOLDER/Downloads
  tar -xzvf v4.9.2.tar.gz
  cd netcdf-c-4.9.2/
  export CPPFLAGS=-I$DIR/grib2/include
  export LDFLAGS=-L$DIR/grib2/lib
  export LIBS="-lhdf5_hl -lhdf5 -lz -lcurl -lgfortran -lgcc -lm -ldl -lpnetcdf"
  CC=$MPICC FC=$MPIFC CXX=$MPICXX F90=$MPIF90 F77=$MPIF77 ./configure --prefix=$DIR/NETCDF --disable-dap --enable-netcdf-4 --enable-netcdf4 --enable-shared --enable-pnetcdf --enable-cdf5 --enable-parallel-tests
  make -j $CPU_HALF_EVEN
  make -j $CPU_HALF_EVEN install 2>&1 | tee make.install.log
  #make check

  export PATH=$DIR/NETCDF/bin:$PATH
  export NETCDF=$DIR/NETCDF
  echo " "
It passes all the checks for WRF. But gives this error.

-----------------------------------------------------------------------
Settings listed above are written to configure.wrf.
If you wish to change settings, please edit that file.
If you wish to change the default options, edit the file:
     arch/configure.defaults
NetCDF users note:
 This installation of NetCDF supports large file support.  To DISABLE large file
 support in NetCDF, set the environment variable WRFIO_NCD_NO_LARGE_FILE_SUPPORT
 to 1 and run configure again. Set to any other value to avoid this message.
  

Testing for NetCDF, C and Fortran compiler

This installation of NetCDF is 64-bit
                 C compiler is 64-bit
           Fortran compiler is 64-bit
              It will build in 64-bit
 
NetCDF version: 4.9.2
Enabled NetCDF-4/HDF-5: yes
NetCDF built with PnetCDF: yes
 

************************** W A R N I N G ************************************
NETCDF4 IO features are requested, but this installation of NetCDF           
  /home/workhorse/WRF/Libs/NETCDF
DOES NOT support these IO features.                                          

Please make sure NETCDF version is 4.1.3 or later and was built with         
--enable-netcdf4                                                             

OR set NETCDF_classic variable                                               
   bash/ksh : export NETCDF_classic=1                                        
        csh : setenv NETCDF_classic 1                                        

Then re-run this configure script                                            

!!! configure.wrf has been REMOVED !!!

Is there a new feature in 4.9.2 that needs to be enabled?

For reference 4.9.0 worked without a problem.

Make Check reveals all tests passed.

**Comment by HathewayWill** [comment]
Issue was fixed with removing Anaconda from the .bashrc file.

Somehow conda was leaking into the environment even though it wasn't active.

Can close issue.

**Comment by OMGTaylor0814** [comment]
> Issue was fixed with removing Anaconda from the .bashrc file.
> 
> Somehow conda was leaking into the environment even though it wasn't active.
> 
> Can close issue.

Hi [HathewayWill](https://github.com/HathewayWill),

I met the same problem with you cause I could not built with
--enable-netcdf4, could you help me with it?

Best Regards,

**Comment by HathewayWill** [comment]
> > Issue was fixed with removing Anaconda from the .bashrc file.
> > Somehow conda was leaking into the environment even though it wasn't active.
> > Can close issue.
> 
> Hi [HathewayWill](https://github.com/HathewayWill),
> 
> I met the same problem with you cause I could not built with --enable-netcdf4, could you help me with it?
> 
> Best Regards,

Evening @OMGTaylor0814 what are you trying to build and what commands were you issuing?
