### ISSUE TITLE
GEN_BE2.0 for WRFDA chem assimilation

### ISSUE THREAD

**Issue by aquavirgo** [wrf-model/WRF#1842]
**Describe the bug**
I was trying to prepare a be.dat file for WRFDA for aerosol assimilation. On default settings for GEN_BE in mosaic/gocard with cv=5 I obtain errors “No variable de control qrain or qsnow or qice or qclouc has been selected”. I changed cv to 7. After that GEN_BE works correctly but in WRFDA is error Read problem in lengthscales in be.dat Trying to read lengthscales for variable 1: qrain. What interesting in WRFDA’s test files be.dat is prepared for cv=7. (And here is a wonder, because the file is without hydrometeors and it works). 

**Expected behavior**
Generated file from GEN_BE2.0 will work in WRFDA chem assimilation

**Comment by weiwangncar** [comment]
@aquavirgo Please post this to the Forum: https://forum.mmm.ucar.edu/. Thanks!
