### ISSUE TITLE
VEGPARM.TBL

### ISSUE THREAD

**Issue by mvieno** [wrf-model/WRF#1854]
**Describe the bug**
In the VEGPARM.TBL there seems to be a missing "comma" in the "Evergreen Needleleaf Forest" where the modified modis vegetations are defined as 1       .70,   4,    125., peraphs should be 1,   .70,   4,    125.,? also 11      .60,   2,     70.,    65.
....
Vegetation Parameters
MODIFIED_IGBP_MODIS_NOAH
20,1, 'SHDFAC NROOT   RS      RGL      HS      SNUP  MAXALB   LAIMIN  LAIMAX   EMISSMIN EMISSMAX ALBEDOMIN ALBEDOMAX   Z0MIN    Z0MAX   ZTOPV    ZBOTV'
1       .70,   4,    125.,    30.,   47.35,   0.08,    52.,    5.00,   6.40,   .950,    .950,     .12,      .12,      .50,     .50,      17.0,     8.5,    'Evergreen Needleleaf Forest'
2,      .95,   4,    150.,    30.,   41.69,   0.08,    35.,    3.08,   6.48,   .950,    .950,     .12,      .12,      .50,     .50,      35.0,     1.0,    'Evergreen Broadleaf Forest'
3,      .70,   4,    150.,    30.,   47.35,   0.08,    54.,    1.00,   5.16,   .930,    .940,     .14,      .15,      .50,     .50,      14.0,     7.0,    'Deciduous Needleleaf Forest'
4,      .80,   4,    100.,    30.,   54.53,   0.08,    58.,    1.85,   3.31,   .930,    .930,     .16,      .17,      .50,     .50,      20.0,    11.5,    'Deciduous Broadleaf Forest'
....

This may or may not affect the correct calculation. There are several commas missing in the data, but it may be not an issue.

**Comment by dudhia** [comment]
Thanks, we should test its effect.

**Comment by weiwangncar** [comment]
@mvieno Did this cause trouble for you? I tested this using an ifort compiler, it didn't matter there.

**Comment by mvieno** [comment]
@weiwangncar ah good to know. Are the data read ignoring the commas as separator then?

**Comment by weiwangncar** [comment]
@mvieno The commas are not used as delimiters, for sure. We will still add missing commas to the table just for its cleanness. And thanks for point them out.
