### ISSUE TITLE
WARNING when i try to compile NETCDF-fortran-4.5.2

### ISSUE THREAD

**Issue by OMGTaylor0814** [wrf-model/WRF#1856]
Hi,
I met another problem when i compile netcdf-fortran-4.5.2 as wrf onLineTutorial suggested,
Warning occurred:
`configure: WARNING: unrecognized options: --disable-dap, --disable-netcdf-4`
that cause error when I try to compile WRF,
I clean the environment which contains old WRF libraries and Anaconda, but I do have another version netcdf(4.1.3) in other folder.

here is my config.log
[config.log](https://github.com/wrf-model/WRF/files/11345796/config.log)

By the way , I don;t know why there are so many libnetcdf***.so file not in path and i have to link these file to the path, what else should I do?

Best Regards,

**Comment by weiwangncar** [comment]
@OMGTaylor0814 Please report this on the [Forum](https://forum.mmm.ucar.edu/). Thanks.
