### ISSUE TITLE
Error while installing BoxMG for WRF-Elec

### ISSUE THREAD

**Issue by ashishShaji333** [wrf-model/WRF#1857]
I have been trying to install BoxMG for WRF-Elec, and the system produced the following error while doing so.

mpif77 -funderscoring -DRKIND=4 -I../../include -I../../extras/msg/include -I../../extras/boxmg-serial/include -Waliasing -Wsurprising -O3 -I/home/ashishshaji/Build_WRF/LIBRARIES/grib2/include -DBOXMG_TIMER_ETIMEi -DBOXMG_TIMER_ETIMEi -DBOXMG_TIMER_ETIMEi -c -o BMG2_SymStd_DUMP_vector.o BMG2_SymStd_DUMP_vector.F
BMG2_SymStd_DUMP_vector.F:186:28:

156 | CALL MPI_Bcast( TMP_iBUFFER, NTMP_iBUFFER, MPI_INTEGER,
| 2
......
186 | CALL MPI_Bcast( IO_DONE, iONE, MPI_INTEGER,
| 1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
BMG2_SymStd_DUMP_vector.F:209:28:

156 | CALL MPI_Bcast( TMP_iBUFFER, NTMP_iBUFFER, MPI_INTEGER,
| 2
......
209 | CALL MPI_Bcast( IO_CONT, iONE, MPI_INTEGER,
| 1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
make[2]: *** [<builtin>: BMG2_SymStd_DUMP_vector.o] Error 1
rm BMG2_SymStd_ErrTrap.o BMG2_SymStd_LineSolve_A.o BMG2_SymStd_SETUP_space.o BMG2_SymStd_COPY_cg_WS_So_O BMG2_SymStd_SETUP_interp_OI.o BMG2_SymStd_SETUP_PtrGrid.o BMG2_SymStd_UTILS_dxpby.o BMG2_SymStd_UTILS_norm_l2.o BMG2_SymStd_UTILS_dot_l2.o BMG2_SymStd_SETUP_parms.o BMG2_SymStd_SETUP_nog.o BMG2_SymStd_SETUP_MSG.o BMG2_SymStd_ncycle.o BMG2_SymStd_residual.o BMG2_SymStd_SETUP_fine_stencil.o BMG2_SymStd_COPY_cg_rV_G_L.o BMG2_SymStd_SOLVE_pcg.o BMG2_SymStd_UTILS_zero_times.o BMG2_SymStd_SETUP_MSGGrid.o BMG2_SymStd_relax_lines_y.o BMG2_SymStd_SETUP_ITLI_bl.o BMG2_SymStd_UTILS_matvec.o BMG2_SymStd_interp_add.o BMG2_SymStd_UTILS_reswt.o BMG2_SymStd_UTILS_bbody9.o BMG2_SymStd_SETUP_recip.o BMG2_SymStd_relax.o BMG2_SymStd_SETUP_LS.o BMG2_SymStd_COPY_cg_WS_RHS.o BMG2_SymStd_SETUP_ITLI_ex.o BMG2_SymStd_UTILS_rV_zero.o BMG2_SymStd_SETUP_relax.o BMG2_SymStd_OUTPUT_times.o BMG2_SymStd_UTILS_bbody5.o BMG2_SymStd_SETUP_cg_parms.o BMG2_SymStd_SETUP_cg_LU.o BMG2_SymStd_restrict.o BMG2_SymStd_relax_lines_x.o BMG2_SymStd_SETUP_LSGrid.o BMG2_SymStd_SETUP_lines_x.o BMG2_SymStd_LineSolve_C.o BMG2_SymStd_SOLVE_cg_boxmg.o BMG2_SymStd_SETUP_PtrLS.o BMG2_SymStd_SOLVE_cg_LU.o BMG2_SymStd_SETUP_PtrWork.o BMG2_SymStd_SOLVE_boxmg.o BMG2_SymStd_updown.o BMG2_SymStd_SETUP_parts.o BMG2_SymStd_PRECON_boxmg.o BMG2_SymStd_SETUP_cg_boxmg.o BMG2_SymStd_UTILS_update_ghosts.o BMG2_SymStd_GET_pointers.o BMG2_SymStd_SETUP_ProcGrid_file.o BMG2_SymStd_SETUP_PtrMSGSo_O BMG2_SymStd_SETUP_MSGGridSo_O BMG2_SymStd_LineSolve_B.o BMG2_SymStd_SETUP_lines_y.o BMG2_SymStd_relax_GS.o BMG2_SymStd_SETUP_PtrMSG.o BMG2_SymStd_UTILS_dscal.o BMG2_SymStd_UTILS_dcopy.o BMG2_SymStd_UTILS_daxpy.o BMG2_SymStd_PRECON_diag.o
make[1]: *** [Makefile:121: library] Error 2
make: *** [Makefile:104: makewithflags] Error 2

Can anyone help me with this?

**Comment by mgduda** [comment]
Please work with the BoxMG or WRF-Elec groups to resolve this.
