### ISSUE TITLE
Error in WRF configure using option 34

### ISSUE THREAD

**Issue by inomyabcs** [wrf-model/WRF#1869]
edit: Using WRF 4.5

Configure was failing on line 1046 with message `./configure: 1046: [: rpc: unexpected operator` and stems from an extra equals sign in the test.

Original
`if [ $rpc_type == "rpc" ]; then`

Working
`if [ $rpc_type = "rpc" ]; then`

**Comment by weiwangncar** [comment]
@inomyabcs What kind of computer system do you have?

**Comment by inomyabcs** [comment]
Windows 11 through Debian 11 WSL. AMD 3600 Zen 2 with 32 GB RAM. I was able to get through the 4.4.2 configure previously using the same set-up.

**Comment by weiwangncar** [comment]
@inomyabcs Thanks. Will make a PR to correct this.

**Comment by zexhan07** [comment]
hello i am also facing same error while configure the latest version of wrf 4.5. 

######################
------------------------------------------------------------------------
Settings listed above are written to configure.wrf.
If you wish to change settings, please edit that file.
If you wish to change the default options, edit the file:
     arch/configure.defaults
NetCDF users note:
 This installation of NetCDF supports large file support.  To DISABLE large file
 support in NetCDF, set the environment variable WRFIO_NCD_NO_LARGE_FILE_SUPPORT
 to 1 and run configure again. Set to any other value to avoid this message.
  
./configure: 1046: [: rpc: unexpected operator
*****************************************************************************
This build of WRF will use classic (non-compressed) NETCDF format
*****************************************************************************
