### ISSUE TITLE
Running WRF4.5, ./wrf.exe reports an error

### ISSUE THREAD

**Issue by Foxcrash2021** [wrf-model/WRF#1870]
**Describe the bug**
I encountered a problem when I ran WRF4.5 to ./wrf.exe, that is, it would stop after a short while, and there was no error reported in the rsl.error.0000 file. I don’t know what’s going on.I encountered a problem when I ran WRF4.5 to ./wrf.exe, that is, it would stop after a short while, and there was no error reported in the rsl.error.0000 file. I don’t know what’s going on. I don't know if anyone can help me.I’m as follows Attached are my input and rsl.error and lcz.tbl files

**Screenshots**
![1684807073887](https://github.com/wrf-model/WRF/assets/94523993/f5970b07-aa49-4d34-aa54-b2b8240b02d4)

**Attachments**
[rsl.error.0000.txt](https://github.com/wrf-model/WRF/files/11538473/rsl.error.0000.txt)
[URBPARM_LCZ.TBL.txt](https://github.com/wrf-model/WRF/files/11538474/URBPARM_LCZ.TBL.txt)
[namelist.input.txt](https://github.com/wrf-model/WRF/files/11538475/namelist.input.txt)

**Additional context**
WRF4.5 with WPS4.5 ,the geographic data specified is CGLC_MODIS_LCZ_global

**Comment by weiwangncar** [comment]
@Foxcrash2021 Please post this question on the Forum: https://forum.mmm.ucar.edu/. Thanks.

**Comment by weiwangncar** [comment]
This is closed.
