### ISSUE TITLE
wrf 4.5 & 4.4 chem compile issue

### ISSUE THREAD

**Issue by zexhan07** [wrf-model/WRF#1874]
hello there, i am trying to install wrf chem model, everything goes well when i try to compile, it show this error 
"**Problems building executables, look for errors in the build log**" 

i went to log file and check the error it is
 **"ERROR: variable name for third body in KPP species file is expected to be M, but was not found in cbm4 species file"** 

i had tried other versions like 4.4.1, 4.4 but still same issue. i don't know how to solve that i am trying to install wrf from last few weeks. please anyone help me how can i solve that? 

additionally, i want to ask what wrf model should i need to install for fog and smog predictions? wrf chem or wrf arw? 
thanks

**Comment by weiwangncar** [comment]
@zexhan07 Please post this on the Forum: https://forum.mmm.ucar.edu/. Please describe your computer system, the command you use to compile WRF Chem. WRF model itself has a fog option, grav_settling (look for it in run/README.namelist), and it could be explored.

**Comment by lixiangbailanzhuyi** [comment]
I have encountered the exact same problem as you, and there is no good solution at the moment

**Comment by lixiangbailanzhuyi** [comment]
Ok, I think I solved the problem
This is the workaround I found, I hope it will be useful for you
Similarly, the apt-installed version of flex library was flex 2.6.4, which resulted in errors " ERROR: variable name for third body in KPP species file is expected to be M, but was not found in cbm4 species file" . For which installing version 2.5.3 solved the problem, which was already mentioned in https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?t=544

**Comment by weiwangncar** [comment]
@jordanschnell Do you think it is worth looking into compatibility of KPP code with flex library 2.6.4?
