### ISSUE TITLE
Why did I get an error when I installed it

### ISSUE THREAD

**Issue by xiongyuup** [wrf-model/WRF#1879]
make[3]: 进入目录“/home/D403-2/桌面/WRF-4.5/WRF-4.5/phys”
make[3]: *** 没有规则可以创建“module_sf_noahmplsm.o”需要的目标“module_sf_noahmplsm.F”。 停止。
make[3]: 离开目录“/home/D403-2/桌面/WRF-4.5/WRF-4.5/phys”
ar: module_sf_noahdrv.o: 没有那个文件或目录
make[2]: [physics] 错误 1 (忽略)
make[2]: 离开目录“/home/D403-2/桌面/WRF-4.5/WRF-4.5/phys”
make[1]: 离开目录“/home/D403-2/桌面/WRF-4.5/WRF-4.5”

------------------------------------------------------------------------------
Error Error Error NoahMP submodule files not populating WRF directories

**Comment by weiwangncar** [comment]
@xiongyuup This question should be posted on the Forum (https://forum.mmm.ucar.edu/). Starting from WRF v4.4, you will need to be online when compiling WRF code. Read the release notes.
