### ISSUE TITLE
Dry deposition velocity is getting zero values on WRF-Chem with MOZART GOCART

### ISSUE THREAD

**Issue by niljai2009** [wrf-model/WRF#1892]
I am running WRF-Chem v4.4  with chem_opt=112 (i.e. MOZART GOCART). I am interested to see the total runoff due to dry and wet BC. The simulation goes well and I get the BC concentration i.e. both hydrophobic and hydrophilic BC (BC1 & BC2). But when I try to see the dry deposition velocity, it gives 0 value. To perform this simulation I used FINN for biomass burning emissions, EDGAR for the anthropogenic emissions, and MEGAN for biogenic emissions. 
The namelist and figures are attached. Please advise Why I am getting 0 dry deposition velocity and how I can calculate total runoff due to BC?

**To Reproduce**
1. Use compiler and version ' WRF-Chem v4.4'
2. Use namelist options 'with chem_opt=112'
3. Output is 'getting zero values for dry deposition velocity'

**Expected behavior**
Non-zero values for dry deposition velocity.

**Screenshots**
![image](https://github.com/wrf-model/WRF/assets/138407057/9b7b4934-166e-4f9f-8f85-e35fb2d17de0)

**Attachments**

[namelist.txt](https://github.com/wrf-model/WRF/files/11931973/namelist.txt)

**Comment by weiwangncar** [comment]
@niljai2009 Please post this in the user's forum: https://forum.mmm.ucar.edu/. Thanks!

**Comment by niljai2009** [comment]
@weiwangncar Thank you so much.
