### ISSUE TITLE
WRF takes a long time to run

### ISSUE THREAD

**Issue by lucasezapata** [wrf-model/WRF#1913]
Dear All,

I have compiled the WRF model on a server and in the first tests I noticed considerably lower performance than the same model has on other of our servers, which catches our attention since the latter are older and have fewer resources.
When I run a run no error appears but it takes a long time to finish. 

I tried replacing the mpich library with open mpi, however there were no improvements. 
Could the problem be in the compilation of the model?

**Comment by mgduda** [comment]
For assistance with the WRF model, please post your question to the support forum at https://forum.mmm.ucar.edu/.
