### ISSUE TITLE
Couple of questions about new Users Guide

### ISSUE THREAD

**Issue by HathewayWill** [wrf-model/WRF#1914]
**Describe the bug**
Few Dead Links and Missing Data

**To Reproduce**
Go to this website and follow this link:

https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/utilities_tools.html#design-wrf-model-domains

https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/overview.html

&noahmp namelist options is not included in the users guide.

**Comment by kkeene44** [comment]
@HathewayWill 
For the first link (utilities/tools), I believe you were referring to the broken links for WRF and WRFDA?
For the second link (overview), I think you were referring to the script that was listed at the top. 
If so, I've corrected those, and I've added the noah_mp namelist section.

**Comment by HathewayWill** [comment]
Thank you
