### ISSUE TITLE
I cannot build wrfplus due to OpenMP syntax error.

### ISSUE THREAD

**Issue by kitoyomi** [wrf-model/WRF#1915]
**Describe the bug**
When I build wrfplus with OpenMP enabled, I get an OpenMP syntax error.

Thread parallelization using OpenMP for the do loop at lines 1057, 1118, 1162, 1205, 1224, 1269, and 1322 of main/module_wrf_top.F.
However, OpenMP is not allowed to exit the do loop on exit, resulting in the following compile error.

../main/module_wrf_top.f90(1200): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                     exit tlextract
--------------------------^

**To Reproduce**
When I use ifort of IntelOneAPI
1. Configure to build wrfplus with configure command.
2. Modify configure.wrf to enable OpenMP.
3. Build wrfplus with compile command.

**Expected behavior**
wrfplus cannot be built.

**Screenshots**
N/A

**Attachments**
N/A

**Additional context**

../main/module_wrf_top.f90(941): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                exit adforce
---------------------^
../main/module_wrf_top.f90(1002): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                     exit adextract
--------------------------^
../main/module_wrf_top.f90(1045): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                         exit nlforce
------------------------------^
../main/module_wrf_top.f90(1089): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                           exit numextract
--------------------------------^
../main/module_wrf_top.f90(1106): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                           exit denextract
--------------------------------^
../main/module_wrf_top.f90(1147): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                  exit tlforce
-----------------------^
../main/module_wrf_top.f90(1200): error #7566: A RETURN or EXIT statement is not legal in a DO loop associated with a parallel directive.
                     exit tlextract
--------------------------^

**Comment by liujake** [comment]
This is expected. WRFDA and WRFPlus do not support OpenMP.
