### ISSUE TITLE
Unable to find Netcdf.inc Debian12 LMOD

### ISSUE THREAD

**Issue by walee-1** [wrf-model/WRF#1917]
Hi,
I currently face the issue: 
```
Error : Not found /mnt/nfs/clustersw/Debian/bookworm/netcdf/4.9.2/include/netcdf.inc
        Please check this installation of NetCDF and re-run this configure script
./configure: 664: exit: Illegal number: -1
```

while trying to run ./configure on a slurm based cluster with Debian12 using the LMOD system. I have netcdf-c (4.9.2) and netcdf-fortran(4.6.1) both installed in a single netcdf folder e.g. /mnt/nfs/clustersw/Debian/bookworm/netcdf/4.9.2

I double checked to see if the netcdf.inc was there and my installation is fine and indeed the file is there. I wanted to ask if this error in the building of WRF is due to the fact that we have had to install the netcdf binaries separately into a single folder and are trying to load them via a single module command or is it just simple incompatibility of the version with the WRF version 4.5.1. 

Every solution I have seen to this problem has been to simply have the fortran files in the same place as the c netcdf, which we do, I made sure of that but I still can't get the program to compile. Any help will be highly appreciated.

**Comment by weiwangncar** [comment]
Please consult on the Forum: https://forum.mmm.ucar.edu/. Thanks.
