### ISSUE TITLE
tslist file reinitialized when nest begins

### ISSUE THREAD

**Issue by mathieulandreau** [wrf-model/WRF#1927]
Note : I posted this issue on the forum : [https://forum.mmm.ucar.edu/threads/error-with-tslist-reinitialize-when-nest-begins.14228/#post-35888](https://forum.mmm.ucar.edu/threads/error-with-tslist-reinitialize-when-nest-begins.14228/#post-35888)

**Describe the bug**
I am running a 5-nested domains simulation. Each domain starts a certain time after its parent. Each domain has a ts output location in the center of the domain. At the end of the simulation, in the ts output file of each domain, the time series start approximately at the date when its nest starts instead of when itself starts except for d05 which behaves perfectly since he has no nest inside. If I look at the ts file during the simulation before d02 starts, I notice that d01 ts output are written normally which indicates that the ts file is reinitialized when the nest begins. 

**To Reproduce**
I am running a real case with nested domain starting later than its parent. The nest initialization options input_from_file and fine_input_stream are activated. 

**A possible solution**
I investigated a bit and found a possible solution (in the file attached).
[start_domain.txt](https://github.com/wrf-model/WRF/files/12925549/start_domain.txt)
The ts file is reinitialized when calling *start_domain(parent)* in the subroutine *med_nest_initial*. in this *parent* object the variable *have_calculated_tslocs* is .False.. I reset it to True depending on the timestep value.
It might not be the best solution but at least it indicates where the problem comes from.

Mathieu

**Comment by mathieulandreau** [comment]
I share here a quick modification of the code to allow time series profiles to be computed on a different number of levels between nested domains.
In particular this is useful when using vertical nesting since max_ts_level is currently limited to e_vert(1)-1 which might be lower to e_vert(2)-1 for example
Note that I modified the default value of max_ts_locs to -1 and automatically reset -1 values to e_vert(i)-1 for each domain in module_check_a_mundo 
[tslist_allow_vertical_nesting.txt](https://github.com/wrf-model/WRF/files/12929056/tslist_allow_vertical_nesting.txt)

**Comment by dudhia** [comment]
Thanks for sharing this issue, could you make this into a pull request to make it easier to look at your suggested fix.

**Comment by mathieulandreau** [comment]
Sir, 
This is my first experience on GitHub. I am not sure about how to create a branch to do a pull request. 
Should I create a new branch on my local git repo and try to push it ?
Mathieu

**Comment by dudhia** [comment]
Yes, you fork from our repo, make your changes, push to your fork, and
should get a pull request option.

**Comment by weiwangncar** [comment]
@mathieulandreau Here is a [wiki page](https://github.com/wrf-model/WRF/wiki/Workflow-for-WRF-Code-Modification) that may help you work through the process. Let us know where you have any questions.
