### ISSUE TITLE
the physical meaning of the output variables of WRF-Chem

### ISSUE THREAD

**Issue by jingqian666** [wrf-model/WRF#1966]
Hello, I need help about the physical meaning of the output variables of WRF-Chem.
Do the "TOP" and "BOTTOM" outlined in the picture refer to the top of the atmosphere and the bottom of the atmosphere (earth's surface) respectively?
![Code Screenshot](https://github.com/wrf-model/WRF/assets/155306938/0fbe24e7-9887-4274-a92b-d14e9d9c1fa4)

**Comment by weiwangncar** [comment]
@jingqian666 Please post the request on the Forum: https://forum.mmm.ucar.edu/.
