### ISSUE TITLE
when i use RUC+wudap_lcz ,forrtl: severe (174): SIGSEGV, segmentation fault occurred?

### ISSUE THREAD

**Issue by wbfaded** [wrf-model/WRF#1968]
**Describe the bug**

**To Reproduce**
1. Use compiler and version '....'
2. Use namelist options '....'
3. Output is '....'

**Expected behavior**

**Screenshots**

**Attachments**
If applicable, attach supporting files: namelist.input, rsl.* files, etc.

**Additional context**
Add any other context about the problem here, such as:
   - This used to work with a previous version.
   - The documentation is different from the exhibited behavior.

**Comment by weiwangncar** [comment]
@wbfaded Please report this on the Forum: https://forum.mmm.ucar.edu/
