### ISSUE TITLE
Inaccuracy in the registry.chem file

### ISSUE THREAD

**Issue by encyclica** [wrf-model/WRF#1982]
In the Registry in the 'Registry/registry.chem' file there are such lines:

state    real  setvel_1      ij       misc         1         -       r      "setvel_1"     "dust gravitational settling velocity for size 1"    "m/s"
state    real  setvel_2      ij       misc         1         -       r      "setvel_2"     "dust gravitational settling velocity for size 2"    "m/s"
state    real  setvel_3      ij       misc         1         -       r      "setvel_3"     "dust gravitational settling velocity for size 3"    "m/s"
state    real  setvel_4      ij       misc         1         -       r      "setvel_4"     "dust gravitational settling velocity for size 4"    "m/s"
state    real  setvel_5      ij       misc         1         -       r      "setvel_5"     "effective gravitational settling velocity for total"    "m/s"

All experienced users know that all 5 bins of the dust aerosol are independent.
So description of the "setvel_5" variable ("effective gravitational settling velocity for total") is misleading inexperienced users.

In WRF-Chem in the 'chem/module_gocart_settling.F' source file (where these variables are defined)
all setvel variables are using in the same manner. "setvel_5" variable does not stand out with anything.

I am sure that this line should be changed to:
state    real  setvel_5      ij       misc         1         -       r      "setvel_5"     "dust gravitational settling velocity for size 5"    "m/s"

I think current variant is outdated for a very long time.

**Comment by weiwangncar** [comment]
@jordanschnell Can you comment on this?

**Comment by jordanschnell** [comment]
> @jordanschnell Can you comment on this?

PR submitted: #1985
