### ISSUE TITLE
WRF Moving nest with high-resolution terrain and landuse input cannot be compiled in NCAR HPC (i.e., derecho)  

### ISSUE THREAD

**Issue by smileMchen** [wrf-model/WRF#1984]
WRF Moving Nest with the option to  incorporate high-resolution terrain and landuse input cannot be compiled in derecho. 
 
I am trying to compile following the steps below:

(1) export TERRAIN_AND_LANDUSE=1
(2) module load gcc
(3) /clean -a
(4) ./configure ( choose option 34 and nesting option )
(5) ./compile em_real 

The job failed with errors below:
landread.c:(.text+0x5a3): undefined reference to `xdrstdio_create'
/usr/bin/ld: landread.c:(.text+0x5be): undefined reference to `xdr_int'
/usr/bin/ld: libwrflib.a(landread.o):landread.c:(.text+0x613): more undefined references to `xdr_int' follow

/usr/bin/ld: libwrflib.a(landread.o): in function `tsInitTileSet':
landread.c:(.text+0x646): undefined reference to `xdr_double'
/usr/bin/ld: landread.c:(.text+0x657): undefined reference to `xdr_double'

....
....

**Comment by mgduda** [comment]
Adding `-ltirpc` to the definition of `LIB_EXTERNAL` in the `configure.wrf` file worked for me. I don't know whether this would work on all systems, though.

**Comment by smileMchen** [comment]
@mgduda 
Just tried with this option, and it worked for me, too. Thanks a lot!
