### ISSUE TITLE
Intel LLVM compilers need to build WRF twice to get to install

### ISSUE THREAD

**Issue by HathewayWill** [wrf-model/WRF#1992]
**Describe the bug**
When using the new intel LLVM compilers there is a linker error in the module files that causes WRF to not be built.

If you compile a second time the linkers are found and wrf can be installed.

**To Reproduce**
see shell script in zip file

**Expected behavior**

./compile -j $CPU_HALF_EVEN em_real 2>&1 | tee compile.wrf1.log

should build all the .exe files
however you have to run this command again
./compile -j $CPU_HALF_EVEN em_real 2>&1 | tee compile.wrf2.log
to get all the exe files to build.

**Attachments**
[Intel LLVM.zip](https://github.com/wrf-model/WRF/files/14040655/Intel.LLVM.zip)

**Comment by MicroTed** [comment]
Does it work correctly on the first build if it uses only one thread ( -j 1 )? If so, maybe there is a dependency that isn't correct. (Was there an error about which module it didn't find?)

**Comment by HathewayWill** [comment]
> Does it work correctly on the first build if it uses only one thread ( -j 1 )? If so, maybe there is a dependency that isn't correct. (Was there an error about which module it didn't find?)

I'll have to rebuild it to double check that.  Might be a few days
