### ISSUE TITLE
Pctsum IS ont esqual to 100

### ISSUE THREAD

**Issue by magalietecher** [wrf-model/WRF#2006]
Hi everybody,
I tried to simulate UHI with WRF. I used w2w to generate LCZ geogrid file, have urb_param index filed in it too, the urban parameter table urbparm_lcz filed too and everything went fine until ./wrf.exe.

I have got this error and cannot find a solution :
FATAL CALLED FROM FILE: <stdin> LINE: 2382
pctsum is not equal to 100.
I am novice so i don't understand.. Can someone here help me ?

I attached my files here 
[urbparm_lcz.txt](https://github.com/wrf-model/WRF/files/14195430/urbparm_lcz.txt)
[geo_em.d01.txt](https://github.com/wrf-model/WRF/files/14195431/geo_em.d01.txt)
[namelist.input.txt](https://github.com/wrf-model/WRF/files/14195432/namelist.input.txt)
[rsl.error.0000.txt](https://github.com/wrf-model/WRF/files/14195433/rsl.error.0000.txt)

Thank you in advance

Magalie:

**Comment by weiwangncar** [comment]
@magalietecher Please post this to the Forum: https://forum.mmm.ucar.edu/. Thanks!

**Comment by magalietecher** [comment]
It's done ! Thanks
