### ISSUE TITLE
WPS configure

### ISSUE THREAD

**Issue by ti-sanjid** [wrf-model/WRF#2014]
sanjid@sanjid:~/WRF/WPS$ ./configure
Will use NETCDF in dir: /home/sanjid/WRF/LIBRARIES/netcdf

Error: The $WRF_DIR environment variable was set, but the WRF code at
       /home/sanjid/WRF/LIBRARIES doesn't appear to have been successfully compiled

**Comment by mgduda** [comment]
Please post help requests to the forum at https://forum.mmm.ucar.edu/.
