### ISSUE TITLE
Reassignment of `ash_mass` in `convert_emiss.F` discards previous value

### ISSUE THREAD

**Issue by hcbelgingur** [wrf-model/WRF#2019]
**Describe the bug**
While working with the `chem/convert_emiss.F` code, I noticed in lines 746-747 that `ash_mass` is reassigned with the value of `eh`, which uses the value of `ash_height`.

```
          eh=2600.*(ash_height(i,j)*.0005)**4.1494
          ash_mass(i,j)=eh*1.e9/area
```

The previous value of `ash_mass` is never referred to after the initial `read`, so in effect, this previous value of `ash_mass` gets lost in line 747. 

I suspect line 746 should be `eh=2600.*(ash_mass(i,j)*.0005)**4.1494`, replacing height with mass, or that the constant 2600 should be `ash_mass`. 

I am not a weather scientist (I work as a developer) so I don't have a grasp of the science behind these numbers to decide what the right formula is. But the current code looks a bit odd to me.

**Expected behavior**
I believe the newer `ash_mass` value should depend on its previous value.

**Comment by hcbelgingur** [comment]
Found an article that describes this behavior, it is intended to replace the ash mass value defined by the user.

**Inclusion of Ash and SO2 emissions from volcanic eruptions in WRF-CHEM: development and some applications**
M. Stuefer , S. R. Freitas , G. Grell , P. Webley , S. Peckham , and S. A. McKeen

> While the emissions preprocessor provides total mass and injection height, the latter will most often be overwritten by the user in the namelist, assuming that observations are available that are much closer to the truth.
>
> For historic cases with known injection heights h and duration d of an eruption, the default initialization parameters are then replaced by the total erupted mass m (kg), which is empirically derived from h (m) and d (s) according to Mastinet et al. (2009):
>
> m = ρd (0.0005 h) ^ 4.1494
>
> The variable ρ denotes the assumed magma density of 2600 kg/m^3.
> 
> m increases significantly with injection height. It is evident that the total mass strongly depends on accurate injection heights.

**Comment by weiwangncar** [comment]
@hcbelgingur Thanks for the finding!
