### ISSUE TITLE
WRF - too many input land uses - urgent help required

### ISSUE THREAD

**Issue by hamzanisar5013** [wrf-model/WRF#2024]
I am using Wudapat along with w2w to use LCZ classes. When I use Num_Land_Cat =61 i get following error, while when I use Num_land_cat=41 i get error: too many input land uses:

**for num_land_61**
taskid: 0 hostname: nisarh-VirtualBox
Ntasks in X 1 , ntasks in Y 1
Domain # 1: dx = 6000.000 m
Domain # 2: dx = 2000.000 m
Domain # 3: dx = 666.667 m
REAL_EM V4.5.2 PREPROCESSOR
No git found or not a git repository, git commit version not available.

Parent domain
ids,ide,jds,jde 1 20 1 20
ims,ime,jms,jme -4 25 -4 25
ips,ipe,jps,jpe 1 20 1 20

DYNAMICS OPTION: Eulerian Mass Coordinate
alloc_space_field: domain 1 , 115993600 bytes allocated
Time period # 1 to process = 2022-06-01_00:00:00.
Time period # 2 to process = 2022-06-01_06:00:00.
Time period # 3 to process = 2022-06-01_12:00:00.
Time period # 4 to process = 2022-06-01_18:00:00.
Total analysis times to input = 4.

Domain 1: Current date being processed: 2022-06-01_00:00:00.0000, which is loop # 1 out of 4
configflags%julyr, %julday, %gmt: 2022 152 0.00000000
d01 2022-06-01_00:00:00 Yes, this special data is acceptable to use: OUTPUT FROM METGRID V4.5
d01 2022-06-01_00:00:00 Input data is acceptable to use: met_em.d01.2022-06-01_00:00:00.nc
metgrid input_wrf.F first_date_input = 2022-06-01_00:00:00
metgrid input_wrf.F first_date_nml = 2022-06-01_00:00:00
----------------- ERROR -------------------
namelist : NUM_LAND_CAT = 61
input files : NUM_LAND_CAT = 41 (from geogrid selections).
d01 2022-06-01_00:00:00 ---- ERROR: Mismatch between namelist and wrf input files for dimension NUM_LAND_CAT
NOTE: 1 namelist vs input data inconsistencies found.
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE: LINE: 1298
NOTE: Please check and reset these options

**for num_land_cat= 41**

om year 1765 to 2499
CO2 range = 277.91300000000001 579.26400000000001 ppm
N2O range = 274.37200000000001 359.79800000000000 ppb
CH4 range = 738.98599999999999 997.31100000000004 ppb
CFC11 range = 0.0000000000000000 1.4000000000000000E-002 ppt
CFC12 range = 0.0000000000000000 2.8809999999999998 ppt
Normal ending of CAMtr_volume_mixing_ratio file
GHG annual values from CAM trace gas file
Year = 2022 , Julian day = 152
CO2 = 4.2009431165911494E-004 volume mixing ratio
N2O = 3.3358831037842025E-007 volume mixing ratio
CH4 = 1.9316951285536446E-006 volume mixing ratio
CFC11 = 2.1284297601007446E-010 volume mixing ratio
CFC12 = 4.8584546024729978E-010 volume mixing ratio
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND 61 CATEGORIES 2 SEASONS WATER CATEGORY = 17 SNOW CATEGORY = 15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND 20 CATEGORIES
INPUT SOIL TEXTURE CLASSIFICATION = STAS
SOIL TEXTURE CLASSIFICATION = STAS FOUND 19 CATEGORIES
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
Sample of Urban settings
TSURFACE0_URB 293.073639
TDEEP0_URB 287.267975
IVGTYP 1
TR_URB2D 293.073639
TB_URB2D 293.073639
TG_URB2D 293.073639
TC_URB2D 293.073639
QC_URB2D 9.99999978E-03
XXXR_URB2D 0.00000000
SH_URB2D 0.00000000
LH_URB2D 0.00000000
G_URB2D 0.00000000
RN_URB2D 0.00000000
TS_URB2D 293.073639
LF_AC_URB3D 0.00000000
SF_AC_URB3D 0.00000000
CM_AC_URB3D 0.00000000
SFVENT_URB3D 0.00000000
LFVENT_URB3D 0.00000000
FRC_URB2D 0.00000000
UTYPE_URB2D 0
I 2 J 19
num_urban_hi 15
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
USING DEFAULT URBAN MORPHOLOGY
Timing for Writing wrfout_d02_2022-06-01_00:00:00 for domain 2: 0.12228 elapsed seconds
Tile Strategy is not specified. Assuming 1D-Y
WRF TILE 1 IS 1 IE 28 JS 1 JE 28
WRF NUMBER OF TILES = 1
-------------- FATAL CALLED ---------------
**FATAL CALLED FROM FILE: LINE: 2419**
Warning: too many input landuse types

**Comment by weiwangncar** [comment]
@hamzanisar5013 Please post this on the Forum: https://forum.mmm.ucar.edu/. Thanks!
