### ISSUE TITLE
convert_emiss.exe, error occurs for domain 2

### ISSUE THREAD

**Issue by jianjun5212** [wrf-model/WRF#2027]
Hi 
the files of g1-gocartBG.bin, g2-gocartBG.bin, g1-ab.bin, g2-ab.bin, g1-bb.bin,g2-bb.bin were generated using PREP-CHEM-SRC. Following the document, the wrfchem**d01 are successfully generated using convert_emiss.exe, but the errors occurred when processing the domain 2 as shown below:

*********************************************************************
* PROGRAM:WRF-Chem V4.5.2 MODEL
git commit a8eb846859cb39d0acfd1d3297ea9992ce66424a 1 file changed, 2 insertions(+), 1 deletion(-)
* *
* PLEASE REPORT ANY BUGS TO WRF-Chem HELP at *
* *
* [wrfchemhelp.gsd@noaa.gov](mailto:wrfchemhelp.gsd@noaa.gov) *
* *
*********************************************************************
start_domain_em: numgas = 50
past opening wrfinput_d01

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Any suggestion please.
Thanks

**Comment by weiwangncar** [comment]
@jianjun5212 Please post this on the Forum: https://forum.mmm.ucar.edu/. Thanks.
