### ISSUE TITLE
WRFDA PLUS V4.6.0 fails with intel llvm compilers.  

### ISSUE THREAD

**Issue by HathewayWill** [wrf-model/WRF#2048]
@islas @mgduda 

**Describe the bug**
During the installation of WRFPLUS v4.6.0 a massive memory usage occurs that happens only with the intel llvm compilers and not with GNU.

I have attached relevant log files.

[configure.log](https://github.com/wrf-model/WRF/files/15307708/configure.log)
[configure.wrf.txt](https://github.com/wrf-model/WRF/files/15307709/configure.wrf.txt)

[wrfplus1.compile.log](https://github.com/wrf-model/WRF/files/15307712/wrfplus1.compile.log)

**To Reproduce**

```
cd "${WRF_FOLDER}"/Downloads
	mkdir "${WRF_FOLDER}"/WRFPLUS
	tar -xvzf WRF-${WRF_VERSION}.tar.gz -C "${WRF_FOLDER}"/WRFPLUS

	# If statment for changing folder name
	if [ -d ""${WRF_FOLDER}"/WRFPLUS/WRF" ]; then
		mv -f "${WRF_FOLDER}"/WRFPLUS/WRF "${WRF_FOLDER}"/WRFPLUS/WRFV${WRF_VERSION}
	fi

	cd "${WRF_FOLDER}"/WRFPLUS/WRFV${WRF_VERSION}
	mv * "${WRF_FOLDER}"/WRFPLUS
	cd "${WRF_FOLDER}"/WRFPLUS
	rm -rf WRFV${WRF_VERSION}/
	export NETCDF=$DIR/NETCDF
	export HDF5=$DIR/grib2
	export LD_LIBRARY_PATH=$DIR/grib2/lib:$LD_LIBRARY_PATH
	./clean -a

	if [ ${auto_config} -eq 1 ]; then
		echo 40 | ./configure wrfplus 2>&1 | tee configure.log #Option 40 for intel and distribunted memory
	else
		./configure wrfplus 2>&1 | tee configure.log #Option 40 for intel and distribunted memory
	fi
	echo " "

	sed -i '136s|mpif90 -f90=$(SFC)|mpiifx|g' "${WRF_FOLDER}"/WRFPLUS/configure.wrf
	sed -i '137s|mpicc -cc=$(SCC)|mpiicx|g' "${WRF_FOLDER}"/WRFPLUS/configure.wrf


	./compile -j $CPU_HALF_EVEN wrfplus 2>&1 | tee wrfplus1.compile.log
```

**Expected behavior**
No Memory leak

**Screenshots**

![20240514_062846](https://github.com/wrf-model/WRF/assets/118180342/9f8d43ad-d7e4-45b1-a086-78ce1b32c3e8)
![20240514_062854](https://github.com/wrf-model/WRF/assets/118180342/b1601caf-cd4a-4b98-8083-b105b14e6ad0)

**Comment by islas** [comment]
I'd caution to label this as a "memory leak" as that has technical implications of the underlying root cause.  It is a memory usage issue with large files when compiling with the new oneAPI compilers, however.

Consider compiling with a _very limited_ number of threads (some files require upwards of 25GB individually) until a future fix is implemented.

**Comment by Jeremy-Benik** [comment]
I don't know if this has been resolved, but I have 128gb of RAM I can use to compile. Would you want me to try to compile WRFDA with intel compilers using that? I would just use one thread when compiling (./compile 4dvar >& compile.log &)

**Comment by HathewayWill** [comment]
> Definitely try just one thread. It will be much slower but it should compile at the very least.

Tried one thread and it worked, opened 4 posts on the wrf forum about this and my tests.  I'll leave it to you to let me know if you need me to do more testing or create pull requests.

Here are the links:

https://forum.mmm.ucar.edu/threads/wrf-chem-w-kpp-wrf-chemda-v4-6-0-intel-llvm-compilers.17266/

https://forum.mmm.ucar.edu/threads/wrf-arw-v4-6-0-intel-llvm-compilers.17265/

https://forum.mmm.ucar.edu/threads/wrf-4dvar-v4-6-0-intel-llvm-compilers.17264/

https://forum.mmm.ucar.edu/threads/wrf-plus-4dvar-v4-6-0-intel-llvm-compilers.17263/

**Comment by HathewayWill** [comment]
Closing issue and opening again with new information
