### ISSUE TITLE
Include paths are missing in source code compilation commands in phys/

### ISSUE THREAD

**Issue by wadudmiah** [wrf-model/WRF#2050]
When I execute the `./compile -j 4 em_real` command, it fails to build source code in the `phys/` subdirectory. When I see what commands make will execute, it shows:

```
$ make -i -n -r -j 8 non_nmm  
[configure.wrf.txt](https://github.com/wrf-model/WRF/files/15388703/configure.wrf.txt)

mpiifort -o module_cam_support.o -c -O3 -ip -fp-model precise -w -ftz -align all -fno-alias -FR -convert big_endian     -real-size `expr 8 \* 4` -i4  module_cam_support.f90
```
As you can see, the include paths are all missing and subsequently, the compilation of `module_cam_support.f90` fails. The `$INCLUDE_MODULES` variable from `configure.wrf` should be in the compilation command. Can someone please suggest how to remedy this error? I have attached my configure.wrf (named configure.wrf.txt so I can attached it to this ticket). 

Thanks in advance.

**Comment by wadudmiah** [comment]
[configure.wrf.txt](https://github.com/wrf-model/WRF/files/15388724/configure.wrf.txt)

**Comment by weiwangncar** [comment]
@wadudmiah Please report this and seek for help in the Forum: https://forum.mmm.ucar.edu/
