### ISSUE TITLE
WRF App

### ISSUE THREAD

**Issue by Wasimwani1** [wrf-model/WRF#2051]
Hello 

Request help in creating a WRF app for testing i need to push the app on a cloud environment and test it there.

How can i pull the required code. Can anyone help with steps.

Regards
Wasim

**Comment by weiwangncar** [comment]
This request should go to the forum too. But try either download the tar file from the github page, or run git like 
git clone --recurse-submodules https://github.com/wrf-model/WRF.git WRF

**Comment by weiwangncar** [comment]
@Wasimwani1 Take a look at the Users' Guide and learn to compile and run the model.
