### ISSUE TITLE
WRF run error: too many input landuse types

### ISSUE THREAD

**Issue by Yegengjiao** [wrf-model/WRF#2066]
I plan to run a test with CGLC-MODIS-LCZ_100m data. The WPS 4.3.1 process and ./real.exe are successful, but the ./wrf.exe failed with error:
.............................................
d01 2019-08-08_12:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain        1:    1.70144 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     17 JS      1 JE     17
WRF NUMBER OF TILES =   1
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    2419
Warning: too many input landuse types
-------------------------------------------

I have tried with WRF 4.3.1, WRF 4.4.2 and WRF 4.6. The same issue occurred. Please help me！

**Comment by weiwangncar** [comment]
@Yegengjiao Please report this on the Forum: https://forum.mmm.ucar.edu/. Thanks.

**Comment by smileMchen** [comment]
This error has been corrected in WRF version newer than v4.4.2. Please try WRFv4.5 or v4.6. Let us know if you still have this issue.
