### ISSUE TITLE
On the problem of running mpi parallel computing.

### ISSUE THREAD

**Issue by xiongyuup** [wrf-model/WRF#2076]
After installing WRF, I encountered the following problems in parallel computing. The first error occurred at the beginning, and the second error occurred later. Have you ever encountered it?
1、
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(433).................:
MPID_Init(176)........................: channel initialization failed
MPIDI_CH3_Init(70)....................:
MPID_nem_init(238)....................:
MPIDI_CH3I_Seg_commit(366)............:
MPIU_SHMW_Hnd_deserialize(324)........:
MPIU_SHMW_Seg_open(865)...............:
MPIU_SHMW_Seg_create_attach_templ(635): open failed - Permission denied

2、
root@dell-pc:/home/dell/Destop/xiongyu/WRF/Build_WRF/WRF-4.1.2/run# mpirun -np 64 ./wrf.exe
[proxy:0:0@dell-pc] HYDU_sock_write (./utils/sock/sock.c:290): write error (Broken pipe)
[proxy:0:0@dell-pc] send_cmd_downstream (./pm/pmiserv/pmip_pmi_v1.c:95): error writing PMI line
[proxy:0:0@dell-pc] fn_get (./pm/pmiserv/pmip_pmi_v1.c:442): error sending command downstream
[proxy:0:0@dell-pc] pmi_cb (./pm/pmiserv/pmip_cb.c:327): PMI handler returned error
[proxy:0:0@dell-pc] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:0@dell-pc] main (./pm/pmiserv/pmip.c:206): demux engine error waiting for event
[mpiexec@dell-pc] control_cb (./pm/pmiserv/pmiserv_cb.c:202): assert (!closed) failed
[mpiexec@dell-pc] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@dell-pc] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:197): error waiting for event
[mpiexec@dell-pc] main (./ui/mpich/mpiexec.c:331): process manager error waiting for completion

**Comment by mgduda** [comment]
@xiongyuup Can you please post your question on the WRF/MPAS support forum at [https://forum.mmm.ucar.edu](https://forum.mmm.ucar.edu)?
