### ISSUE TITLE
Version of NOAH LSM 

### ISSUE THREAD

**Issue by shaider2** [wrf-model/WRF#2080]
Hi,
 I am a graduate student researching land use and atmosphere interaction. I am using WRF 4.5.2 version for my research. I ma using Noah LSM physics parameterization. However, I was looking for the version of Noah LSM used in WRF 4.5.2. It will be a great help if you can provide some insights to it.

**Comment by weiwangncar** [comment]
See discussion in https://github.com/wrf-model/WRF/issues/2079.
Also please post this in the [forum](https://forum.mmm.ucar.edu/) rather than here.
