### ISSUE TITLE
when finished installation ,bash: ./compile: Unable to execute: required file not found

### ISSUE THREAD

**Issue by dafage66** [wrf-model/WRF#2085]
what seems to be the problem?
![截图 2024-08-05 13-04-38](https://github.com/user-attachments/assets/3953ea55-4750-4b34-99c6-c3ade8cde907)
![截图 2024-08-05 12-12-57](https://github.com/user-attachments/assets/1060e314-4e72-4ec1-89a3-e060f45dac8d)
![截图 2024-08-05 13-03-44](https://github.com/user-attachments/assets/c7576cef-f695-44fc-894e-4758495d41f1)

**Comment by weiwangncar** [comment]
@dafage66 Please post this in the Forum: https://forum.mmm.ucar.edu/. Note that compile is a script which is located in the top WRF directory.
