### ISSUE TITLE
wrfv4.6.0 crush without error but with 'Domain average of dpsdt, dmudt NAN'

### ISSUE THREAD

**Issue by OMGTaylor0814** [wrf-model/WRF#2094]
I am encountering an issue where WRF crashes at a specific time. I would appreciate any assistance you can provide.

I have installed the latest WRF v4.6.0 model on my Linux server to utilize new functions for wind farms. After successfully running an earlier case, I read literature and planned sensitivity tests for Typhoon 'Infa', modifying some options and adjusting area ranges.

I created the initial and lateral data from fnl data (ds083.3) and ran WRF. However, it consistently crashes at a certain point without clear error messages. Upon investigation, I discovered NAN values in the final calculation stage, and I currently don’t know how to resolve this issue.

Here is the “NaN value” part:
![nan](https://github.com/user-attachments/assets/20d2bcb1-662f-4be9-b725-5cf2ed3fd60c)

I have attached my namelist files, including those for both successful and failed runs, along with the rsl.error files in this url:
(https://forum.mmm.ucar.edu/threads/crush-with-domain-average-of-dpsdt-dmudt-nan.18548/)

Additionally, I have uploaded the shell script files for processing the WPS and WRF components, which may be helpful.

Thank you in advance.

**Comment by weiwangncar** [comment]
@OMGTaylor0814 Your post is appropriate for the User Support Forum. Please wait for reply there. In the meantime, try to make small changes between the runs with and without crash to identify the change that may be the cause and report it in the Forum.
