### ISSUE TITLE
add the support of seperate netcdf and netcdf-fortran path

### ISSUE THREAD

**Issue by jiangleads** [wrf-model/WRF#2102]
Hello, I would like to install the wrf using seperate netcdf-c and netcdf-fortran library. However, according to the configuration process I used. I have to add the flag -lnetcdff and the path of netcdf-fortran to the configure.wrf manually. As it is known, the netcdf-c and netcdf-fortran are two seperately libraries after the verson of netcdf-4.1.1 or so. It's less likely for us to use an ancient verson of netcdf in order to avoid add the NETCDF-fortran path to configuration file manually. 
So, my urge is that could you please to add  support of netcdf-fortran environmental value path? 
BTW, The issue exists AT LEAST 10 years ago. Hope for solve the problems eventually. 
THANK YOU.
Apologize for if it disturbs you for mismatched area of question, since I am not familar with how to add issue in github correctly.

**Comment by weiwangncar** [comment]
@jiangleads Please post this request to the Forum: https://forum.mmm.ucar.edu/. Thanks.
