### ISSUE TITLE
WRF-Chem 4.6 compile with KPP on derecho failure on write_decomp.exe

### ISSUE THREAD

**Issue by SichengWu1991** [wrf-model/WRF#2117]
**Describe the bug**
While compiling WRF-Chem with KPP, it seems that write_decomp.exe is not properly generated. While running it complains about instruction error. The error does not happen at 4.4.2 using configure option 15

```
./write_decomp.exe

Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, MOVBE, POPCNT, AVX, F16C, FMA, BMI, LZCNT and AVX2 instructions.
```

**To Reproduce**
1. Compiler setting using either 15 and 78.

**Comment by weiwangncar** [comment]
@SichengWu1991 Trying to do 'module load intel-classic' before choosing the compiler options. Do 'clean -a' first too. If you still have problems, please post it on the support Forum: https://forum.mmm.ucar.edu/
