### ISSUE TITLE
Problem in Data assimilation of IASI radiance 

### ISSUE THREAD

**Issue by melani71** [wrf-model/WRF#2123]
I am trying to assimilate IASI radiance data obtained from NCEP GDAS Satellite Data server (NCAR RDA Dataset ds735.0 that can be directly assimilated with WRFDA) into WRF-ARW 4.6.0, using RTTOV 12.3.

However, the 3DVAR process stopped at the module "rttov_check_profiles.F90", as described in the rsl.error.0000 log file, with the reason "invalid zenith angle".
I attached the log files (rs.error.0000, rsl.out.0000) and the namelist.input file.

In the subroutine that reads the IASI data (da_read_obs_bufriasi.inc) there is a check that transforms the satellite zenith angle in negative; infact, if (ifov <= 60) sat_zenang = -sat_zenang.
Thus, positive angles are transformed in negative ones and these values do not pass the zenith angle check in the subroutine rttov_check_profiles.F90, which works only with positive angles.

The Metop-IASI observation files (either obtained from NCEP and operationally by EUMETSAT providers) generally contain both negative and positive satellite zenith angles. Currently, it is not then possible to assimilate IASI radiance data.

[namelist.input.txt](https://github.com/user-attachments/files/17557518/namelist.input.txt)
[rsl.error.0000.txt](https://github.com/user-attachments/files/17557519/rsl.error.0000.txt)
[rsl.out.0000.txt](https://github.com/user-attachments/files/17557520/rsl.out.0000.txt)

**Comment by melani71** [comment]
Unfortunately, I already posted this issue on the WRF & MPAS-A FORUM this summer, but I haven't received a response yet. I think it's a bug that needs to be fixed between the subroutine that handles the IASI data and RTTOV.

Do you have any contact people to ask? Thanks!

**Comment by weiwangncar** [comment]
@liujake @mos3r3n I wonder if you can help here.
