### ISSUE TITLE
jasper installation error

### ISSUE THREAD

**Issue by DLDRSB** [wrf-model/WRF#2127]
hello. I was just trying to compile wrf using Intel compiler. Everything went well until I got to Jasper. When compiling, it shows me this error:
Making all in src
make[1]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src'
Making all in libjasper
make[2]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper'
Making all in include
make[3]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include'
Making all in jasper
make[4]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include/jasper'
make all-am
make[5]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include/jasper'
make[5]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include/jasper'
make[4]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include/jasper'
make[4]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include'
make[3]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/include'
Making all in base
make[3]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/base'
/bin/bash ../../../libtool --tag=CC --mode=compile icx -DHAVE_CONFIG_H -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -O2 -std=c11 -pedantic -Wall -Wno-unused -pedantic-errors -MT jas_cm.lo -MD -MP -MF .deps/jas_cm.Tpo -c -o jas_cm.lo jas_cm.c
libtool: compile: icx -DHAVE_CONFIG_H -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -O2 -std=c11 -pedantic -Wall -Wno-unused -pedantic-errors -MT jas_cm.lo -MD -MP -MF .deps/jas_cm.Tpo -c jas_cm.c -fPIC -DPIC -o .libs/jas_cm.o
In file included from jas_cm.c:77:
../../../src/libjasper/include/jasper/jas_math.h:143:15: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
143 | assert(((-1) << 1) == -2);
| ~~~~ ^
/usr/include/assert.h:109:7: note: expanded from macro 'assert'
109 | ((expr) \
| ^~~~
In file included from jas_cm.c:77:
../../../src/libjasper/include/jasper/jas_math.h:169:39: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
169 | assert(((JAS_CAST(int_fast32_t, -1)) << 1) == JAS_CAST(int_fast32_t, -2));
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/assert.h:109:7: note: expanded from macro 'assert'
109 | ((expr) \
| ^~~~
jas_cm.c:175:43: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
175 | static jas_cmprof_t *jas_cmprof_createsycc()
| ^
| void
jas_cm.c:312:39: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
312 | static jas_cmprof_t *jas_cmprof_create()
| ^
| void
jas_cm.c:594:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
594 | static jas_cmpxformseq_t *jas_cmpxformseq_create()
| ^
| void
jas_cm.c:728:44: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
728 | static jas_cmpxform_t *jas_cmpxform_create0()
| ^
| void
jas_cm.c:757:50: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
757 | static jas_cmpxform_t *jas_cmpxform_createshapmat()
| ^
| void
2 warnings and 5 errors generated.
make[3]: *** [Makefile:473: jas_cm.lo] Error 1
make[3]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper/base'
make[2]: *** [Makefile:588: all-recursive] Error 1
make[2]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src/libjasper'
make[1]: *** [Makefile:426: all-recursive] Error 1
make[1]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.29/src'
make: *** [Makefile:469: all-recursive] Error 1

i have also attatched the config.log file below.
how should i overcome this?
 
Attachments
[config.log](https://github.com/user-attachments/files/17606401/config.log)

**Comment by DLDRSB** [comment]
i tried using jasper version 1.900.1 and it shows this error after configuring
Making all in src
make[1]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src'
Making all in libjasper
make[2]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper'
Making all in include
make[3]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include'
Making all in jasper
make[4]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include/jasper'
make all-am
make[5]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include/jasper'
make[5]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include/jasper'
make[4]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include/jasper'
make[4]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include'
make[3]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/include'
Making all in base
make[3]: Entering directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/base'
if /bin/bash ../../../libtool --tag=CC --mode=compile icx -DHAVE_CONFIG_H -I. -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -g -O2 -MT jas_cm.lo -MD -MP -MF ".deps/jas_cm.Tpo" -c -o jas_cm.lo jas_cm.c; \
then mv -f ".deps/jas_cm.Tpo" ".deps/jas_cm.Plo"; else rm -f ".deps/jas_cm.Tpo"; exit 1; fi
icx -DHAVE_CONFIG_H -I. -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -g -O2 -MT jas_cm.lo -MD -MP -MF .deps/jas_cm.Tpo -c jas_cm.c -o jas_cm.o
if /bin/bash ../../../libtool --tag=CC --mode=compile icx -DHAVE_CONFIG_H -I. -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -g -O2 -MT jas_debug.lo -MD -MP -MF ".deps/jas_debug.Tpo" -c -o jas_debug.lo jas_debug.c; \
then mv -f ".deps/jas_debug.Tpo" ".deps/jas_debug.Plo"; else rm -f ".deps/jas_debug.Tpo"; exit 1; fi
icx -DHAVE_CONFIG_H -I. -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -g -O2 -MT jas_debug.lo -MD -MP -MF .deps/jas_debug.Tpo -c jas_debug.c -o jas_debug.o
jas_debug.c:128:25: warning: format specifies type 'unsigned int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
128 | fprintf(out, "%04x:", i);
| ~~~~ ^
| %04zx
1 warning generated.
if /bin/bash ../../../libtool --tag=CC --mode=compile icx -DHAVE_CONFIG_H -I. -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -g -O2 -MT jas_getopt.lo -MD -MP -MF ".deps/jas_getopt.Tpo" -c -o jas_getopt.lo jas_getopt.c; \
then mv -f ".deps/jas_getopt.Tpo" ".deps/jas_getopt.Plo"; else rm -f ".deps/jas_getopt.Tpo"; exit 1; fi
icx -DHAVE_CONFIG_H -I. -I. -I../../../src/libjasper/include/jasper -I../../../src/libjasper/include -I/home/rhyme/Documents/LIBRARIES/include -I/home/rhyme/Documents/LIBRARIES/NETCDF/include -I/home/rhyme/Documents/LIBRARIES/grib2/include -g -O2 -MT jas_getopt.lo -MD -MP -MF .deps/jas_getopt.Tpo -c jas_getopt.c -o jas_getopt.o
jas_getopt.c:129:7: error: call to undeclared function 'jas_eprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
129 | jas_eprintf("unknown long option %s\n", s);
| ^
jas_getopt.c:140:7: error: call to undeclared function 'jas_eprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
140 | jas_eprintf("unknown short option %s\n", s);
| ^
jas_getopt.c:151:7: error: call to undeclared function 'jas_eprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
151 | jas_eprintf("missing argument for option %s\n", s);
| ^
3 errors generated.
make[3]: *** [Makefile:349: jas_getopt.lo] Error 1
make[3]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper/base'
make[2]: *** [Makefile:404: all-recursive] Error 1
make[2]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src/libjasper'
make[1]: *** [Makefile:290: all-recursive] Error 1
make[1]: Leaving directory '/home/rhyme/Documents/LIBRARIES/jasper-1.900.1/src'
make: *** [Makefile:319: all-recursive] Error 1
 
[config.log](https://github.com/user-attachments/files/17606404/config.log)

**Comment by weiwangncar** [comment]
@DLDRSB You can build WPS using code for these libraries included in the tar file. Simply do './configure --build-grib2-libs'. See https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/compiling.html#configure-wps. For further questions, please post it on the Forum: https://forum.mmm.ucar.edu/
