### ISSUE TITLE
segmentation fault occurred

### ISSUE THREAD

**Issue by DLDRSB** [wrf-model/WRF#2129]
I just recently completed compiling WPS and WRF using Intel's latest compilers. WPS and real.exe seems to run fine but wrf.exe encounters some errors.
Here are my libraries installed.
ulimit -s unlimited
export CC=icx
export CXX=icpx
export FC=ifx
export F77=ifx
export F90=ifx
export MPIFC=mpiifx
export MPIF77=mpiifx
export MPIF90=mpiifx
export MPICC=mpiicx
export MPICXX=mpiicpc
export CFLAGS="-fPIC -fPIE -O3 -Wno-implicit-function-declaration -Wno-incompatible-function-pointer-types -Wno-unused-command-line-argument"
export FFLAGS="-m64"
export FCFLAGS="-m64"
export HDF5=/home/rhyme/WRF_FOLDER/Libs/grib2
export PATH=/home/rhyme/WRF_FOLDER/Libs/bin:$PATH
export PHDF5=/home/rhyme/WRF_FOLDER/Libs/grib2
export LD_LIBRARY_PATH=/home/rhyme/WRF_FOLDER/Libs/NETCDF/lib:$LD_LIBRARY_PATH
export PNETCDF=/home/rhyme/WRF_FOLDER/Libs/grib2
export PATH=/home/rhyme/WRF_FOLDER/Libs/NETCDF/bin:$PATH
export NETCDF=/home/rhyme/WRF_FOLDER/Libs/NETCDF
export CPPFLAGS="-I/home/rhyme/WRF_FOLDER/Libs/NETCDF/include -I/home/rhyme/WRF_FOLDER/Libs/grib2/include"
export LDFLAGS="-L/home/rhyme/WRF_FOLDER/Libs/NETCDF/lib -L/home/rhyme/WRF_FOLDER/Libs/grib2/lib"
export LIBS="-lnetcdf -lpnetcdf -lcurl -lhdf5_hl -lhdf5 -lz -lm -ldl -lgcc"
export JASPERLIB=/home/rhyme/WRF_FOLDER/Libs/grib2/lib
export JASPERINC=/home/rhyme/WRF_FOLDER/Libs/grib2/include
export WRFIO_NCD_LARGE_FILE_SUPPORT=1
export WRF_DIR=/home/rhyme/WRF_FOLDER/WRFV4.6.1
echo $LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/rhyme/WRF_FOLDER/Libs/grib2/lib"

. /opt/intel/oneapi/setvars.sh
clear

[configure.wrf.txt](https://github.com/user-attachments/files/17654512/configure.wrf.txt)
[configure(1).wps.txt](https://github.com/user-attachments/files/17654529/configure.1.wps.txt)
[namelist.input.txt](https://github.com/user-attachments/files/17654532/namelist.input.txt)
[rsl.out.0000.txt](https://github.com/user-attachments/files/17654535/rsl.out.0000.txt)
[rsl.error(1).0000.txt](https://github.com/user-attachments/files/17654536/rsl.error.1.0000.txt)

**Comment by weiwangncar** [comment]
@DLDRSB Please post this on the Forum: https://forum.mmm.ucar.edu/. It is unlikely the seg fault error is related to compilers.

**Comment by DLDRSB** [comment]
@weiwangncar I've ran tests for the compilers and everything went well.
