### ISSUE TITLE
WRFV4.6.1   real.exe  problem, 

### ISSUE THREAD

**Issue by wancheng22** [wrf-model/WRF#2140]
namelist.input是正确的
![image](https://github.com/user-attachments/assets/7dd5d865-daaf-4809-9be9-331cf523b4bc)
met_em.d*也是正确的
![image](https://github.com/user-attachments/assets/59f96e32-43ed-4dc5-b2b0-d73bacae5ee0)
但是运行real.exe
![image](https://github.com/user-attachments/assets/0ae5d5bc-8340-4628-821e-ebae567dc87f)

helpme please  thanks a lot

**Comment by weiwangncar** [comment]
@wancheng22 Please post your problem to the User Forum: https://forum.mmm.ucar.edu/ in English.
