### ISSUE TITLE
Issues to running real.exe and wrf.exe MacOS

### ISSUE THREAD

**Issue by rcrafa179** [wrf-model/WRF#2141]
Hi everyone,

After a lot of try and errors I could finally compile WRF and WPS without any major issue for MacOS with M3 pro chip. I'm trying to run the Matthew hurricane example, but when I run real.exe it's fails, even using the examples that the tutorial gives you. Also I recompiled the program, the compile was perfect and the program stills failing. I'm using MPICH installed by homebrew, the rest of libraries are installed as the tutorial. Any idea what to do here?

`taskid: 0 hostname: MacBook-Pro-2.local
 ./module_io_quilt_old.F        2931 T
 Ntasks in X            2 , ntasks in Y            2
*************************************
Configuring physics suite 'conus'

         mp_physics:      8
         cu_physics:      6
      ra_lw_physics:      4
      ra_sw_physics:      4
     bl_pbl_physics:      2
  sf_sfclay_physics:      2
 sf_surface_physics:      2
*************************************
  Domain # 1: dx = 27000.000 m
REAL_EM V4.6.1 PREPROCESSOR
git commit d66e442fccc04111067e29274c9f9eaccc3cef28 1 file changed, 3 insertions(+), 3 deletions(-)
 *************************************
 Parent domain
 ids,ide,jds,jde            1          91           1         100
 ims,ime,jms,jme           -4          52          -4          57
 ips,ipe,jps,jpe            1          45           1          50
 *************************************
DYNAMICS OPTION: Eulerian Mass Coordinate
   alloc_space_field: domain            1 ,             136755772  bytes allocated
*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[MacBook-Pro-2.local:30475] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!`

**Comment by weiwangncar** [comment]
@rcrafa179 Please report your difficulties on the User Forum: https://forum.mmm.ucar.edu/. Thanks!
