### ISSUE TITLE
Add a README for CRTM coefficients

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#330]
Associated with PR #329, provide a README with information for users. For example, something like this ...

These coefficient files are binary and cannot be tracked by git and will be put in WRFDA website for download from the release 4.0.  A copy will also be made available under ~wrfhelp on the NCAR cheyenne supercomputer (for internal use). The full set of CRTM coefficient files can be downloaded from the official CRTM ftp site http://ftp.emc.ncep.noaa.gov/jcsda/CRTM/.

**Comment by davegill** [comment]
@liujake @jjguerrette 
Folks,
Could you look at addressing this

**Comment by jjguerrette** [comment]
@davegill @liujake 
I made a first attempt in this branch:
https://github.com/jjguerrette/WRF/tree/doc/crtm_readme

The file is located at doc/README.crtm.  Should I submit a PR?  FYI, I will be M.I.A. (PTO) the next two weeks.

**Comment by davegill** [comment]
@liujake @jjguerrette 
JJ,
This looks great. Yes issue a PR. Include the line that says something like "addresses issue #330", and it will close this issue. 

Put this as a new feature, so base your PR off of the develop branch. No problem at all to get back to this PR in a couple of weeks.

**Comment by davegill** [comment]
Fixed by "README for CRTM coefficient procedure #662"
