### ISSUE TITLE
v4.0 WRF DA does not compile

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#595]
The v4_metgrid variable is used inside share/input_wrf.F. The variable is not in the Registry.EM_COMMON_var.

Solution
1. Add v4_metgrid to DA Registry
2. ifdef around usage in share/input_wrf.F

**Comment by flytohighhigh** [comment]
> The v4_metgrid variable is used inside share/input_wrf.F. The variable is not in the Registry.EM_COMMON_var.
> 
> Solution
> 
> 1. Add v4_metgrid to DA Registry
> 2. ifdef around usage in share/input_wrf.F

sorry to bother you. I really want to know how to  add v4_metgrid to DA Registry

**Comment by weiwangncar** [comment]
@flytohighhigh Please post this on the Forum: https://forum.mmm.ucar.edu/. Thanks.

**Comment by flytohighhigh** [comment]
> @flytohighhigh Please post this on the Forum: https://forum.mmm.ucar.edu/. Thanks

I posted this question about WRFDA and v4_metgrid on the Forum you mentioned.
