### ISSUE TITLE
V4 REAL rejecting OBSGRID analyses

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#600]
From WRF Forum

V4 REAL rejecting OBSGRID analyses
Post  by RCarpenter » Wed Jun 20, 2018 2:59 pm

I am using the OBSGRID metoa_em files as input to REAL. In v4, I get this error:

d01 2018-06-20_12:00:00 This input data is not V4: OUTPUT FROM OBSGRID

It appears that REAL is rejecting any METGRID netCDF files that don't have "V4" in the TITLE attribute.

As a workaround, I am setting force_use_old_data=T in the time_control record of the namelist.input file.

So, is this a bug or a feature?

**Comment by davegill** [comment]
@kkeene44 @smileMchen 
Do we have any obsgrid data laying around that we can test?

**Comment by weiwangncar** [comment]
I believe the solution we chose before the release is to change the version number in obsgrid output. Can you confirm this is done to the obsgrid program?

**Comment by kkeene44** [comment]
@weiwangncar The obsgrid program assigns the title "OUTPUT FROM OBSGRID" to the file. We can add the version number, but we need to add a test to determine the version of WPS that the met_em* files are coming from.  Someone may be using an older version of WPS before running obsgrid.

**Comment by kkeene44** [comment]
@davegill Thanks. I'll create a PR for this correction.

**Comment by davegill** [comment]
@kkeene44 

You can reference this issue from the obsgrid repo. Take a look at this site:

https://blog.github.com/2011-10-21-github-secrets/

<img width="686" alt="screen shot 2018-10-11 at 12 30 33 pm" src="https://user-images.githubusercontent.com/12666234/46825749-99223100-cd51-11e8-908d-3e39953dd49a.png">
