### ISSUE TITLE
compile emi_conv fails after v4.0

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#601]
The convert_emiss.exe is not able to compile with the following error message:

This option is not recognized: emi_conv

Likely solution is to put in an IF test in the compile script, something like:
```
 61   else if   ( "$a" ==  "em_real" ) then
 62     set arglist = ( $arglist $a )
 63     set ZAP = ( main/wrf.exe main/real.exe main/ndown.exe main/tc.exe )
```
The ZAP part should explicitly include the executables that will be generated (so that they are explictly removed during the build).

**Comment by sanjeevdwivedi2** [comment]
Dear Davegill
Thanks for the comments
actually, I added
"$a"= "emi_conv"
then, It ran and built the exe file. But no success message came.
