### ISSUE TITLE
Swap ";" for "!" in README.namelist and examples.namelist

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#616]
To allow users to easily cut and paste, swap the ";" characters (in the README.namelist and examples.namelist files) for the standard comment demarkation character "!".  

For example:

test/em_real/examples.namelist
```
** Optional gravitational settling of fog/cloud droplets (MYNN PBL only)

 grav_settling                       = 1,       ; default 0
```

run/README.namelist
```
For example, assuming the job is 10 nodes with 36 cores per node. To have 1 I/O processor
per node, set

&pio_control
 usepio = .true.,  ; turn PIO on
 pioprocs = 10,    ; Number of processors to do IO
 piostart = 0,     ; starting from processor 0
 piostride = 36,   ; number of intervals between IO processsors.  pioprocs * piostride = total number of procs.
 pioshift = 1,     ; Shift PIO master to this processor (instead of default 0)
/
```

**Comment by davegill** [comment]
@kkeene44 @smileMchen 
We should do this from our develop branch. It would allow users to cut and paste directly.

**Comment by smileMchen** [comment]
@davegill  I will change these files and put them to develop branch.

**Comment by smileMchen** [comment]
This issue has been addressed.
