### ISSUE TITLE
v4.0, v4.01 use_theta_m with input_from_file=.f., d02 dry theta field = 0 at init

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#660]
@powersjg

At the initial time of the WRF model, the perturbation dry potential temperature field ("T" in the netcdf file) for d02 (and greater) is identically zero when the initial conditions for the fine-domain fields are manufactured via horizontal interpolation (in the WRF Registry, this horizontal interpolation at the initial time is activted through the "d" switch in the nest options).

This error is noticed when
```
 &time_control
 input_from_file                     = .true.,.false.,.false.,
 /
```
```
 &domains
 max_dom                             = 2,
 /
```
```
 &dynamics
 use_theta_m                        = 1,
 /
```

**Comment by davegill** [comment]
closed by #674 "Fix zero-valued d02 dry potential temp pert, from horiz interpolation"

**Comment by r-rarthur** [comment]
@davegill I have noticed a similar issue where on a restart run with write_hist_at_0h_rst=.true., the initial T output for (d02 and greater) is 0. All other variables seem fine. I think I fixed this by adding an "r" to th_phy_m_t0 in  Registry.EM_COMMON. If this is correct, perhaps it should be added to the next release.

**Comment by daliagachc** [comment]
ditto
