### ISSUE TITLE
Arbitrary shape domains

### ISSUE THREAD

**Issue by nbald** [wrf-model/WRF#708]
Hello

Having capability for arbitrary shape domains would be a great addon for WRF.
It would allow to save computation power when doing large grid / high-resolution simulations over seaside or mixed flat-land / mountainous area.

I did a quick survey of the actual code and internal mechanisms of WRF, and it looks like to me that it could be implemented without major modification.

I think that I am able to do the necessary coding, and I would be happy to give it a try.

I am looking for an academical or private institution that would be willing to:
- sponsor the software development
- assist me with the associated scientific validation and publication

Anyone interested?

**Comment by davegill** [comment]
@nbald @mgduda 
Nicholas,
Since the MPAS model is able to handle arbitrarily shaped regional domains, we do not view it as a priority to implement this capability into WRF. While the work could be accomplished in WRF, the associated pre- and post-processor retrofit would be large.
