### ISSUE TITLE
DA CRTM level_pressure(0) value

### ISSUE THREAD

**Issue by jamiebresch** [wrf-model/WRF#728]
In var/da/da_radiance/da_get_innov_vector_crtm.inc:
Atmosphere(1)%Level_Pressure(0) should be TOA_PRESSURE (from crtm_module), not model_ptop.

**Comment by jamiebresch** [comment]
Sorry about the confusion about water_content. I have modified the issue.
The kg/kg to kg/m2 conversion is done in the later part of the code.
To improve the readability of the code, it'd be better to add a comment around the
assignment of water_content and move the conversion code closer to the assignment.

**Comment by liujake** [comment]
I remember the same thing from my old memory (I implemented this many years ago).

**Comment by jamiebresch** [comment]
Great. Thanks, JJ. That is exactly the kind of information I'd like to have.
