### ISSUE TITLE
Binary files of lookup data troubles for double precision build/run

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#754]
@kkeene44 @smileMchen @davegill 
For the new MP schemes that are getting into the WRF model, if there are binary lookup tables that are supplied by the developer, we need to do one of the following two items before v4.1 release:
1. put a controlled stop in check_a_mundo for schemes that should not be run in real*8
2. supply a real*8 data file, modify build so the correct file gets linked into the run directories

**Comment by mgduda** [comment]
Would a third option be to read the look-up data into `real(kind=4)` temporary variables, then transfer those to variables of the native kind, letting the compiler handle the type conversion?

**Comment by smileMchen** [comment]
Following the suggestion of Michael, I have modified the code phys/module_mp_jensen_ishmael.F to make it work for both single and double precision. A test case with double precision has been run and the results look fine. 
I put the code in /mmmtmp/chenming/. Please  take a look and let me know if you have any suggestions. 
Thanks.

**Comment by smileMchen** [comment]
@mgduda 
Michael,
Thanks for pointing out the problem. It is a bug. I have modified the code.

**Comment by mgduda** [comment]
Actually, if the issue is just in the Jensen ISHMAEL scheme, the look-up tables appear to be formatted text, so there may not be any endian issues. See my comment on PR #725 .

**Comment by davegill** [comment]
@smileMchen 
Ming,
Was this issue resolved? If so, would you close it.

**Comment by smileMchen** [comment]
@davegill 
Dave,
I believe this issue has been solved by Andrea.
