### ISSUE TITLE
Building WRF  error:   undefined reference to `nf_set_fill_'   ........

### ISSUE THREAD

**Issue by boyucjz** [wrf-model/WRF#813]
WRFV4.0.TAR.gz
netcdf-4.1.3.tar.gz
 centos7 64

error:
 undefined reference to `nf_set_fill_'
undefined reference to `nf_enddef_'
wrf_io.f:(.text+0x1f71b): undefined reference to `nf_close_'
wrf_io.f:(.text+0x22110): undefined reference to `nf_put_att_double_'
wrf_io.f:(.text+0x24503): undefined reference to `nf_put_att_text_'
wrf_io.f:(.text+0x3958b): undefined reference to `nf_inq_dimlen_'
field_routines.f:(.text+0x55): undefined reference to `nf_put_vara_real_'
field_routines.f:(.text+0x838): undefined reference to `nf_put_vara_int_'
.........
........
........

**Comment by davegill** [comment]
@boyucjz 
Please repost this on the WRF Forum.
Go to `forum.mmm.ucar.edu`. In the "WRF Support" section you will see "WRF Model", click that. The first option is "WRF Compiling/Installation".
