### ISSUE TITLE
DA should check and stop when ensdim_alpha>0 and cv_options=3.

### ISSUE THREAD

**Issue by jamiebresch** [wrf-model/WRF#867]
Alpha control variable is not implemented for cv_options=3.
When running for EnVar with cv_options=3, da_wrfvar.exe runs but has nonsense gradient values.

**Comment by liujake** [comment]
Yes. We need a check for this.

**Comment by jjguerrette** [comment]
See https://github.com/wrf-model/WRF/pull/871.  We could update the User Guide as well.  Is the user guide still in the drafting stage?

**Comment by davegill** [comment]
@jjguerrette 
JJ,
It is a living document. We tend to work on updates just before tutorials.
