### ISSUE TITLE
WRF v4.1 compilation

### ISSUE THREAD

**Issue by RobWatersIEA** [wrf-model/WRF#886]
Hi WRF team, 

Trying to compile the new V4.1 WRF and struggling to compile. 

Fatal Error: Can't find an intrinsic module named 'ieee_arithmetic' at (1)

Which can be solved upgrading to gcc/gfortran version >= 5.0. 

The issue is it this seems to break compiling the openMPI: 

Fatal Error: Cannot read module file ‘mpi.mod’ opened at (1), because it was created by a different vers$
compilation terminated

Linux version 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

gcc/gfortran from devtoolset-7

OpenMPI via EPEL
yum install -y epel-release 
yum -y install netcdf-openmpi-devel.x86_64 netcdf-fortran-openmpi-devel.x86_64 netcdf-fortran-openmpi.x86_64 hdf5-openmpi.x86_64 openmpi.x86_64 openmpi-devel.x86_64

Is there a better way to get the openmpi requirements? 

Thanks in advance for any help, 

Rob

**Comment by davegill** [comment]
@RobWatersIEA 
Rob,
This problem would be better to be posted on the WRF Forum:
http://forum.mmm.ucar.edu
I have a solution (take a look at https://github.com/wrf-model/WRF/pull/803), and would like to have the answer posted in the correct location.
I am closing this issue
