### ISSUE TITLE
"Segmentation fault occurred" when use Jensen's ISHMAEL scheme (mp_physics=55) in WRFV4.1

### ISSUE THREAD

**Issue by sfhua** [wrf-model/WRF#902]
This error occurred when use Jensen's ISHMAEL scheme (mp=55) , while simulations with other mp_physics options are running well.

RRTMG radiation  scheme (ra_sw_physics=4, ra_lw_physics=4) and positive-definite advection scheme (moist_adv_opt=2, scalar_adv_opt=2) are used, and time step=6s.

**Comment by davegill** [comment]
Would you please repost this to the WRF Forum: forum.mmm.ucar.edu
If you have never used the WRF Forum before, you will be asked to register.

The Forum is set up to permit back and forth dialogue to uncover the problems with a simulation. To move the process along, provide your namelist.input file and the important rsl files. Consider that additional information you may be able to provide: in which domain does the error occur, is it immediate, is it after a lateral bc update, is the problem location near convection or over high topography, were there preceding CFLs, does this reproducibly happen with this case, with the same set up does the model typically fail, are you using non-standard optimizations, have you used this input data before, is there an unusual episodic event in the domain, etc.
