### ISSUE TITLE
ieee_arithmetic usage

### ISSUE THREAD

**Issue by letmaik** [wrf-model/WRF#905]
WRF 4.1 unconditionally added uses of ieee_arithmetic in some places, e.g. https://github.com/wrf-model/WRF/blob/dd5c4c3afdc01a11f0ee4d37969b0617fd72435f/phys/module_checkerror.F#L72-L73

Pre-4.1 code uses a check:
https://github.com/wrf-model/WRF/blob/dd5c4c3afdc01a11f0ee4d37969b0617fd72435f/frame/module_clear_halos.F#L29-L31

I couldn't find anything in the changelog about dropping support for compiler (versions) without ieee_arithmetic (e.g. gfortran < 5). Can this be made explicit or otherwise checks be used everywhere?

**Comment by davegill** [comment]
@letmaik 
Maik,
There is no intent to not support the default version of GNU that comes with most Linux distributions. There are still a small number of IEEE occurrences, so we can continue to wrap those in ifdefs.
```
>find . -name \*.F -exec grep -i ieee_arithmetic {} \; -print
        use, intrinsic :: ieee_arithmetic
./dyn_nmm/solve_nmm.F
    use,intrinsic :: ieee_arithmetic
./frame/module_clear_halos.F
 use, intrinsic :: ieee_arithmetic
 use, intrinsic :: ieee_arithmetic
./phys/module_checkerror.F
 use, intrinsic :: ieee_arithmetic
./phys/module_gocart_coupling.F
      use, intrinsic :: ieee_arithmetic
./phys/module_mp_gsfcgce_4ice_nuwrf.F
 use, intrinsic :: ieee_arithmetic
 use, intrinsic :: ieee_arithmetic
./phys/module_ra_goddard.F
```

When we received the recent additions of physics schemes from Goddard (module_ra_goddard.F and module_mp_gsfcgce_4ice_nuwrf.F), they were doing some non-standard tests for NaNs. The port that we introduced to use the available IEEE standard should have also included ifdef protections (as we have done before). 

We will get this issue addressed in the release-v4.1.1 branch (and will ask you to verify that it works).
