### ISSUE TITLE
NDOWN v4.1: vertical refinement is broken

### ISSUE THREAD

**Issue by Enzoupi** [wrf-model/WRF#917]
Hi everybody !

Just to let you know about a possible bug in Ndown.exe in version 4.1 when using vertical interpolation.

Here is the results of ndown using version 3.9 and `vert_refine_fact =2`

![wrfbdy_wrf39](https://user-images.githubusercontent.com/16925356/58245389-f608af80-7d54-11e9-9748-8b95f80a3d6e.png)

Here is the results of ndown using version 4.1 and `vert_refine_fact =2`

![wrfbdy_wrf41](https://user-images.githubusercontent.com/16925356/58245511-3d8f3b80-7d55-11e9-9a98-263a12ae69ba.png)

In both cases, the inputs used are generated by the same version as ndown (wrf 3.9 when using ndown 3.9 and wrf 4.1 when using ndown 4.1). Apart from things that changed between the two version the namelists are identical.

Also, inputs from previous domains using WRF 4.1 look absolutely normal.

It might be me doing something wrong here but just in case it is not the case, I prefer to mention it here :)

All the best,

Enzo

**Comment by kalundquist** [comment]
Hi Enzo,
Just FYI, you can use vertical nesting for concurrently run domains now, rather than using ndown.  I am not sure if that capability would suit your needs or not.  Vertical nesting works in v3.9.1.1 but was broken in 4.0 when WRF went to the hybrid coordinate.  We have a fix for this, but it is in the queue to be merged into the code.

**Comment by davegill** [comment]
@Enzoupi 
Enzo,
Would you please post this to the WRF Forum: forum.mmm.ucar.edu. Also, please attach your namelist.input file that you used for ndown. This problem is definitely correctly posted here as a valid "issue", but we'll want to take all of the back and forth iterating to the forum.

**Comment by davegill** [comment]
@Enzoupi @kalundquist @weiwangncar @kkeene44 
Enzo,
Please take a look at #901 "Fix vertical refinement, broken from v4.0 through v4.1". You should be able to clone the davegill fork and checkout the fix_v_refinement_with_hyb_coord branch. I added in the computation of the 1d arrays for the hybrid coordinate into ndown. That missing piece fits the symptoms that you reported and our internal testing corroborated. However, the mods may be necessary but not sufficient. Let us know what you find.

Also, we still want this officially posted on the forum, so other users can search for it.

Thanks for the very clear and detailed description of the problem. I'm going to edit the title a bit.

**Comment by davegill** [comment]
@Enzoupi 
Enzo,
Also, for clarification ... you mention in the comment "vertical refinement option = 2", but do you mean `vert_refine_factor = 2`?

**Comment by Enzoupi** [comment]
@davegill 

Thanks for all the answers and edits on my original post !

Regarding the post on the WRF forum it is what I did in the first place : [http://forum.wrfforum.com/viewtopic.php?f=10&t=11277](url). Hope it does the job otherwise i will edit the post there !

Thanks for the tips on how to correct it ! However i am dealing with another problem of seg fault in SFCLAY so I will have to jump back to WRF 3.X versions for a while in order to find the origin of this problem ! If I have the chance to go back on 4.1 I'll definitely let you know !

Sorry for the ambiguity : it is indeed `vert_refine_fact =2`, I will edit my post.

All the best,

Enzo

**Comment by ozanmert** [comment]
_"However i am dealing with another problem of seg fault in SFCLAY..."_

Enzo, did you find out what the problem was about SFCLAY and did you solve it? I am also getting seg fault just on that step! Thanks in advance.

**Comment by Enzoupi** [comment]
> Enzo, did you find out what the problem was about SFCLAY and did you solve it? I am also getting seg fault just on that step! Thanks in advance.

Hi @ozanmert, this is completely off topic here !

But in a few words, in have numerical instability due to my complex topography. Try to make history files every second to see where it craches may help. Or decrease vertical resolution / reduce drastically the time step.

Hope that helps,

Enzo
