### ISSUE TITLE
WRFDA V4.1.1 does not compile in serial mode.

### ISSUE THREAD

**Issue by jamiebresch** [wrf-model/WRF#923]
In var/da/da_vtox_transforms/da_vtox_transforms.f90,
use da_par_util, only : true_mpi_real, mpi_sum, comm
should be placed inside #ifdef DM_PARALLEL.
It is a bug introduced in V4.1.1 in commit dba3464.

**Comment by davegill** [comment]
@jjguerrette @liujake 
JJ and Jake,
Would you guys put together a PR for this. The usual, v4.1.2 as the base branch.

**Comment by liujake** [comment]
@jamiebresch Can you make a bug fixPR to v4.1.2 branch?
