### ISSUE TITLE
aercu_opt=2 error

### ISSUE THREAD

**Issue by yijingsub** [wrf-model/WRF#924]
hello  
 i  set mp_physics =40 and cu_physics= 11，aercu_opt  = 2 in namelist.input as below ,and run real.exe is ok ,but when run wrf.exe, it appeared

  phy_init:  start_of_simulation =  T
  calling nl_get_iswater, nl_get_isice, nl_get_mminlu_loc
  after nl_get_iswater, nl_get_isice, nl_get_mminlu_loc
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
wrf.exe            0000000004AC0C94  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002ACD366B95E0  Unknown               Unknown  Unknown
wrf.exe            0000000003560240  Unknown               Unknown  Unknown
wrf.exe            000000000355EFB8  Unknown               Unknown  Unknown
wrf.exe            000000000353B5D1  Unknown               Unknown  Unknown
wrf.exe            0000000002D5B097  Unknown               Unknown  Unknown
wrf.exe            00000000023A5EB1  Unknown               Unknown  Unknown
wrf.exe            0000000001D958B1  Unknown               Unknown  Unknown
wrf.exe            000000000040DF55  Unknown               Unknown  Unknown
wrf.exe            000000000040CDF5  Unknown               Unknown  Unknown
wrf.exe            000000000040CD9E  Unknown               Unknown  Unknown
libc-2.17.so       00002ACD368E7C05  __libc_start_main     Unknown  Unknown
wrf.exe            000000000040CCA9  Unknown               Unknown  Unknown
                                                                                

how can i solve the ploblem

thank you very much

 &time_control
 run_days                            = 0,
 run_hours                           = 0,
 run_minutes                         = 0,
 run_seconds                         = 0,
 start_year                          = 2015, 2014, 2999,
 start_month                         = 03,   12,  06,
 start_day                           = 12,  30,    11,
 start_hour                          = 00,   00,   12,
 start_minute                        = 00,   00,   00,
 start_second                        = 00,   00,   00,
 end_year                            = 2015,2015, 2999,
 end_month                           = 03,  01,   06,
 end_day                             = 15,  08,   12,
 end_hour                            = 00,   00,   12,
 end_minute                          = 00,   00,   00,
 end_second                          = 00,   00,   00,
 interval_seconds                    = 21600
 input_from_file                     = .true.,.true.,.true.,
 history_interval                    = 60,   60,   60,
 frames_per_outfile                  = 1, 1000, 1000,
 restart                             = .false.,
 restart_interval                    = 500000,
 io_form_history                     = 2,
 io_form_restart                     = 2,
 io_form_input                       = 2,
 io_form_boundary                    = 2,
 auxinput4_inname                    = 'wrflowinp_d<domain>'
 auxinput4_interval                  = 360,
 io_form_auxinput4                   = 0,
 debug_level                         = 1000,
 output_diagnostics                  = 1,
 io_form_auxhist3                    = 2,
 auxhist3_interval                   = 1440,
 frames_per_auxhist3                 = 1,
 force_use_old_data                  = T
/

 &domains
 time_step                           = 180,
 time_step_fract_num                 = 0,
 time_step_fract_den                 = 1,
 max_dom                             = 1,
 e_we                                = 208,  145,   94,
 e_sn                                = 97,  124,   91,
 e_vert                              =  40,   32,   20,
 eta_levels                          = 1.000, 0.995, 0.990, 0.985, 0.980,0.975, 0.970, 0.960,
                                       0.950, 0.940,0.930, 0.920, 0.910, 0.900, 0.890,0.880,
                                       0.860, 0.8338386, 0.7876773, 0.741516, 0.6953547, 0.6149445, 0.5417048, 0.4751021,
                                       0.4146363, 0.3598392, 0.3102725, 0.265526, 0.2252167, 0.1889867, 0.1565017, 0.1274503,
                                       0.1017843, 0.07977638, 0.06090509, 0.04472341, 0.03084801, 0.01895018, 0.008748077, 0.000,
 dx                                  = 27000, 3000, 6666.66,
 dy                                  = 27000, 3000, 6666.66,
 p_top_requested                     = 1000,
 num_metgrid_levels                  = 27,
 num_metgrid_soil_levels             = 4,
 grid_id                             = 1,     2,     3,
 parent_id                           = 0,     1,     2,
 i_parent_start                      = 1,     49,    30,
 j_parent_start                      = 1,     51,    30,
 parent_grid_ratio                   = 1,     3,     3,
 parent_time_step_ratio              = 1,     3,     3,
 feedback                            = 0,
 smooth_option                       = 0,
 /

 &physics
  physics_suite                       = 'CONUS'
 mp_physics                          = 40,     2,     2,
 progn                               = 0 ,     1,     0,
 naer                                = 1e9
 ra_lw_physics                       = 14,     4,     1,
 ra_sw_physics                       = 14,     5,     2,
 radt                                = 3,     3,    10,
 sf_sfclay_physics                   = 1,     1,     1,
 sf_surface_physics                  = 2,     2,     2,
 bl_pbl_physics                      = 1,     1,     1,
 mfshconv                            = 0,
 bldt                                = 0,     0,     0,
 cu_physics                          = 11,     5,     0,
 cu_diag                             = 1,     1,     0,
 cugd_avedx                          = 3,
 cudt                                = 0,     0,     1,
 ishallow                            = 1,
 isfflx                              = 1,
 ifsnow                              = 0,
 icloud                              = 1,
 surface_input_source                = 3,
 num_soil_layers                     = 4,
 num_land_cat                        = 24,
 sf_urban_physics                    = 1,     0,     0,
 aercu_opt                           = 2
 alevsiz_cu                          = 30,
 no_src_types_cu                     = 10
 scalar_pblmix                       = 1
 mp_zero_out                         = 2,
 maxiens                             = 1,
 maxens                              = 3,
 maxens2                             = 3,
 maxens3                             = 16,
 ensdim                              = 144,
 cu_rad_feedback                     = .false.,
 topo_wind                           = 0,
 usemonalb                           = .true.,
 sst_update                          = 0,
 sst_skin                            = 0,
 /

 &fdda
 /
 &dynamics
 w_damping                           = 1,
 diff_opt                            = 1,
 km_opt                              = 4,
 diff_6th_opt                        = 0,      0,      0,
 diff_6th_factor                     = 0.12,   0.12,   0.12,
 base_temp                           = 290.
 damp_opt                            = 0,
 zdamp                               = 5000.,  5000.,  5000.,
 dampcoef                            = 0.2,    0.2,    0.2
 khdif                               = 0,      0,      0,
 kvdif                               = 0,      0,      0,
 non_hydrostatic                     = .true., .true., .true.,
 moist_adv_opt                       = 2,      1,      1,
 scalar_adv_opt                      = 2,      1,      1,
 chem_adv_opt                        = 2,      1,      1,
 tke_adv_opt                         = 2,      2,      0,
 gwd_opt                             = 1,
 /

 &bdy_control
 spec_bdy_width                      = 5,
 spec_zone                           = 1,
 relax_zone                          = 4,
 specified                           = .true., .false.,.false.,
 nested                              = .false., .true., .true.,
 /

 &grib2
 /

 &namelist_quilt
 nio_tasks_per_group = 0,
 nio_groups = 1,
 /

**Comment by yijingsub** [comment]
@JulieSchramm @cross85 @t-brown @mgduda

**Comment by weiwangncar** [comment]
@yijingsub Can you please post it this on the Forum: http://forum.mmm.ucar.edu/?

**Comment by cxh416** [comment]
@yijingsub Did you get your question answered? I am having the same problem and can't find your question on the forum.

**Comment by davegill** [comment]
I do not see this on the forum. Please post a question there so that we can address the problem. 

In addition to the namelist.input file, add a few more pieces of information. Turn various physics options ON/OFF to try to find what is causing the seg fault. For example, does the CONUS suite work? That information will be helpful to the forum moderators.

I am closing this issue because we want this handled on the forum.

**Comment by sael9740** [comment]
@weiwangncar - linking you since this is a closed issue and I'm not sure anyone will notice this otherwise.

I figured out what was happening here. If the aerosol data file `CESM_RCP4.5_Aerosol_Data.dat` doesn't exist then the code doesn't do anything:

https://github.com/wrf-model/WRF/blob/21c72141142fc6c8d203d2bf79f1990e45a0aef8/phys/module_physics_init.F#L5508-L5533

The allocatable arrays `aeroin`, `aerpoin`, etc. arrays don't get allocated and they are accessed in the calls to `interp_vec_cu` right after that, which would cause the seg faults that people were seeing.

It may be more user friendly to have a call to `wrf_error_fatal()` if the file isn't found, particularly since it isn't included in the standard `run/*` data files and the documentation doesn't say anything about needing this file, where to find it or what to name it from what I can tell.

**Comment by weiwangncar** [comment]
@sael9740 Thanks for pointing it out. This seems to be reasonable solution. Will work on a PR.

**Comment by sael9740** [comment]
> @sael9740 Thanks for pointing it out. This seems to be reasonable solution. Will work on a PR.

I can do that if you would like?

**Comment by weiwangncar** [comment]
@sael9740 Please do! Thanks!

**Comment by sael9740** [comment]
Should I include any information on where to get the data in the error message? Is there any documentation anywhere about this data?

**Comment by weiwangncar** [comment]
@sael9740 That would be useful info to have, especially for users who don't read other document...

**Comment by sael9740** [comment]
> especially for users who don't read other document...

Which document are you referring to?

**Comment by weiwangncar** [comment]
@sael9740 I was thinking of the User's Guide. But it isn't there. We should add it there and the README.namelist file where this dataset is referenced. That leaves the release note for the code (v4.0 release) and using 'git log' on the module to find more info.

**Comment by sael9740** [comment]
Ok I'm thinking something like this:

```fortran
INQUIRE(FILE='./CESM_RCP4.5_Aerosol_Data.dat', EXIST=exists)

IF (exists) THEN
...
ELSE
    CALL wrf_error_fatal('Missing file "CESM_RCP4.5_Aerosol_Data.dat" (required for aercu_opt = 1 or 2). ' // &
        'Please refer to chapter 5 of the WRF users guide for more information.')
END IF
```

**Comment by weiwangncar** [comment]
@sael9740 If you could add something like this in run/README.namelist file: 
 aercu_opt                           option to control aerosol interaction in MSKF and Morrison microphysics (mp_physics=40)
                                     = 0: no aerosol interaction
                                     = 1: aerosol interaction with MSKF only
                                     = 2: aerosol interaction with both MSKF and Morrison
                                   (input file downloadable from 
                                    http://www2.mmm.ucar.edu/wrf/src/wrf_files/CESM_RCP4.5_Aerosol_Data.tar.gz,
                                    and link one of the two files to CESM_RCP4.5_Aerosol_Data.dat before running)

you may be able to say 'Please refer to README.namelist file for more information'. Since this file is more accessible.
