### ISSUE TITLE
Bad Wind and Temperature values with diag_nwp2=1

### ISSUE THREAD

**Issue by nbald** [wrf-model/WRF#935]
I am getting strange values from phys/module_diag_trad_fields.F

I am suspecting a missing /2 division here:
```
L97:
umet(i,k,j) = (u(i,k,j)+u(i+1,k,j))*cosa(i,j) - (v(i,k,j)+v(i,k,j+1))*sina(i,j)
vmet(i,k,j) = (u(i,k,j)+u(i+1,k,j))*sina(i,j) + (v(i,k,j)+v(i,k,j+1))*cosa(i,j)
```

Also, the temperatures I get from this diagnostic seems ~10K lower than expected. (T2 is OK)

```
L81:
IF ( use_theta_m .EQ. 1 ) THEN
  temperature(i,k,j) = ( ( t(i,k,j) + t0 ) * ( (pb(i,k,j)+pp(i,k,j)) / p1000mb ) ** rcp ) / ( 1. + (R_v/R_d) * qv(i,k,j) )
ELSE
  temperature(i,k,j) = ( ( t(i,k,j) + t0 ) * ( (pb(i,k,j)+pp(i,k,j)) / p1000mb ) ** rcp )
END IF
```

- using the latest master branch
- use_theta_m=1
- domain over France

**Comment by nbald** [comment]
Here is the definition of temperature in module_diag_zld.F

`td = (t(i,ke ,j)+t0)*(pd/p1000mb)**rcp`

This one have no special case for use_theta_m

**Comment by dudhia** [comment]
These look like valid points.
Not sure about why the temperatures would look cold, however.
We need to check.
Jimy

**Comment by nbald** [comment]
I do not understand why the temperature as wrong. As a temporary solution, I disabled use_theta_m. Now it looks fine.
I think that the theta_m option should be used with a lot of care, since many tools / diagnostics / post-processing are still using the old formula. I am not sure if NCL or wrf-python are up-to-date.

**Comment by dudhia** [comment]
For post-processing we have made sure the T wrfout array has the old
definition whether use_theta_m is used or not.
For internal diagnostics we have identified most of these places, but may
have missed some.
Jimy

**Comment by weiwangncar** [comment]
@nbald The t field passed into this routine is the dry theta, hence the check for computing temperature is not necessary for use_theta_m = 1. Can you see if this is right in your case?

**Comment by davegill** [comment]
The pressure level diagnostics routine will have the same problem, with no consideration for moist or dry theta.
```
tu = ( t(i,ke,j) + t0 ) * ( pd / p1000mb ) ** rcp
```
