### ISSUE TITLE
WRF unable to find netcdf.inc

### ISSUE THREAD

**Issue by mahmoodn** [wrf-model/WRF#964]
I have tried to build the latest git version with netcdf-4.7.0. Although netcdf has been installed, I get this error for wrf.
```
Error : Not found /home/mahmood/06.wrf/netcdf/include/netcdf.inc
        Please check this installation of NetCDF and re-run this configure script
```
In fact there is no `netcdf.inc` 

```
[mahmood@rocks7 netcdf-c-4.7.0]$ find . -name *.inc
[mahmood@rocks7 netcdf-c-4.7.0]$ cd ../netcdf
[mahmood@rocks7 netcdf]$ find . -name *.inc
[mahmood@rocks7 netcdf]$  
```

I see that this issue has been reported but they say that wrf may use older netcdf version.
So, I want to know which version exactly works?

**Comment by TimoRoth** [comment]
I'm having the same issue, how did you solve it?

**Comment by mahmoodn** [comment]
Actually I left it to some times in the future. 
I also didn't get a solution in their forum.

**Comment by TimoRoth** [comment]
It appear like netcdf was just split into netcdf-c and netcdf-fortran. And all you have to do is install both.

**Comment by Jiangcy0712** [comment]
netcdf.inc is in the netcdf-fortran and you can copy it to the netcdf
