### ISSUE TITLE
Need check_a_mundo test: max_ts_level must be <= number of znu half layers

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#976]
From Pedro Jimenez

I found that max_ts_level should not be set to a number larger than the number of half levels. If the user accidentally set this namelist entry to a larger value, then the wrf_timeseries.F tries to use w_2  and other vars at higher levels than possible. The model would not crash but I do not know what would happen to the time series results. I found this compiling WRF in debugging mode since I set up max_ts_level to the number of full levels. Unfortunately I removed the log file with the error.

There should be a check maybe in check_a_mundo to ensure that max_ts_level is not set up to a number higher than the number of half levels.

**Comment by smileMchen** [comment]
This issue has been addressed and is closed.
