### ISSUE TITLE
How to create a 4D variable in the Registry?

### ISSUE THREAD

**Issue by bell-94** [wrf-model/WRF#987]
Hello, I am trying to add  a 4D variable to the output of the WRF model. I want to generate the variable PSD(Particle Size Distribution) which can be solved in a microphysics scheme. The variable must have 4 dimensions i,j,k and another one to express an array obtained calculating the quantity of particle for a set of diameter data that shows the different sizes of different hydrometeors.

I hope someone could help me, I would appreciate it

**Comment by davegill** [comment]
@bell-94 
This belongs in the WRF forum.
forum.mmm.ucar.edu

Please see: 
https://github.com/wrf-model/WRF/pull/528

If that WRF PR helps you, please reference it in the forum with your question.
