### ISSUE TITLE
wrfchem 4.0 undefined reference to

### ISSUE THREAD

**Issue by chojinss** [wrf-model/WRF#992]
Dear Scientists

I want to compile wrf-chem 4.0, but cannot  find the cause of the error.
Your help is desperate.

The compile options and library list are as follows:
-configure option: 3 (pgi, gcc, dmpar)
-Centos 7
-x86-64 Linux
-pgf90 18.10-1
-mpich-3.3
-netcdf 4.6.2
-hdf5 1.8.17
-jasper
-libpng
-zlib
-pnetcdf

I found and applied a fix in this forum regarding of this error, export CPATH = "/ usr / include / rpc".
But I have been getting the same error.

I think that this error message is related to chem. If I compile without kpp, are there any chem related options that I should set except for WRF_CHEM = 1?

I would be very happy if you tell me what to do for the completed compiling.
Please kindly find attached error message.

[wrf compile.zip](https://github.com/wrf-model/WRF/files/3663571/wrf.compile.zip)

**Comment by davegill** [comment]
@chojinss 
This question belongs in the WRF Forum: forum.mmm.ucar.edu

There is a section for compiling and building WRF. Unfortunately, there is no longer a group that provides support for WRF Chem. The WRF group at NCAR will not answer WRF Chem questions. The forum may have users that can help support each other.

I built the the WRF Chem code. I used GNU and MPI. I only used the WRF_CHEM=1 env var.

```
> git clone https://github.com/wrf-model/WRF
> cd WRF/ 
> setenv WRF_CHEM 1
> configure -D << EOF
32
1
EOF
> compile em_real -j 6 > & ! foo &
> tail foo
 
--->                  Executables successfully built                  <---
 
-rwxr-xr-x 1 gill p66770001 195380800 Sep 27 14:09 main/ndown.exe
-rwxr-xr-x 1 gill p66770001 195308024 Sep 27 14:09 main/real.exe
-rwxr-xr-x 1 gill p66770001 191365016 Sep 27 14:09 main/tc.exe
-rwxr-xr-x 1 gill p66770001 225729480 Sep 27 14:04 main/wrf.exe
 
==========================================================================
 
cheyenne.ucar.edu:/glade/scratch/gill/really/WRF>git branch
* master
cheyenne.ucar.edu:/glade/scratch/gill/really/WRF>git log --pretty=oneline | head
04cb7565605fe1894b4824bef7d0ee71c457f371 Merge remote-tracking branch 'origin/release-v4.1.2'
aadb3b3a31bdd9ba72eff9107871355221beefa4 update README and inc/version_decl for release-v4.1.2 (#947)
163b3124216b4ea9ebfe8d0d2bc92826a2b8faf5 Bucket fixes: rain is more conventional, flux arrays are allocated (#944)
77a7a1b91d3716db9c46a85ad4b5f55b6e89eb36 Adding new and correct changed options (#946)
6da06f4ec30ba7b34bf10be8f48ec9d227c292be Fix compile script to print model version, due to new version_decl format (#940)
2e7da0b16a33407a61fe9929bc7fd12530e524cb Bug fixes: ISHMAEL MP: single precision look-up table; prevent undefined values; nucleation limit  (#925)
f5fbd1e39b5dcf50e4f960e3db7c703852fe1fde Fix to make restarts reproducible in nests when topo_shading is used (#931)
3478f2ed12db1746c1ca41b84c26bd028b9e71dc Bug fix: traditional fields diags, u and v are 2x too large (#941)
f74767d51f5865c2286120526285a26fbb6e9868 Bug fix: diagnostics: in temperature computation, incorrectly remove moisture from DRY theta perturbation (#942)
eb4264493eabaf5156f75c726cab84bdb4ab3018 Fix to allow proper QVAPOR analysis when mp_physics is not set in namelist.input
```
