### ISSUE TITLE
error code 11

### ISSUE THREAD

**Issue by vermaparul2015** [wrf-model/WRF#996]
executed wrf.exe thrice . The process 
stopped at the the same time. 
BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 11

my namelist:
 &time_control
 run_days                            = 07,
 run_hours                           = 0,
 run_minutes                         = 0,
 run_seconds                         = 0,
 start_year                          = 2019,     2019,
 start_month                         = 04,       04,
 start_day                           = 21,       21,
 start_hour                          = 00,       00,
 start_minute                        = 00,       00,
 start_second                        = 00,       00,
 end_year                            = 2019,     2019,
 end_month                           = 04,       04,
 end_day                             = 28,       28,
 end_hour                            = 00,       00,
 end_minute                          = 00,       00,
 end_second                          = 00,       00,
 interval_seconds                    = 1800,
 input_from_file                     = .true.,   .true.,
 history_interval                    = 30,      30,
 frames_per_outfile                  = 1,        1,
 restart                             = .false.,
 restart_interval                    = 5000,
 io_form_history                     = 2
 io_form_restart                     = 2
 io_form_input                       = 2
 io_form_boundary                    = 2
 debug_level                         = 0
 /

 &domains
 time_step                           = 40,
 time_step_fract_num                 = 0,
 time_step_fract_den                 = 1,
 max_dom                             = 2,
 e_we                                = 112,      100,
 e_sn                                = 88,       76,
 e_vert                              = 36,       36,
 p_top_requested                     = 5000,
 num_metgrid_levels                  = 32,
 dx                                  = 3000,     1000,
 dy                                  = 3000,     1000,
 grid_id                             = 1,        2,
 parent_id                           = 1,        1,
 i_parent_start                      = 1,        36,
 j_parent_start                      = 1,        29,
"namelist.input" 112L, 4320C 

namelist.wps:

&share
 wrf_core = 'ARW',
 max_dom = 2,
 start_date = '2019-04-21_00:00:00',2019-04-21_00:00:00,
 end_date   = '2019-04-28_00:00:00',2019-04-28_00:00:00,
 interval_seconds = 1800,
 io_form_geogrid = 2,
 !opt_output_from_geogrid_path = 'home/charan/Build_WRF/WPS/geo_em',
 debug_level = 0,
/

&geogrid
 parent_id         =   1,1,
 parent_grid_ratio =   1,3,
 i_parent_start    =   1,36,
 j_parent_start    =   1,29,
 e_we              =   112,100,
 e_sn              =   88,76,
 !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! The default datasets used to produce the HGT_M, GREENFRAC,
 ! and LU_INDEX/LANDUSEF fields have changed in WPS v3.8. The HGT_M field
 ! is now interpolated from 30-arc-second USGS GMTED2010, the GREENFRAC
 ! field is interpolated from MODIS FPAR, and the LU_INDEX/LANDUSEF fields
 ! are interpolated from 21-class MODIS.
 !
 ! To match the output given by the default namelist.wps in WPS v3.7.1,
 ! the following setting for geog_data_res may be used:
 !
 ! geog_data_res = 'gtopo_10m+usgs_10m+nesdis_greenfrac+10m','gtopo_2m+usgs_2m+nesdis_greenfrac+2m',
 !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !
 geog_data_res = '2m','2m'
 dx = 3000,
 dy = 3000,
 map_proj = 'mercator',
 ref_lat   =  29.917,
 ref_lon   =  79.53,
 truelat1  =  29.917,
 truelat2  =  0,
 stand_lon =  79.53,
 geog_data_path = '/home/charan/Build_WRF/WPS/WPS_GEOG/'
 ref_x = 50.0,
 ref_y = 40.0,
/

&ungrib
 out_format = 'WPS',
 prefix = 'FILE',
/

&metgrid
 fg_name = 'FILE'
 io_form_metgrid = 2,
 opt_output_from_metgrid_path = '/home/charan/Build_WRF/WRFV3/test/em_real',
/

**Comment by davegill** [comment]
@vermaparul2015 
This type of problem belongs on the WRF forum. 
Please post this on forum.mmm.ucar.edu.
Include the following:
1. "ls -ls" in the directory you are running WRF
2. a tar file of all of the rsl* files
3. the namelist.input file
4. your configure.wrf file

**Comment by peisipand** [comment]
vermaparul2015：

Hello, I have the same problem as you.So have you solved the problem?

**Comment by davegill** [comment]
@peisipand 
As stated above, this type of problem belongs on the WRF forum. 
Please post this on forum.mmm.ucar.edu.
Include the following:
1. "ls -ls" in the directory you are running WRF
2. a tar file of all of the rsl* files
3. the namelist.input file
4. your configure.wrf file
